### ISSUE TITLE
Create and publish Software Bill of Materials (SBOMs) for our operators, products and docker images

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#168]
# SBOM for our Operators

We want to produce SBOMs for all our operators and the operator images.

```[tasklist]
- [ ] https://github.com/stackabletech/issues/issues/369
- [x] Introduce cargo-cyclonedx in build process
- [ ] https://github.com/stackabletech/issues/issues/411
- [ ] https://github.com/stackabletech/issues/issues/398
- [ ] https://github.com/stackabletech/internal-issues/issues/46
```

# SBOM for our products

See https://cwiki.apache.org/confluence/display/COMDEV/SBOM for a list of Apache products that already support SBOMs. Thanks to @dongjoon-hyun who worked on most of these!

```[tasklist]
- [ ] https://github.com/stackabletech/issues/issues/512
- [ ] https://github.com/stackabletech/internal-issues/issues/46
```

Unfortunately, we will not be able to use them all so we might have to create our own SBOMs.

Generating the SBOMs is only the first step though. We should mirror them somewhere and publish them as well to merge them with our Docker images and any custom additions.

**Comment by teozkr** [comment]
This sounds great, but I have a sneaking suspicion that this kind of automatic processing would be quite complicated, especially for our products, where we just use their release artifacts rather than integrating with their build systems.

I'd absolutely like to see this at some point, but it feels like it's a big and important enough issue that we need some kind of stopgap until then. I'd propose:

1. Add a comment or metadata file to each NXRM package folder with a URL to the upstream
2. (If NXRM supports it) set up pull-through mirroring, so that we automatically download artifacts from a fixed upstream URL pattern the first time they are requested

**Comment by lfrancke** [comment]
I just stumbled across this https://thenewstack.io/how-to-improve-docker-security-with-docker-sbom-and-syft/

**Comment by lfrancke** [comment]
And now across this: https://www.heise.de/news/Open-Source-Tool-von-Microsoft-erstellt-Software-Bill-of-Materials-7177889.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag

https://github.com/microsoft/sbom-tool

**Comment by lfrancke** [comment]
This is a good summary of tools used to generate SBOMs: https://cloudsmith.com/blog/how-to-generate-and-host-an-sbom/

**Comment by fhennig** [comment]
Once we have the SBOMs I suggest we work on this: https://github.com/stackabletech/internal-issues/issues/46
