### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by nightkr** [stackabletech/issues#172]
## Description

We want to support LDAP authentication in the given products below.

### Products

```[tasklist]
### Tasks
- [x] https://github.com/stackabletech/airflow-operator/issues/100
- [x] https://github.com/stackabletech/druid-operator/issues/144
- [x] https://github.com/stackabletech/nifi-operator/issues/273
- [x] https://github.com/stackabletech/superset-operator/issues/5
- [x] https://github.com/stackabletech/trino-operator/issues/38
- [x] https://github.com/stackabletech/documentation/issues/300
- [x] https://github.com/stackabletech/issues/issues/322
- [x] https://github.com/stackabletech/druid-operator/issues/382
```

### Not in scope:
- HBase -> Kerberos will talk to LDAP
- Hadoop HDFS -> Kerberos will talk to LDAP
- Hive -> not required for metastore
- Kafka -> not supported nativly
- OPA: Will talk to LDAP for authorization (not in scope here for authentication)
- Spark -> not required
- ZooKeeper ->not supported nativly
- https://github.com/stackabletech/druid-operator/issues/383

## Acceptance

- [ ] LDAP is configurable in the CRD using the [LDAP structs](https://github.com/stackabletech/operator-rs/blob/main/src/commons/ldap.rs) from operator-rs
- [ ] A user/admin can configure the product to use a LDAP server for authentication
- [ ] There is documentation on how to configure the product with LDAP using the Custom Resource
- [ ] Optional: There is an example demonstrating the product with LDAP
- There are tests which include:
  - [ ] OpenLDAP is installed and accessible via the product
  - [ ] Optional: LDAP works encrypted and unencrypted
  - [ ] Queries / access to the product works with the LDAP credentials
- [ ] It is added to the feature tracker (ask Lars for help)

**Comment by maltesander** [comment]
I checked and all existing LDAP issues are mentioned here. I checked the unknown / not supported products and this is what i came up with:

### Products

- [ ] HBase -> Hadoop group mapper maps between LDAP and HBase users https://hbase.apache.org/book.html#hbase.accesscontrol.configuration
- [ ] HDFS  -> Group level authorization via LDAP possible
- [ ] Hive  -> Hive server supports LDAP, not sure about the metastore 
- [ ] Kafka -> Only with plugins. There are some available but not really maintained or just for Kafka 2.x.x (https://github.com/instaclustr/kafka-ldap-integration, https://github.com/insightlake/Kafka-LDAP-Security)
- [ ] Spark -> Not needed
- [ ] ZooKeeper -> Group permissions can be set up via AuthenticationProvider

**Comment by lfrancke** [comment]
Thank you @fhennig. Is that something we can already get started on?

**Comment by fhennig** [comment]
The ticket lists a few options, we still have to pick. But we can refine it!

**Comment by fhennig** [comment]
After we have LDAP authentication everywhere, it would be good to get the LDAP groups into OPA, so support group based authorization. There is already a ticket for it, and I wanted to link it here: https://github.com/stackabletech/opa-operator/issues/237

**Comment by lfrancke** [comment]
This is all done. I decided to keep the last remaining issue as out-of-scope and I'll close this.

Thank you everyone!
