### ISSUE TITLE
Build and use custom Python image in kuttl tests

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#230]
# Description

kuttl tests use the official Python base image to install dependencies needed for running the tests. - These dependencies need to be installed for every test. There multiple problems with this:

- It can fail if the pip repository happens to be unavailable at that  moment.
- Makes tests slower.
- On OpenShift clusters, a virtual environment needs to be created under `/tmp` because that is the only place where the user has write access (by default).
- The virtual environment created above needs to be `activate`d for every Python script that is `kubectl exec`d which is error prone and sometimes just not possible.

# Acceptance criteria

- [x] A Stackable image exists with Python and requirements needed **by all kuttl tests** across all operators.
- [x] kuttl tests have been updated to to use this image instead of the current Python base image.

Affected operators:

- [ ] zookeeper
- [ ] opa
- [ ] kafka
- [ ] hdfs
- [ ] nifi
- [ ] druid
- [ ] trino
- [ ] superset
- [x] secret  (doesn't use python in kuttl tests)
- [ ] hive
- [x] spark-k8s (doesn't use python in kuttl tests)

**Comment by razvan** [comment]
Fixed.
