### ISSUE TITLE
Set resource requests and limits for product pods

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#241]
As a user, i want to set memory, CPU and storage requests and limits for the Kubernetes pods via the CRD. This must be configured in the managed products (e.g set "-Xmx" Java heap settings) as well.

An example how the resources are definend (see [operator-rs](https://github.com/stackabletech/operator-rs/blob/e56110dd394c98a67f21ff17f7fab6c88f3aa322/src/commons/resources.rs#L77) for more detail):
```
resources:
  memory:
    limit: "1"
  cpu:
    min: "2"
    max: "3"
  storage:
    data:
      capacity: "10Gi"
```
A full example can be seen [here](https://github.com/stackabletech/nifi-operator/blob/main/examples/simple-nifi-cluster.yaml) (NiFi).

General Tasks:
- [x] https://github.com/stackabletech/documentation/issues/263

Implementations for the individual products:

- [x] https://github.com/stackabletech/trino-operator/issues/248
- [x] https://github.com/stackabletech/druid-operator/issues/277
- [x] https://github.com/stackabletech/hbase-operator/issues/220
- [x] https://github.com/stackabletech/airflow-operator/issues/139
- [x] https://github.com/stackabletech/hive-operator/issues/217
- [x] https://github.com/stackabletech/superset-operator/issues/239
- [x] https://github.com/stackabletech/opa-operator/issues/325
- [x] https://github.com/stackabletech/spark-k8s-operator/issues/128
- [x] https://github.com/stackabletech/nifi-operator/issues/252
- [x] https://github.com/stackabletech/kafka-operator/issues/283
- [x] https://github.com/stackabletech/hdfs-operator/issues/67
- [x] https://github.com/stackabletech/zookeeper-operator/issues/348

**Comment by maltesander** [comment]
Does it make sense to do this for every operator before https://github.com/stackabletech/operator-rs/pull/445 is merged?

**Comment by sbernauer** [comment]
For me personally yes, because this may be a blocker when using real data volumes. We already had random restarts during our hackathon.

**Comment by maltesander** [comment]
Yeah agree. https://github.com/stackabletech/operator-rs/pull/445 is currently blocked anyways. An we would already have all the crd changes in and only need to adapt to the fragment stuff later.

**Comment by lfrancke** [comment]
Do we have a CRD snippet/ADR for this? Could you link to it if so?

**Comment by sbernauer** [comment]
This Epic is currently in progress (currently @maltesander works on Trino). To not tamper with the WIP limit we put it here

**Comment by lfrancke** [comment]
All done, thank you!
