### ISSUE TITLE
Epic: Better Readmes

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#273]
## Goal

Having templated READMEs for all operators which look closer to [this](https://github.com/datahub-project/datahub) or [this](https://github.com/CrunchyData/postgres-operator) would look way way better than the minimal READMEs we have [right](https://github.com/stackabletech/secret-operator) [now](https://github.com/stackabletech/druid-operator).

Every single README can be seen as a landing page, conveying quality and competency, and inviting the visitor into the stackable ecosystem. It would take a very manageable amount of effort to get our READMEs closer to the above examples, and do a significantly better job at representing our products.

Created from issue https://github.com/stackabletech/operator-templating/issues/152

## Next Steps

- All done

## Roadmap

We want to design two different readmes at first, and then find out which parts should be common to all operators (put into the templating), and which parts should be operator specific. 

- [x] https://github.com/stackabletech/kafka-operator/issues/480
- [x] https://github.com/stackabletech/secret-operator/issues/187

After we gathered our requirements, we want to design the templating system according to those requirements, and finally implement it and generate READMEs for all operators.

- [x] https://github.com/stackabletech/issues/issues/274
  - Implement templating making it possible to include pre-written blocks into operator READMEs
- [x] https://github.com/stackabletech/issues/issues/292

**Comment by vsupalov** [comment]
@maltesander @fhennig Now that the prototypes are in review, a sensible way forward would be to ask some people for their opinions to find out what we want to include for https://github.com/stackabletech/operator-templating/issues/152

In parallel, we could already get started on implementing an include-based system for https://github.com/stackabletech/issues/issues/274

--

For anybody reading this who wants to get up to speed:
* Felix captured some learnings in the PR to the [secret-operator prototype](https://github.com/stackabletech/kafka-operator/pull/483)
* There were some comments about the [kafka-operator prototype](https://github.com/stackabletech/kafka-operator/pull/483)

**Comment by fhennig** [comment]
stackablectl has a _very_ bare README, and I think we should improve it as part of this epic. There is also a ticket for it already: https://github.com/stackabletech/stackablectl/issues/85

**Comment by fhennig** [comment]
And probably we should also do something about this readme: https://github.com/stackabletech/operator-rs/

**Comment by vsupalov** [comment]
This epic can be concluded.

Here is an overview of possible next steps, or follow-up tasks:
* Giving other READMEs the same polish, as mentioned by Felix above
* Going in-depth with each operator, contributing detailed knowledge to their README where it makes sense
  * see Razvan's comments in https://github.com/stackabletech/kafka-operator/pull/489 for example

**Comment by lfrancke** [comment]
I have created a followup: https://github.com/stackabletech/issues/issues/297
