### ISSUE TITLE
Listener Operator first release

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#281]
These tasks are needed/useful for a first public release of the operator to make it useful and actually do something.
Further steps would be to roll it out across more operators I guess @nightkr 

TODO: This needs further refinement to check whether we really need all of this and whether they need to be done in any specific order

```[tasklist]
## Must have
- [ ] https://github.com/stackabletech/listener-operator/issues/20
- [ ] https://github.com/stackabletech/listener-operator/issues/2
- [ ] https://github.com/stackabletech/listener-operator/issues/3
- [ ] https://github.com/stackabletech/listener-operator/issues/71
- [ ] https://github.com/stackabletech/listener-operator/issues/70
- [ ] https://github.com/stackabletech/listener-operator/issues/72
- [ ] https://github.com/stackabletech/listener-operator/issues/95
- [ ] https://github.com/stackabletech/listener-operator/issues/96
- [ ] https://github.com/stackabletech/listener-operator/issues/110
- [ ] https://github.com/stackabletech/ci/pull/85
- [ ] https://github.com/stackabletech/documentation/issues/480
```

```[tasklist]
## Could have
- [ ] https://github.com/stackabletech/listener-operator/issues/4
- [ ] https://github.com/stackabletech/hdfs-operator/issues/235
```

```[tasklist]
## Platform rollout
- [ ] Airflow
- [ ] Druid
- [ ] HBase
- [ ] https://github.com/stackabletech/hdfs-operator/issues/174
- [ ] Hive
- [ ] https://github.com/stackabletech/kafka-operator/pull/443
- [ ] NiFi
- [ ] Spark
- [ ] Superset
- [ ] Trino
- [ ] ZooKeeper
```

```[tasklist]
### Documentation
- [ ] Update the _service exposition_ concept page: https://docs.stackable.tech/home/stable/concepts/service-exposition
```

**Comment by lfrancke** [comment]
We need to make sure that our platform is still usable for people who cannot run the listener operator (there are some unanswered questions about privileged mode using OLM deployment which we might be able to solve).

**Comment by soenkeliebau** [comment]
If they cannot run the listener they probably also cannot run the secret operator and at that point I think **** really hits the fan if we have to make do without it ..

**Comment by nightkr** [comment]
Ah, missed the discussion here. List-op is mandatory where it's used, but as @soenkeliebau mentioned secret-op has the same limitations (in fact, list-op should be *more* emenable to privilege dropping since we primarily need the privileges to harden access to secret material).

**Comment by nightkr** [comment]
The initial list-op release happened a while ago, closing this in favour of the separate rollout ticket #692.
