### ISSUE TITLE
Spike our Security Architecture

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#284]
## Introduction
We have extensively discussed our overall security architecture and even written about in on our [blog](https://stackable.tech/en/2022/07/27/the-stackable-security-story/).
To get started with the actual implementation I'd suggest a limited-scope spike to proof out the general principles. 
I'd suggest to pick HDFS for the initial spike because it'll be one of the more complex implementations and draw out issues early on. Once we succeeded with that we should expand the spike to a second (and maybe third) product and consider what we can pull out into the framework/utility operators/... .

## Scope
In order to reduce the amount of work for this initial spike we will make some simplifications:
- Manually deploy some supporting infrastructure like kdc
- Manually create and edit regorules, generating these from the operator can come at a later stage
- Running everything inside of k8s is totally fine, no need for services to be externally accessible at this stage

The following diagram show roughly what we intend to build for this spike, please refer to the _ToDo_ section for more specific subtasks of this epic.

![security_spike drawio](https://user-images.githubusercontent.com/1070361/194511796-ecaaf3ec-b7fb-41d2-bad2-2b3e8543a361.png)

# ToDo
- [ ] Patch Ranger HDFS authorizer to target an opa instead of Ranger server
- [ ] Build HDFS image containing the patched authorizer
- [ ] Deploy mit kdc (can be done manually for now)
- [ ] Change HDFS operator to allow enabling secure mode 
  - [ ] Enable Kerberos and integrate with KDC
  - [ ] Enable and configure patched authorizer
  - [ ] Deploy OPA sidecar containers
- [ ]  Create regorule objects to allow authorizing (or minimally just showing) requests
