### ISSUE TITLE
Log Aggregation

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#288]
## Goals
- a setup that can be easily spun up (single command) on any cluster running stackable  
- in an OpenSearch Dashboard  
	- see all operator logs  
	- see all product logs  
	- all logs have timestamp, log level and "THE REST"  
- all logs are exposed as stdout, but also as json & xml ("stackable log format")  
	- the customer can use anything they have, not only vector  
- outcome: central point to see what's going on in a stackable cluster  

## Un-goals (we will NOT do this here)  
- k8s events etc -> for next epic  

## Milestones  
- Done  
	- create spike vector setup  
	- decide on architecture  

### Task group A  
- [x] write down logging architecture in ADR  
  - https://github.com/stackabletech/issues/issues/259  

### Task group B  
- [x] one SINGLE operator, one single product, configured to write non-CRD json format into folder, stuff gets exported into vector and is visible in opensearch  
  - Revive Teo's vector spike, iterate, extract learnings for ADR: https://github.com/stackabletech/issues/issues/295
  - building on top of https://github.com/stackabletech/zookeeper-operator/pull/450
- [x] formulate ADR and CRD from those learnings  
  - https://github.com/stackabletech/issues/issues/261  
  - https://github.com/stackabletech/issues/issues/202
- [x] use CRD for one SINGLE operator, using operator framework  
  - edge cases figured out: vector agent rotates log files  
- [x] draw the rest of the fucking owl (ALL operators, ALL products, json logs in folders, vector sidecar agents, logging setup with dashboards)  

### Task group C  
- [x] stackablectl command to setup vector/opensearch/open search dashboard  
  - logging setup convenience  

## All tasks

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/opa-operator/issues/373
- [x] https://github.com/stackabletech/issues/issues/259
- [x] https://github.com/stackabletech/issues/issues/295
- [x] https://github.com/stackabletech/issues/issues/261
- [x] https://github.com/stackabletech/issues/issues/202
- [ ] https://github.com/stackabletech/zookeeper-operator/issues/633
```

```[tasklist]
### Products (Implementation)
- [x] https://github.com/stackabletech/hbase-operator/issues/291
- [x] https://github.com/stackabletech/zookeeper-operator/pull/588
- [ ] https://github.com/stackabletech/airflow-operator/issues/213
- [ ] https://github.com/stackabletech/druid-operator/issues/364
- [x] https://github.com/stackabletech/hdfs-operator/issues/288
- [x] https://github.com/stackabletech/hive-operator/issues/290
- [ ] https://github.com/stackabletech/kafka-operator/issues/544
- [ ] https://github.com/stackabletech/nifi-operator/pull/418
- [ ] https://github.com/stackabletech/spark-k8s-operator/issues/218
- [ ] https://github.com/stackabletech/opa-operator/issues/410
- [ ] https://github.com/stackabletech/superset-operator/issues/317
- [ ] https://github.com/stackabletech/trino-operator/issues/376
```

**Comment by vsupalov** [comment]
While refining the logging tickets of 202, we noticed that there was context missing, in form of a descriptive, focused epic ticket. The refinements of those tickets is effectively blocked.

Here is our draft of a logging epic which would provide enough information to be able to tackle the tickets currently in refinement:

**Comment by vsupalov** [comment]
- Goals  
		- a setup that can be easily spun up (single command) on any cluster running stackable  
		- in an open search dashboard  
			- see all operator logs  
			- see all product logs  
			- all logs have timestamp, log level and "THE REST"  
		- all logs are exposed as stdout, but also as json & xml ("stackable log format")  
			- the customer can use anything they have, not only vector  
		- outcome: central point to see what's going on in a stackable cluster  
	- Un-goals (we will NOT do this here)  
		- k8s events etc -> for next epic  
	- Milestones  
		- Done  
			- create spike vector setup  
			- decide on architecture  
		- Task group A  
			- write down logging architecture in ADR  
				- https://github.com/stackabletech/issues/issues/259  
		- Task group B  
			- one SINGLE operator, one single product, configured to write non-CRD json format into folder, stuff gets exported into vector and is visible in opensearch  
				- Revive Teo's vector spike, iterate, extract learnings for ADR  
			- formulate ADR and CRD from those learnings  
				- https://github.com/stackabletech/issues/issues/261  
			- use CRD for one SINGLE operator, using operator framework  
				- edge cases figured out: vector agent rotates log files  
			- draw the rest of the fucking owl (ALL operators, ALL products, json logs in folders, vector sidecar agents, logging setup with dashboards)  
		- Task group C  
			- stackablectl command to setup vector/opensearch/open search dashboard  
				- logging setup convenience

**Comment by maltesander** [comment]
all done!
