### ISSUE TITLE
OpenShift support

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#290]
This is the initiative tracking all of our OpenShift support

[Knowledge Base](https://app.nuclino.com/Stackable/Development/Atlasian-Docs-45d7b120-6d93-41c6-9b4d-2816c9362a24)

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/issues/issues/336
- [ ] https://github.com/stackabletech/issues/issues/234
- [x] Create and validate operator bundles as documented ~[here](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.58/html/red_hat_openshift_software_certification_policy_guide/assembly-products-managed-by-an-operator_openshift-sw-cert-policy-container-images#con-operator-requirements_openshift-sw-cert-policy-products-managed)~. Update: process is documented [here](https://app.nuclino.com/Stackable/Development/Operator-bundles-46f45f63-a887-4e92-8f65-31056f17f7ba) in Nuclino.
- [ ] Create a stackable base operator that can deploy the "fundamentals" (webhooks, commons, secret, listener, ...)
- [ ] https://github.com/stackabletech/issues/issues/337
- [ ] https://github.com/stackabletech/hdfs-operator/issues/327
- [ ] https://github.com/stackabletech/hbase-operator/issues/327
- [ ] https://github.com/stackabletech/airflow-operator/pull/251
- [x] Commons operator certification
- [x] Update Feature Tracker
```

**Comment by fhennig** [comment]
After a call with @razvan I wanted to write down my view on the issue.

- "Get it running" (with warnings etc.) and
- "Get it certified

are 2 different things, and the certification process seems rigorous, and it is likely that it cannot be done without human support from RedHat. It is useful to look at both aspects separately, but we should prioritize to get one Operator through the whole pipeline before spending a lot of time on technical things.

## Known technical issues

- Operators cannot be DaemonSets
- What about our CSI Drivers? The Secret Operator is a CSI Driver. However, we don't _actually_ provide storage.
  - Should they be certified as CSI Drivers regardless? What about the non-CSI Driver part of the Operator?
  - Can we certify an Operator that some also is a CSI Driver?

## Certification

- The certification pipeline that can be run manually seems to not run very stable
- What about requiring another Operator as a dependency? Do we need to provide all operators as a platform bundle?
- The process seems not doable with just reading the docs and doing it ourselves

I suggest to

- track the CSI question in a separate ticket. This seems to involve talking to RedHat. I wouldn't attempt to certify a CSI driver, as we're not actually providing storage.
- spike a secret operator that isn't a daemonset, and instead just deploys one
- Start talking to RedHat about getting the ZK Operator certified
- Track all of this in a seperate "Spike" epic

**Comment by adwk67** [comment]
@lfrancke  I'm not sure if we need this issue, or how we should maintain it going forward: we will have a ticket following each release ([here](https://github.com/stackabletech/issues/issues/376) is the one for 23.4), anyway.
