### ISSUE TITLE
Roll out README templating across all operators

### ISSUE THREAD

**Issue by vsupalov** [stackabletech/issues#292]
Apply the README templating method prototyped in https://github.com/stackabletech/issues/issues/274 to operator-templating and all operator repositories. (You can see the rendered example README [here](https://github.com/stackabletech/kafka-operator/tree/prototype-readme-templating))

The tasks are very similar, and will be tracked together in this issue, keeping detailed discussion to PRs within each operator.

## Goal

* Transition to the new style of README. Achieving high-polish content is not necessary.

## Tasks

- [x] https://github.com/stackabletech/operator-templating/pull/192
  - Add common templating files and scripts to operator-templating 

**Proceed in the PRs created by templating.**

Create 80/20-level operator-specific content across the following repositories, and commit a rendered README in each:

> PRs are named "Update templated files to rev f19219f" and the branches `template_f19219f`

- [Apache Airflow Operator](https://github.com/stackabletech/airflow-operator)
  - https://github.com/stackabletech/airflow-operator/pull/181
- [Apache Druid Operator](https://github.com/stackabletech/druid-operator)
  - https://github.com/stackabletech/druid-operator/pull/321
- [Apache HBase Operator](https://github.com/stackabletech/hbase-operator)
  - https://github.com/stackabletech/hbase-operator/pull/263
- [Apache Hadoop HDFS Operator](https://github.com/stackabletech/hdfs-operator)
  - https://github.com/stackabletech/hdfs-operator/pull/254
- [Apache Hive Operator](https://github.com/stackabletech/hive-operator)
  - https://github.com/stackabletech/hive-operator/pull/256
- [Apache Kafka Operator](https://github.com/stackabletech/kafka-operator)
  - https://github.com/stackabletech/kafka-operator/pull/496
- [Apache NiFi Operator](https://github.com/stackabletech/nifi-operator)
  - https://github.com/stackabletech/nifi-operator/pull/363
- [Apache Spark Operator](https://github.com/stackabletech/spark-k8s-operator)
  - https://github.com/stackabletech/spark-k8s-operator/pull/164
- [Apache Superset Operator](https://github.com/stackabletech/superset-operator)
  - https://github.com/stackabletech/superset-operator/pull/284
- [Trino Operator](https://github.com/stackabletech/trino-operator)
  - https://github.com/stackabletech/trino-operator/pull/312
- [Apache ZooKeeper Operator](https://github.com/stackabletech/zookeeper-operator)
  - https://github.com/stackabletech/zookeeper-operator/pull/572
- [Commons Operator](https://github.com/stackabletech/commons-operator)
  - https://github.com/stackabletech/commons-operator/pull/104
- [Listener Operator](https://github.com/stackabletech/listener-operator)
  - https://github.com/stackabletech/listener-operator/pull/23
- [OpenPolicyAgent Operator](https://github.com/stackabletech/opa-operator)
  - https://github.com/stackabletech/opa-operator/pull/361
- [Secret Operator](https://github.com/stackabletech/secret-operator)
  - https://github.com/stackabletech/secret-operator/pull/196

Cleanup tasks

- [x] Hide Jenkins job badge in operator repositories which don't have dedicated nightly tests
  - https://github.com/stackabletech/commons-operator/pull/105
  - https://github.com/stackabletech/listener-operator/pull/24
  - https://github.com/stackabletech/secret-operator/pull/197
- [x] https://github.com/stackabletech/operator-templating/pull/193
  - Fix badges being broken due to missing blank line
  - Debug readme diff checking action - it's supposed to fail on (uncommitted) differences
- [x] https://github.com/stackabletech/operator-templating/pull/194
  - Fix broken link by making it into a reusable part
- [x] https://github.com/stackabletech/operator-templating/pull/195
  - Fix badges broken by "this is a tiny change, it looks better and will surely work just as well"
- [x] Wait until above operator-templating changes have landed in all operators, integrate the new partial in all main files, render and check all READMEs
  - [x] [Apache Airflow Operator](https://github.com/stackabletech/airflow-operator)
  - [x] [Apache Druid Operator](https://github.com/stackabletech/druid-operator)
  - [x] [Apache HBase Operator](https://github.com/stackabletech/hbase-operator)
  - [x] [Apache Hadoop HDFS Operator](https://github.com/stackabletech/hdfs-operator)
  - [x] [Apache Hive Operator](https://github.com/stackabletech/hive-operator)
  - [x] [Apache Kafka Operator](https://github.com/stackabletech/kafka-operator)
  - [x] [Apache NiFi Operator](https://github.com/stackabletech/nifi-operator)
  - [x] [Apache Spark Operator](https://github.com/stackabletech/spark-k8s-operator)
  - [x] [Apache Superset Operator](https://github.com/stackabletech/superset-operator)
  - [x] [Trino Operator](https://github.com/stackabletech/trino-operator)
  - [x] [Apache ZooKeeper Operator](https://github.com/stackabletech/zookeeper-operator)
  - [x] [Commons Operator](https://github.com/stackabletech/commons-operator)
  - [x] [Listener Operator](https://github.com/stackabletech/listener-operator)
  - [x] [OpenPolicyAgent Operator](https://github.com/stackabletech/opa-operator)
  - [x] [Secret Operator](https://github.com/stackabletech/secret-operator)

## Acceptance Criteria

- [x] All features described in https://github.com/stackabletech/issues/issues/274 are functional through templating
  - github action hook
  - make sure to re-enable "integration testing" badge
  - makefile render command and scripts
  - files in `borrowed` folders are overwritten by operator-templating
- [x] All operator PRs have an own README.md.j2
- [x] All operator PRs are reviewed and merged
- [x] All operator repositories have a README.md rendered from those parts

**Comment by fhennig** [comment]
Review:

- The first link to the docs is broken (in the "link bar"). For i.e. airflow it links to "airflow-operator" but should link to "airflow". This affects most operators, except for "secret-operator" and the other internal ones, there the link has the "-operator" suffix and it is correct. It's a bit confusing that it is that way. Every docs module defines its name in the yml file: https://github.com/stackabletech/airflow-operator/blob/main/docs/antora.yml (so you know where this part of the URL comes from)

Other than that it looks very nice!!

**Comment by vsupalov** [comment]
Addressing this issue in https://github.com/stackabletech/operator-templating/pull/197

**Comment by vsupalov** [comment]
All changes are rendered, merged and checked.
