### ISSUE TITLE
Vector Logging Spike with sidecar & reading from files

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#295]
What happened so far: We made a spike (https://github.com/stackabletech/issues/issues/258) for vector logging in general. We decided on an architecture (https://github.com/stackabletech/issues/issues/259). Now we want to define a CRD in an ADR (https://github.com/stackabletech/issues/issues/261).

For this, we want to do another Spike, which is based on the decisions we made in #259, to base our ADR for #261 on. This new spike can be built on Teos old code: https://github.com/stackabletech/zookeeper-operator/pull/450

Previous spikes:
- https://github.com/stackabletech/issues/issues/258
- https://github.com/stackabletech/zookeeper-operator/pull/450

## Implementation status

The current status of the implementation can be seen in the [logging demo](https://github.com/stackabletech/stackablectl/blob/logging/docs/modules/ROOT/pages/demos/logging.adoc).

### Goal

The goal of this implementation is to have a production-ready logging solution for ZooKeeper and everything which is related to it. Every problem should be solvable by just having a look at the collected logs (Improving the logs so that this is actually possible, is out of scope. Also the Kubernetes events are out of scope). This implementation will be the template for the other operators, so it is worth doing it right. The decisions documented in the ADR go into the implementation but also the insights gained in the implementation flow back into the ADR. I planned to also gather the logs of the operator itself but this would require a lot of changes and new decisions, so I will postpone this and finish the log aggregation of the product first.

### Tasks

* [x] Allow custom configuration files
* [x] Analyze bug when levelThreshold for file is given but not for console.
* [x] Use a fragment also for the ZookeeperConfig.
* [x] Support log4j (currently only logback is supported which is used in ZooKeeper 3.8.0).
* [x] Adapt the ADR so that the logging of sidecar containers can be configured.
* [x] Collect the logs of all sidecar containers like the init container and the Vector agent itself.
* [x] Implement log level configuration.
* [x] Move common code to operator-rs.
* [x] Document logging in the concepts section of the top-level documentation. (assigned to @fhennig)
* [x] Improve the documentation of the demo.
* [x] Write an integration test.
* [x] Discuss how production-ready the logging stack in stackablectl should be. Currently the default configuration of the OpenSearch security plugin is used which is insecure.
* [x] Test hot-reloading of log configuration.
* [x] Test log file rollover.
* [x] Forward logs to the T2 Vector aggregator.
* [x] Add additional information to the log entries like namespace, cluster, group, and role group.
* [x] Analyze empty log entries in T2.
* [x] Document the calculation of the maximum log file size.

### Overview of the involved branches:

* https://github.com/stackabletech/docker-images/tree/logging (stackabletech/docker-images#268)
* https://github.com/stackabletech/operator-rs/tree/logging (stackabletech/operator-rs#517)
* https://github.com/stackabletech/zookeeper-operator/tree/logging (stackabletech/zookeeper-operator#588)
* https://github.com/stackabletech/stackablectl/tree/logging (stackabletech/stackablectl#187)
* https://github.com/stackabletech/documentation/tree/feature/logging-docs (stackabletech/documentation#326)

### Temporary Docker images

see https://repo.stackable.tech/#browse/browse:docker:v2%2Fsandbox%2Flogging

## Acceptance Criteria

* [x] Log plain text to stdout
* [x] Log structured entries (json/xml) to file (or using some other way directly to the sidecar Vector agent)
* [x] Vector agent as a sidecar
* [x] Read file with the vector agent sidecar
* [x] Deploy a vector aggregator
* [x] Deploy Opensearch
* [x] Forward log entries to vector aggregator
* [x] vector aggregator pushes entries to opensearch
    * [x] use secret operator for the certificate
* [x] Log level should be configurable per logger in the ZookeeperCluster Resource

**Comment by lfrancke** [comment]
I've updated one point above.
If there's an easy way to not write the log file then we could try that.

And to make sure I understand correctly: Logging structured entries might not be possible with log4j out of the box, and it will require a different mechanism for non log4j tools, right?

**Comment by fhennig** [comment]
Airflow: [Logging Configuration](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#logging) | [Logging & Monitoring Architecture](https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/logging-architecture.html)
Druid: uses log4j2. [Logging](https://druid.apache.org/docs/latest/configuration/logging.html)
Hbase: 2.4: [log4j](https://hbase.apache.org/2.4/book.html) | 3.0: [log4j2](https://hbase.apache.org/book.html#log4j)
HDFS: ???
Hive: ???
Kafka:
NiFi: uses logback. [Logging Configuration](https://nifi.apache.org/docs.html)
Spark:
Superset:
Trino:
ZooKeeper:
OPA:

### Frameworks:

#### log4j2:
[Supports XML, JSON and YAML output](https://logging.apache.org/log4j/2.x/manual/layouts.html), but not configurable.
Maybe with a custom `PatternLayout` implementation (might be overkill)?

**Comment by razvan** [comment]
Trino is using JDK's [java.util.logging](https://docs.oracle.com/en/java/javase/11/core/java-logging-overview.html) so we might have a chance to configure the output format to be xml. Here is an [example config file](https://github.com/trinodb/trino/blob/master/testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/tempto/logging.properties).

**Comment by fhennig** [comment]
@razvan Are you sure? I think this might just be the logging config for tempo, their logging framework.

**Comment by lfrancke** [comment]
@siegfriedweber This is still open. As far as I can see all boxes are ticked.
Would you consider this closed?

**Comment by siegfriedweber** [comment]
Yes, this is closed.
