### ISSUE TITLE
Put the getting_started scripts into a jenkins test and make them reliably green

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#308]
We have added the the getting started scripts a while ago and they are already conceptualized as tests. The return `0` if they worked, or any other return code if they failed. We would like to run them in Jenkins before every release, to save us time in the release process. Currently, the tests have to be run manually with is time consuming and error prone.

Testing should be possible for nightly as well as release branches

### Operators

In the operator, every test script should have a name conforming to `test_*.sh`. (i'd say the script cannot make any assumptions about where it is running)

### Jenkins

Most of the work will need to be done on the Jenkins side. Jenkins should:

- Look for all the `test_*.sh` scripts in the repo
- start a cluster for each one. No operators need to be installed
- run the script and capture the output

We would add another "Tab" in jenkins (like nightly, custom, etc.) for the docs tests.

## Steps

As usual, we'll

- [x] Make an OPA test branch with the `test_*.sh` scripts (done: [`spike/docs-testing`](https://github.com/stackabletech/opa-operator/tree/spike/docs-testing))
- [x] try it with OPA in Jenkins
- [x] if everything works, roll it out to all operators

## Acceptance criteria

- [x] Jenkins has a new tab for docs tests
- [x] the tab contains all operators as well as the main documentation itself
- [x] in each test a branch can be selected

## Tests working

- [x] ~~Main docs https://github.com/stackabletech/documentation/pull/367~~ :warning: Follow-Up: https://github.com/stackabletech/documentation/issues/378
- [x] Airflow https://github.com/stackabletech/airflow-operator/pull/249 :green_circle: 
- [x] Druid https://github.com/stackabletech/druid-operator/pull/412 :green_circle: 
- [x] Hbase https://github.com/stackabletech/hbase-operator/pull/328 :green_circle: 
- [x] HDFS https://github.com/stackabletech/hdfs-operator/pull/331 :green_circle: 
- [x] Hive https://github.com/stackabletech/hive-operator/pull/320 :exclamation: Not working yet: https://github.com/stackabletech/hive-operator/issues/329
- [x] Kafka https://github.com/stackabletech/kafka-operator/pull/561 :warning: (Outside connection currently not possible, see https://github.com/stackabletech/kafka-operator/issues/569) 
- [x] NiFi https://github.com/stackabletech/nifi-operator/pull/439 :warning: (connection problems in T2: https://github.com/stackabletech/nifi-operator/issues/442)
- [x] OPA https://github.com/stackabletech/opa-operator/pull/426 :green_circle: 
- [x] Spark https://github.com/stackabletech/spark-k8s-operator/pull/220 :green_circle: 
- [x] Superset https://github.com/stackabletech/superset-operator/pull/338 :green_circle: 
- [x] Trino https://github.com/stackabletech/trino-operator/pull/397 :green_circle: 
- [x] ZooKeeper https://github.com/stackabletech/zookeeper-operator/pull/655 :green_circle:  

Not all tests are working right now, but the basic infrastructure is in place. I made tickets for the tests that do not work:

## Follow-Up tickets

- https://github.com/stackabletech/nifi-operator/issues/442
- https://github.com/stackabletech/kafka-operator/issues/569
- https://github.com/stackabletech/documentation/issues/378
- https://github.com/stackabletech/hive-operator/issues/329

**Comment by fhennig** [comment]
notes
- we test with one repo first
- if everything goes well, we expand it into a custom test

also
- we only want to run it on demand
- there are no parameters in the tests

**Comment by fhennig** [comment]
The tests can be seen here: https://ci.stackable.tech/view/05%20Documentation%20Tests/

I'm working on enabling testing for all repos, as well as ensuring the tests work well in Jenkins.

- [ ] Main docs
- [ ] Airflow
- [ ] Druid
- [ ] Hbase
- [ ] HDFS
- [ ] Hive
- [ ] Kafka
- [ ] NiFi
- [ ] OPA
- [ ] Spark
- [ ] Superset
- [ ] Trino
- [ ] ZooKeeper

**Comment by fhennig** [comment]
Update: testing is enabled for all repos now, but the tests aren't reliably green yet, mostly due to timing issues

**Comment by fhennig** [comment]
Another update: I've been working on this as a filler every now and then. 

The switch from *-nightly to 0.0.0-dev has caused some issues for the tests, stackablectl 0.8.0 needs to go into Jenkins, That's something that Nikolaus will work on.

We also had some issues with the download times breaking the tests, but that should also be fixed now. I'm working/tracking this.

**Comment by backstreetkiwi** [comment]
Done
> The switch from *-nightly to 0.0.0-dev has caused some issues for the tests, stackablectl 0.8.0 needs to go into Jenkins, That's something that Nikolaus will work on.

**Comment by fhennig** [comment]
The tests all install -nightly instead of -dev, that needs to be fixed

**Comment by fhennig** [comment]
This PR needs to be tackled https://github.com/stackabletech/kafka-operator/pull/561

**Comment by fhennig** [comment]
Alright. The only two tests that are really difficult to fix are **NiFi** and the main **docs** test. They both don't use port-forwarding. NiFi can't use port-forwarding due to hostname checking. The main docs test for LDAP uses `stackablectl svc list` which is much more convenient than port forwards.

I'd tend to just excluding these two tests from the CI for now.

**Comment by fhennig** [comment]
Update for today:
- main docs might work on GKE, but I can't select GKE in Jenkis atm, I asked Nikolaus about it
- The `stackablectl` test of Hive passed now, but with Helm it doesn't work yet
- Kafka has a weird issue with a disconnecting port-forward
- NiFi can't connect via ExternalIP for some reason - needs debugging

The rest was reviewed (Thanks Malte) and merged!

**Comment by sbernauer** [comment]
Currently waiting for Nikolaus
