### ISSUE TITLE
Epic: Don't run init container as root and avoid chmod and chowning

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#312]
- [x] airflow: It's complicated. based on openshift compatible image, no chows or chmods BUT runAsUser 50000 and group 0. We will leave it as is for now
- [X] commons - No chmod, chown and security context
- [x] https://github.com/stackabletech/druid-operator/pull/353
- [x] https://github.com/stackabletech/hbase-operator/pull/283
- [x] https://github.com/stackabletech/hdfs-operator/pull/282
- [x] https://github.com/stackabletech/hive-operator/pull/277
- [x] https://github.com/stackabletech/kafka-operator/pull/524
- [x] listener - No chmod, chown and security context
- [x] https://github.com/stackabletech/nifi-operator/pull/390
- [x] https://github.com/stackabletech/opa-operator/pull/382
- [X] secret - No chmod, chown and security context
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/183
- [x] https://github.com/stackabletech/superset-operator/pull/300
- [x] https://github.com/stackabletech/trino-operator/pull/353
- [x] https://github.com/stackabletech/zookeeper-operator/pull/603 (reported in https://github.com/stackabletech/zookeeper-operator/issues/602)

## Install all nightly operators and run testsuites **on OpenShift**
This list only includes products that already run on Openshift before

**Comment by lfrancke** [comment]
All boxes are ticked. Is this done?

**Comment by sbernauer** [comment]
We could conduct some more tests on openshift, but other than it should be done. @maltesander what do you think?

**Comment by maltesander** [comment]
Yeah i think we should test this first on openshift.

**Comment by sbernauer** [comment]
Alright i will go throw the joy.... Added a list for that

**Comment by sbernauer** [comment]
Nice benefit is re-testing all our operators on openshift

**Comment by sbernauer** [comment]
All tests passed, can be closed from my point of view

**Comment by maltesander** [comment]
All done!
