### ISSUE TITLE
Enable logging in all operator integration tests depending on ZooKeeper

### ISSUE THREAD

**Issue by maltesander** [stackabletech/issues#317]
After the ZooKeeper logging spike was merged https://github.com/stackabletech/zookeeper-operator/pull/588, all operator integration tests depending on ZooKeeper will fail.

This is due to CRD changes in ZooKeeper. We could simply deactivate logging, but this means T2 will not pick up any logs.

Since there are other dependencies in the integration tests (HDFS, Hive, OPA) that require changes as soon as logging is enabled in the respective products, i see two options.

### Disable logging for now in the integration tests using ZooKeeper and wait for all other dependencies to support logging

This would be a quick fix for failing integration tests, and we would enable logging once all other product dependencies support logging.

### Adapt the dependent integration tests properly

This will offer us logs in T2 (at least for ZooKeeper) but will require changes as soon as another dependent product supports logging.

## Tasks

- [ ] Druid (ZooKeeper, HDFS, OPA)
- [ ] HDFS (ZooKeeper)
- [ ] HBase (ZooKeeper + HDFS)
- [ ] Kafka (ZooKeeper + OPA)
- [ ] NiFi (ZooKeeper)
- [ ] Trino (ZooKeeper, HDFS, Hive, OPA)

All products with only one dependency on ZooKeeper can be properly adapted (HDFS, NiFi).

**Comment by siegfriedweber** [comment]
The effort for the proper fix is negligible.

A ConfigMap must be created if the environment variable `VECTOR_AGGREGATOR` is set:
```yaml
{% if lookup('env', 'VECTOR_AGGREGATOR') %}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-aggregator-discovery
data:
  ADDRESS: {{ lookup('env', 'VECTOR_AGGREGATOR') }}
{% endif %}
```

In the ZooKeeper cluster, the `vectorAggregatorConfigMapName` and `enableVectorAgent` must be set depending on the environment variable:
```yaml
spec:
{% if lookup('env', 'VECTOR_AGGREGATOR') %}
  vectorAggregatorConfigMapName: vector-aggregator-discovery
{% endif %}
  <role>:
    config:
      logging:
        enableVectorAgent: {{ lookup('env', 'VECTOR_AGGREGATOR') | length > 0 }}
```
