### ISSUE TITLE
Make integration tests green

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#318]
# TODO

* Merge open ZooKeeper PRs with breaking changes:
  * https://github.com/stackabletech/zookeeper-operator/pull/612
* Update Postgresql Helm chart to 12.1.5
* Upgrade Redis Helm chart to 17.3.7
* Update tests with new CRD format for Zookeeper.
* Update tests based on the decision regarding logging
  * The decision: https://github.com/stackabletech/documentation/pull/330/files
    * Done _When implemented a new operator-rs must be released and new PR for the zookeeper-operator must be made._
  * Included in  https://github.com/stackabletech/issues/issues/317

# Acceptance 

Integration tests are green again.

### Kuttl tests with new Postgresql chart

- [x] Airflow: https://github.com/stackabletech/airflow-operator/pull/207
- [x] Druid: https://github.com/stackabletech/druid-operator/pull/363
- [x] HBase: n/a
- [x] Hadoop HDFS: https://github.com/stackabletech/hdfs-operator/pull/287
- [x] Hive: https://github.com/stackabletech/hive-operator/pull/284
- [x] Kafka
- [x] NiFi
- [x] OPA: n/a
- [x] Spark: n/a
- [x] Superset: https://github.com/stackabletech/superset-operator/pull/305
- [x] Trino: https://github.com/stackabletech/trino-operator/pull/359
- [x] ZooKeeper

**Comment by maltesander** [comment]
Im on HDFS -> HBase

**Comment by lfrancke** [comment]
You moved it to Done so I assume the tests are all green again and we can close this?

**Comment by maltesander** [comment]
Yes all custom tests ran successfully, so i would assume the nightlys once reactivated should work again!
