### ISSUE TITLE
Uber epic: Product monitoring

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#320]
More or less all our products already expose Prometheus metrics.
We only need to collect them and build Dashboards ontop. Alerting can be done using Prometheus alertmanager or Grafana alerts -> Followup, out of scope of this epic.

### Tasks
- [x] https://github.com/stackabletech/issues/issues/319
- [x] https://github.com/stackabletech/stackablectl/issues/193
- [ ] https://github.com/stackabletech/issues/issues/321
- [ ] https://github.com/stackabletech/issues/issues/81
- [ ] https://github.com/stackabletech/documentation/issues/331
- [ ] Find a way to ship dashboads to *only* paying customer
