### ISSUE TITLE
Deploy default and support custom affinities in our operators

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#323]
```[tasklist]
### Geneal Tasks
- [X] https://github.com/stackabletech/documentation/pull/362
- [x] POC for two products (kafka and hdfs) done
- [x] We still need to support the old nodeSelector mechanism
- [x] Old nodeSelector mechanism is deprecated, Warning in operator is thrown
- [x] Concepts page written (documentation)
```

```[tasklist]
### Products
- [X] https://github.com/stackabletech/operator-rs/pull/556
- [X] https://github.com/stackabletech/airflow-operator/pull/241
- [X] https://github.com/stackabletech/druid-operator/pull/406
- [X] https://github.com/stackabletech/hbase-operator/pull/322
- [x] https://github.com/stackabletech/hdfs-operator/pull/319
- [X] https://github.com/stackabletech/hive-operator/pull/315
- [x] https://github.com/stackabletech/kafka-operator/pull/557
- [X] https://github.com/stackabletech/nifi-operator/pull/436
- [X] opa-operator -> We always deploy a DaemonSet and don't see any large benefit of adding affinity as of now. Might change in the future, but requires custom logic (compared to the other operators)
- [X] https://github.com/stackabletech/spark-k8s-operator/pull/217
- [X] https://github.com/stackabletech/superset-operator/pull/337
- [X] https://github.com/stackabletech/trino-operator/pull/391
- [X] https://github.com/stackabletech/zookeeper-operator/pull/649

```

**Comment by soenkeliebau** [comment]
@nightkr @lfrancke and @soenkeliebau briefly discussed this yesterday and decided on a way forward.

The main discussion was whether it would be sufficient to allow overriding this as part of a generic safety-valve type of functionality where the user is allowed to specify pod_templates and the operator merges these into the pods it would create.

We decided that affinities are sufficiently common that we want to expose this as a fully supported functionality, instead of relying on overrides. Overrides will also be implemented, but under a separate [ticket](https://github.com/stackabletech/issues/issues/346).

To this effect we will look into adding Option<PodAffinitiy> and Option<PodAntiAffinity> to our structs.
These will need to be defineable at the role and rolegroup level.

If these are not defined the operators should add sensible default affinities, like the ones mentioned in the ticket. If these are defined they should override the default affinities. To suppress affinites completely these should be set to `null`.

**Comment by fhennig** [comment]
I didn't look into it much, but will be also be able to co-locate roles? I.e. for druid, the broker and router should ideally run on the same node ([see here](https://druid.apache.org/docs/latest/design/processes.html)).

Can we also define that I want my Superset to always run preferably run next to the Druid Broker? Maybe that's already a bit advanced, just some ideas :)

**Comment by razvan** [comment]
This looks like a good chance to introduce first class support for pod templates. These would be merged with templates generated by the operators.. Then, not only affinities can be customized.

**Comment by sbernauer** [comment]
That was my initial thought as well. After some discussion I was convinced that a "generic" podOverwrite will still need some time as well as development cost until ready and we need this feature rather quick.
Also affinity is "important enough" to not rely on podOverwrites - at least for our POs.
Happy to have a short call and convince you as well :)

**Comment by razvan** [comment]
I understand the complexity argument and I agree. Still, we could design the manifest structure now in such a way that doesn't require breaking changes in the future.
For example, instead of adding a `config.podAffinity` now and painfully change it later, add a  `config.podTemplate.affinity.nodeAffinity` and be forward compatible with the future. Also be more in line with what people already know.

**Comment by lfrancke** [comment]
All done! Thank you very much!
