### ISSUE TITLE
Get rid of static changelog files

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#330]
### Problem

**Update**: a prototype for a changelog generator has been implemented [here](https://github.com/stackabletech/release-summarizer).

Now that we switched the release model to use [trunk based development ](https://trunkbaseddevelopment.com/) maintaining a static CHANGELOG file in the "main" branch doesn't make much sense, and in the future it might not even be possible anymore.

For example, backporting changelogs from different release branches to main can lead to conflicts (or nonsensical entries) and is error prone as seen [here](https://github.com/stackabletech/issues/issues/329).

Other projects using the same release model generate release notes automatically from their issue trackers. For example, Apache Kafka has[ a script that scrapes Jira](https://github.com/apache/kafka/blob/3.4/release_notes.py) and generates the [changelog](https://downloads.apache.org/kafka/3.3.2/RELEASE_NOTES.html).

I propose to use the same approach for the Stackable Data Platform.

### Todo

Decide on the details:

- [ ]  what to put in the GH issues. Are[ conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) the way to go? There is already exisiting tooling ([example](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli))
- [ ] what labels to use: **Answer**: the labels to use for the changelog genration can be provided as command line arguments.
- [ ] how much content to put in the changelog. **Answer**: The content of the changelog can be customized with Jinja2 templates.
- [ ] what format to generate. **Answer**: The output format can be customized with Jinja2 templates.

**Comment by fhennig** [comment]
We'll not get rid of static changelog files, we'll maintain them manually. Exact process will come up at the next release.
