### ISSUE TITLE
post-release 23.1/pre-release 23.4

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#332]
These tasks should be addressed before Release 23.4

```[tasklist]
- [x] https://github.com/stackabletech/issues/issues/324
- [x] https://github.com/stackabletech/issues/issues/325
- [x] https://github.com/stackabletech/issues/issues/326
- [x] https://github.com/stackabletech/issues/issues/329 (will be closed if we go with 330 below). The decision was made to keep the changelog in main but update it manually 
- [x] https://github.com/stackabletech/issues/issues/330
- [x] Set up Jenkins to run all integration tests against (a branch and) a tag provided as parameters (this issue will be a post-23.4 release task)
- [x] #335
- [x] investigate using release candidates: what would change? (see #324. RCs already being used for product images). This is currently being done for product images, already used in some tests. For operators: can pass in a string such as 23.4-rc1 (will only be checked at regex level): i.e. nothing to change in the stackable-utils script
- [x] ~write a description of logging demos for the blog (low prio?)~
- [x] #339
- [x] Consider how to version product images (especially ngithly/pre-release versions). Decision made and will be presented at the arch meeting.
```

**Comment by fhennig** [comment]
I've pinned the Rust toolchain version in operator-rs now. We need to remember to bump it eventually.

I've come across [this](https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows): We could define the toolchain version once as a GitHub CI configuration variable, organization-wide. Then all Workflows could read from that. I think that could be very handy! Not sure what the scripting options are for the global variables.

**Comment by adwk67** [comment]
Closing this as #334 has been added as a post-release task to #333
