### ISSUE TITLE
Release 23.4

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#333]
# Stackable Release 23.4

### General pre-requisites (before feature freeze)

- [x] Run renovate manually (done at the beginning of this dev cycle: have added it to the post-release tasks below)
- [x] Check/bump ubi8 base image (it should be possible to do this by merging the latest Renovate PR mentioning ubi8). This was not done this dev cycle. Added to the post-release tasks below.
- [x] Check/bump java base image (it should be possible to do this by merging the latest Renovate PR mentioning ubi8): solved see [326](https://github.com/stackabletech/issues/issues/326) and [321](https://github.com/stackabletech/docker-images/pull/321)
- [x] Check/bump the vector base image: solved see [326](https://github.com/stackabletech/issues/issues/326) and [321](https://github.com/stackabletech/docker-images/pull/321)
- [x] Check/bump the stackable base image: : solved see [326](https://github.com/stackabletech/issues/issues/326) and [321](https://github.com/stackabletech/docker-images/pull/321)
- [x] Will be done post-release (see below). ~Bump Rust version. This can be done [in this file](https://github.com/stackabletech/operator-templating/blob/main/repositories.yaml) by changing `rust_version` and also for the ubi base iamge [here](https://github.com/stackabletech/docker-images/blob/main/ubi8-rust-builder/Dockerfile#L25). Please be aware that this action will change it for all repositories at the same time (when merging the templating PRs).~
- [x] Define product versions to include in the next release. See https://github.com/stackabletech/issues/issues/375
- [x] Bump operator-rs to latest version in all operators. This should be done early in the release cycle to leave sufficient time for testing etc (*done* - bumped to 0.39.0 - in the context of status/cluster-operation changes)
- [x] Run getting-started scripts if they have not yet been incorporated into integration tests

### Other release-specific pre-requisites
- [x] see https://github.com/stackabletech/issues/issues/332

### Feature freeze

This will not be so crucial with release branches, but is nonetheless sensible as it will make it easier to cherry-pick any release-related bugfixes from main into the release branch.

#### Technical tasks
- [x] Create release branches for docker-images and operators (see stackable-utils for script to create branches)
- [x] update changelogs (manually or incorporated into release scripts: decide this while releasing) in main branches by adding the release version under the `Changelog` tag
- [x] Create release tag(s) for docker-images and operators (see stackable-utils for scripts to create tags)
- [x] Check integration tests
- [x] Check getting started scripts (optional, as may be covered by integration tests)
- [x] Check new stackablectl Stacks and Demos
  - [x] test with locally updated (to new release number) `releases.yaml`
- [x] Inspect stackablectl release upgrade with deployed products (does everything still spin up?) 
  - N.B. no - this won't work for breaking changes with CRD changes 
- [x] update `release.yaml` in https://github.com/stackabletech/release/blob/main/releases.yaml: https://github.com/stackabletech/release/pull/22

#### Documentation tasks
- [x] Check the Changelog and/or issue labels to compile Release Highlights
- [x] Write an upgrade guide: https://github.com/stackabletech/documentation/pull/381
  - [x] Document how to use stackablectl to uninstall all and install new release
  - [x] Document how to use helm to uninstall all and install new release
  - [x] Every breaking change of all our operators
  - [x] List dropped supported product versions (if there are some)
  - [x] List dropped supported operators (if there are some)
  - [x] List supported k8s versions
- [x] Sync supported k8s versions in the READMEs with what is in the release notes (and apply templating): https://github.com/stackabletech/operator-templating/pull/246
- [x] Update version of main documentation repo

Marketing tasks can now reference published documentation.

#### Marketing tasks
- [x] Write marketing / customer oriented release summary to be published in the marketing channels
- [x] Update the homepage banner (as long as we have it) to point to the new release
- [x] Write a blogpost / news article announcing the new release (optional)
- [x] ~Write a description of new demos for hmepage/demos section~ (included in release notes)
- [ ] Announce Release on linkedIn
- [ ] Announce Release on Twitter (optional)
- [x] Announce Release in Newsletter (optional)
- [ ] Announce Release on Hacker News (optional)?
- [ ] Inform Kubernetes Podcast about Release (optional)
- [ ] Produce a release highlight video (optional)
- [x] Post an announcement in the GitHub [Discussions Announcement forum](https://github.com/stackabletech/community/discussions/categories/announcements)

#### stackablectl

Actions:
* Test new stacks

| stackablectl stack | status |
| :--- | :--- |
| all | :heavy_check_mark:  |
(extend as necessary)

* Test new demos

| stackablectl demo | status |
| :--- | :--- |
| all | :heavy_check_mark:  |
(extend as necessary)

#### Operators

| Operator  | Integration tests | Getting started scripts |
| :--- | :---: | :--- |
| Airflow   |    :green_circle:     | tested locally :green_circle: |
| Commons   |     N/A    | N/A |
| Druid     |   :green_circle:      | tested locally & [CI Test](https://ci.stackable.tech/view/05%20Documentation%20Tests/job/druid-operator-documentation-test/12/) :green_circle: |
| HBase     |  :green_circle:  | tested locally & [CI Test](https://ci.stackable.tech/view/05%20Documentation%20Tests/job/hbase-operator-documentation-test/7/) :green_circle:     |                     |
| HDFS      |    :green_circle:     | tested locally :green_circle: |
| Hive      |     :green_circle:    | tested locally :green_circle: |
| Kafka     |    :green_circle:     | tested locally :green_circle: |
| Listener  |   :green_circle:      | N/A |
| NiFi      |    :green_circle:     | tested locally :green_circle: |
| OPA       |    :green_circle:     | [CI test :green_circle: ](https://ci.stackable.tech/view/05%20Documentation%20Tests/job/opa-operator-documentation-test/15/) |
| Secret    |    N/A     | N/A |
| Spark     |    :green_circle:     | [CI Test :green_circle:](https://ci.stackable.tech/view/05%20Documentation%20Tests/job/spark-k8s-operator-documentation-test/4/) |
| Superset  |   :green_circle:      | tested locally :green_circle:|
| Trino     |   :green_circle:      | [CI Test :green_circle::green_circle:](https://ci.stackable.tech/view/05%20Documentation%20Tests/job/trino-operator-documentation-test/7/) |
| ZooKeeper |     :green_circle:    | [CI Test :green_circle::green_circle:](https://ci.stackable.tech/view/05%20Documentation%20Tests/job/zookeeper-operator-documentation-test/6/) |

### Post-release tasks
- [x] Moving this to the next release as a pre-release task ~https://github.com/stackabletech/issues/issues/334~
- [x] Bump Rust version. This can be done [in this file](https://github.com/stackabletech/operator-templating/blob/main/repositories.yaml) by changing `rust_version` and also for the ubi base iamge [here](https://github.com/stackabletech/docker-images/blob/main/ubi8-rust-builder/Dockerfile#L25). Please be aware that this action will change it for all repositories at the same time (when merging the templating PRs).
  - https://github.com/stackabletech/docker-images/pull/357
  - stackabletech/operator-templating#246
- [x] Run renovate manually
- [x] Check/bump ubi8 base image: https://github.com/stackabletech/docker-images/pull/357
- [x] create issue for release-specific openshift certification: https://github.com/stackabletech/issues/issues/376
- [x] Update to kube-rs 0.82.1: https://github.com/stackabletech/operator-rs/issues/588
