### ISSUE TITLE
Apache ZooKeeper Operator and dependencies certification

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#337]
# Description

Certify the Zookeeper operator and it's dependencies.

NOTE: **product images** prior to 23.4.x cannot be certified because of a missing label that is required.

* [Container certification project](https://connect.redhat.com/projects/62552b0aadd9d54d56cda11d/overview)
* [Operator certification project](https://connect.redhat.com/projects/62552c9ae85eb954f055f3c8/overview) (incomplete)

```[tasklist]
### Tasks
- [x] generate script bundle/catalog for operator version `23.4.0-rc1` (e.g.`make regenerate-opm`)
  - [x] PR: https://github.com/stackabletech/zookeeper-operator/pull/645
  - [x] PR: https://github.com/stackabletech/commons-operator/pull/149 
- [x] deploy scripts for catalog and packaging operators (stackable-utils)
- [x] PR: https://github.com/stackabletech/stackable-utils/pull/39
- [x] pre-certify image zookeeper: `3.8.0-stackable23.4.0-rc2`, `3.7.0-stackable23.4.0-rc2`, `3.6.3-stackable23.4.0-rc2`, `3.5.8-stackable23.4.0-rc2`
- [x] publish zookeeper product image
- [x] pre-certify image: zookeeper-operator: `23.1.0`
- [x] pre-certify image: commons-operator: `23.1.0`
- [x] (once per cluster) install the "Operator Certification Operator" from OperatorHub using the cluster console
- [x] [follow the instructions](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/operator-cert-workflow.md) on setting up the certification pipeline,
- [x] finalise PR process from our fork 
- [ ] certify image: commons-operator (23.4.0) (will be done with release 23.4.0)
- [ ] certify image: secret-operator (23.4.0) (will be done with release 23.4.0)
- [x] certify operator bundle: commons-operator
- [x] certify operator bundle: secret-operator
- [x] certify operator bundle zookeeper-operator
- [x] finalize the operator certification project. questions: what authorized GH account?
```

# Notes

[Step 6](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/4.9/ga/ci-pipeline.md) fails with:

```
➜  operator-pipelines git:(main) oc apply -R -f ansible/roles/operator-pipeline/templates/openshift/pipelines
pipeline.tekton.dev/operator-ci-pipeline created
pipeline.tekton.dev/operator-hosted-pipeline created
Error from server (BadRequest): error when creating "ansible/roles/operator-pipeline/templates/openshift/pipelines/community-signing-pipeline.yml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: must not set the field(s): spec.tasks[0].taskref.bundle, spec.tasks[2].taskref.bundle, spec.tasks[3].taskref.bundle
Error from server (BadRequest): error when creating "ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-release-pipeline.yml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: must not set the field(s): spec.tasks[19].taskref.bundle, spec.tasks[20].taskref.bundle
```

## Container requirements

To verify container images and publish results you need to install preflight and run it for every container (including the operator)
```
preflight check container docker.stackable.tech/stackable/zookeeper:<version> --certification-project-id=ospid-62552b0aadd9d54d56cda11d --pyxis-api-token=<token> --submit
```
Where:
* `version` is the image version you want to check
* `token` RedHat account token of the user running the command

**Comment by adwk67** [comment]
Usuing the updated documentation [here](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.56/html/red_hat_software_certification_workflow_guide/assembly-running-the-certification-suite-locally_openshift-sw-cert-workflow-complete-pre-certification-checklist):

Create template file to be accessed from where the pipeline will be started:

```
mkdir templates
cd templates

cat <<EOF> workspace-template.yml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
EOF
cd ..
```

Call `tkn`:

export GIT_REPO_URL=https://github.com/stackabletech/openshift-certified-operators
export BUNDLE_PATH=operators/stackable-zookeeper-operator/23.1.0

```
tkn pipeline start operator-ci-pipeline \
  --namespace stackable-operators \
  --param git_repo_url=$GIT_REPO_URL \
  --param git_branch=main \
  --param bundle_path=$BUNDLE_PATH \
  --param env=prod \
  --workspace name=pipeline,volumeClaimTemplateFile=templates/workspace-template.yml \
  --showlog
```

**Comment by adwk67** [comment]
Further progress on this issue is blocked until we decide what to do with the secret operator.

**Comment by adwk67** [comment]
The only things currently blocking are the certification of the commons and secret operator images: however this will only be possible when 23.4.0 is released (0.0.0-dev builds without certification errors, but we don't want to certify that).

**Comment by adwk67** [comment]
Closing this as the remaining operator images will be pushed/certified when release 23.4.0 is done (along with other certified operators: secret, commons, hdfs, zookeeper, ...)

**Comment by adwk67** [comment]
Closing this as the remaining operator images will be pushed/certified when release 23.4.0 is done (along with other certified operators: secret, commons, hdfs, zookeeper, ...)
