### ISSUE TITLE
Ensure operators update the Status field of managed CRs

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#343]
# Description

**Update**: ADR has been written here: https://github.com/stackabletech/documentation/pull/366

One [requirement](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.56/html/red_hat_openshift_software_certification_policy_guide/assembly-products-managed-by-an-operator_openshift-sw-cert-policy-container-images#con-operator-requirements_openshift-sw-cert-policy-products-managed) for OpenShift operators is that:

> The Operator must update the status field of each Custom Resource (CR). | To ensure that users can determine the running state of the CR and identify potential failures.

### Implementation
- [x] operator-rs: https://github.com/stackabletech/operator-rs/pull/571
- [x] https://github.com/stackabletech/airflow-operator/pull/255
- [x] commons-operator -> left out for now
- [x] https://github.com/stackabletech/druid-operator/pull/421
- [x] https://github.com/stackabletech/hbase-operator/pull/337 
- [x] https://github.com/stackabletech/hdfs-operator/pull/339
- [x] https://github.com/stackabletech/hive-operator/pull/326
- [x] https://github.com/stackabletech/kafka-operator/pull/575 
- [x] listener-operator -> left out for now
- [x] https://github.com/stackabletech/nifi-operator/pull/448
- [x] https://github.com/stackabletech/opa-operator/pull/428
- [x] secret-operator -> left out for now
- [x] spark-k8s-operator -> already uses status
- [x] https://github.com/stackabletech/superset-operator/pull/349
- [x] https://github.com/stackabletech/trino-operator/pull/403
- [x] https://github.com/stackabletech/zookeeper-operator/pull/658
- [x] https://github.com/stackabletech/opa-operator/pull/428

Current situation (02.02.2023) shows that not all operators do this (most notably `hdfs`):

```
➜  stackable rg  status -g lib.rs
superset-operator/rust/crd/src/lib.rs
124:    status = "SupersetClusterStatus",

druid-operator/rust/crd/src/lib.rs
133:    status = "DruidClusterStatus",

spark-k8s-operator/rust/crd/src/lib.rs
121:    status = "SparkApplicationStatus",

airflow-operator/rust/crd/src/lib.rs
97:    status = "AirflowClusterStatus",

hive-operator/rust/crd/src/lib.rs
64:    status = "HiveClusterStatus",

zookeeper-operator/rust/crd/src/lib.rs
79:    status = "ZookeeperClusterStatus",

trino-operator/rust/crd/src/lib.rs
164:#[kube(status = "TrinoClusterStatus")]

hbase-operator/rust/crd/src/lib.rs
71:    status = "HbaseClusterStatus",

nifi-operator/rust/crd/src/lib.rs
57:    status = "NifiStatus",
```

**Comment by fhennig** [comment]
I had a look at the SupersetclusterStatus as a sample, and it is empty. I don't think an empty status will be sufficient for Openshift, all the empty structs need to have something in them to

> ... ensure that users can determine the running state of the CR and identify potential failures.

We need to gather all the states from all rolegroups etc and come up with status fields to communicate the status of the product as a whole. At the very minimum I suppose we need Doploying/Ready/Stopped or something.

**Comment by fhennig** [comment]
Which statuses should be there? The RedHat docs state that the user should be able to determine whether a resource is running and whether there were any failures. 

At the very least we need a boolean ready/not ready.

Even better might be an enum like:

- waiting/deploying
- running
- stopped
- failed

what about "degraded?" (maybe i.e. Zookeeper with one node crashed)

Which state means what is up to the operator.


Probably an implemenation could look like this:
- we define watches on the statefulsets
- we match statefulsets to ProductClusters and trigger reconcile for the relevant Cluster
- in the reconcile, fetch statuses from all statefulsets and calculate and overall cluster status and set it

**Comment by razvan** [comment]
OpenShift defines the following types for operator conditions  [1]:
* Available
* Progressing
* Degraded
* Upgradable

[1] https://github.com/openshift/api/blob/b1bcdbc3/config/v1/types_cluster_operator.go#L123-L140

**Comment by razvan** [comment]
ADR started at : https://github.com/stackabletech/documentation/pull/366/

**Comment by lfrancke** [comment]
This is an epic, correct?
If so, I'll move it to the other board.
Razvan, can I make you the epic owner for this one?

**Comment by razvan** [comment]
Yes it's an epic. I'm already assigned or is "owner" different than "assignees"?

**Comment by maltesander** [comment]
All done!
