### ISSUE TITLE
Supply Chain Security Epic

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#345]
We'd like to take on various projects to strengthen our security posture and make our (and our customer's) supply chain secure.

There are some related tasks in here that are not strictly about security

```[tasklist]
- [ ] Signing images
- [ ] Signing Helm charts
- [ ] Publishing Helm charts in an OCI compatible repository
- [ ] Scan our artifacts against security vulnerabilities at build time and regularly thereafter
- [ ] Update our base images regularly and rebuild product images
- [ ] Provide SBOMs for our Docker images, our compiled artifacts and our products
- [ ] Publish signature hashes for releases on our homepage/in the release notes
- [ ] Evaluate signed commits
- [ ] Evaluate how/if we can get notified on changes to the git history
- [ ] Evaluate whether we want to rename docker.stackable.tech to hub.stackable.tech or similar
- [ ] Look at CIS benchmark
- [ ] Look at https://securityscorecards.dev/
- [ ] Look at https://slsa.dev/

See also https://app.nuclino.com/Stackable/Stackable/Supply-Chain-Security-ce7f8653-fc4b-4b8f-934f-d1ba6772e308 (internal only)

**Comment by soenkeliebau** [comment]
Meeting on friday (29.9.2023) about the current state of implementation, afterwards we'll probably have a bit more clarity on this and can refine it further.

**Comment by fhennig** [comment]
I found this ticket which I think should be linked here: https://github.com/stackabletech/docker-images/issues/44 (or maybe just close it, linking to a different one)
