### ISSUE TITLE
Add functionality to merge user specified pod overrides into the pods created by operators to allow generic "last-resort" overrides

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#346]
Our operators support specifying config overrides that allow putting custom settings into the product config that the operator rolls out.
This is quite often useful to influence behavior which is not directly exposed or supported by the operators.

However, this does not work at the kubernetes level, any customizations needed on the objects that are created by the operators would immediately be reverted by the operator.
So allow adding custom settings here we should allow specifying a pod template (service, stateteful set, ...) on roles or rolegroups, which the operator could then merge with the objects it would write, before actually applying them.

To a certain extent this is dependent on https://github.com/Arnavion/k8s-openapi/issues/128 as we need the merge functionality discussed in that ticket to be implemented for this to work properly

```[tasklist]
- [ ] https://github.com/stackabletech/operator-rs/pull/601
- [ ] https://github.com/stackabletech/documentation/pull/415
- [ ] https://github.com/stackabletech/documentation/pull/416
- [ ] https://github.com/stackabletech/airflow-operator/pull/295
- [ ] https://github.com/stackabletech/druid-operator/pull/450
- [ ] https://github.com/stackabletech/hbase-operator/pull/371
- [ ] https://github.com/stackabletech/hdfs-operator/pull/368
- [ ] https://github.com/stackabletech/kafka-operator/pull/602
- [ ] https://github.com/stackabletech/superset-operator/pull/377
- [ ] https://github.com/stackabletech/trino-operator/pull/440
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/698
- [ ] https://github.com/stackabletech/hive-operator/pull/352
- [ ] https://github.com/stackabletech/nifi-operator/pull/483
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/256
- [ ] https://github.com/stackabletech/opa-operator/pull/458
- [x] edc - We will handle podOverrides in a larger refactoring later on
- [ ] https://github.com/stackabletech/hello-world-operator/pull/15
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/702
- [ ] https://github.com/stackabletech/hbase-operator/pull/373
```

**Comment by lfrancke** [comment]
See also https://github.com/stackabletech/issues/issues/344
