### ISSUE TITLE
Develop crate2nix based CI pipeline for operators

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#349]
# TODO

- [ ] Implement crate2nix pipeline
- [ ] used for PRs
- [ ] makes use of remote caching.
