### ISSUE TITLE
Initial Kerberos support

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#352]
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/secret-operator/issues/4
- [ ] https://github.com/stackabletech/hdfs-operator/issues/178
- [ ] https://github.com/stackabletech/secret-operator/issues/253
- [ ] https://github.com/stackabletech/hbase-operator/issues/285
- [ ] https://github.com/stackabletech/hive-operator/issues/387
```

**Comment by nightkr** [comment]
I'm taking https://github.com/stackabletech/documentation/issues/251 out of this issue for now, it's not really any more vital for Krb that it is for TLS.

**Comment by sbernauer** [comment]
Now HDFS, HBase and HMS can be secured using Kerberos :partying_face: 

What was **not** handled in this Issue is the whole discovery (the discovery should include that Kerberos should be used for authentication etc.), as well as clients such as Trino, Nifi or Spark connecting to kerberized stacklets.
