### ISSUE TITLE
Graceful shutdown support

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#357]
As  a user, I want to minimize disruptions of my deployed products.
There are important items listed in https://docs.stackable.tech/home/nightly/concepts/operations/#_service_availability, but for one very important we are missing the actual implementation in all operators but trino: Graceful shutdown

We should check all our products on whether there is anything we can do to shutdown gracefully once a Pod has been scheduled for deletion.
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/343
- [ ] https://github.com/stackabletech/druid-operator/pull/486
- [ ] https://github.com/stackabletech/hbase-operator/issues/400
- [ ] https://github.com/stackabletech/hdfs-operator/pull/407
- [ ] https://github.com/stackabletech/hive-operator/pull/385
- [ ] https://github.com/stackabletech/kafka-operator/pull/635
- [ ] https://github.com/stackabletech/nifi-operator/pull/528
- [ ] https://github.com/stackabletech/opa-operator/pull/487
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/306
- [ ] https://github.com/stackabletech/superset-operator/pull/422
- [ ] https://github.com/stackabletech/trino-operator/pull/486
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/740
- [ ] https://github.com/stackabletech/hello-world-operator/pull/33
- [ ] https://github.com/stackabletech/operator-rs/pull/681
- [ ] https://github.com/stackabletech/hdfs-operator/pull/418
- [ ] https://github.com/stackabletech/hbase-operator/pull/410
```

```[tasklist]
### Tasks
- [x] Approve CRD changes
- [ ] https://github.com/stackabletech/operator-rs/pull/668
- [ ] https://github.com/stackabletech/documentation/pull/468
- [ ] https://github.com/stackabletech/operator-rs/pull/672
```

**Comment by soenkeliebau** [comment]
We'll put this on the board to do some research into it.

HBase and HDFS are the main two products we want this for, after those are done we'll revisit and see if we go on with the epic or put it back into the backlog again.
