### ISSUE TITLE
Disabled Java DNS Caching leads to performance issues

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#359]
In the past we disabled Java DNS caching (https://github.com/stackabletech/docker-images/pull/126) due to issues with HBase & ZooKeeper.

During benchmarking of HBase it turns out that this leads to a heavy negative performance impact as there seem to be DNS lookups at every request (maybe more than one) which makes it unsustainable to keep the DNS caching disabled.

Enabling it _might_ lead to other failures (@nightkr can you remember details?) though so we have to be careful and need to find a solution that works in all scenarios.

This is an epic that contains research, potential fixes in all (Java based) operators and validation that the fix works and causes no negative side effects.

```[tasklist]
### Tasks
- [x] Document how the JVM does DNS caching: https://app.nuclino.com/Stackable/Knowledge-Base/DNS-caching-b9e947b4-717a-4257-8903-23cb4af6d4f2
- [ ] https://github.com/stackabletech/docker-images/pull/433
- [ ] https://github.com/stackabletech/issues/issues/412
- [x] Implement Java DNS fields for Java based products.
- [x] Optional: use Chaos Mesh to simulate DNS failures and implement test suite for it.
```

**Comment by razvan** [comment]
## Scenario 1
* set both ttl versions to small numbers and test.
## Scenario 2
* Gather list of product versions where DNS problems are supposedly fixed. Compare with supported product versions.
* Test versions that are supposedly fixed: kill a node, bring up a new node, ....

**Comment by razvan** [comment]
I started a Nuclino page information related to the Java DNS caching: https://app.nuclino.com/Stackable/Knowledge-Base/DNS-caching-b9e947b4-717a-4257-8903-23cb4af6d4f2

**Comment by lfrancke** [comment]
The Nuclino page is excellent!

I'm afraid I need a summary.
What did change in this issue?
We changed the CRDs of all Java operators to be able to override Java security properties?
And what did we set the values to?

Is there an example CRD snippet somewhere?

**Comment by razvan** [comment]
In this issue we:
* removed the hard coded dns settings from the base java image.
* added the possibility to configure these per product (even role group) via config overrides
* documented how to do it for each product ([example](https://docs.stackable.tech/home/nightly/zookeeper/usage_guide/configuration_environment_overrides#_overriding_entries_in_security_properties)) and what the defaults are.

**Comment by razvan** [comment]
Usually the defaults are the same as the JVM defaults except for Zookeeper where the positive cache has a TTL of only 5 secs.

**Comment by lfrancke** [comment]
Thank you!
