### ISSUE TITLE
Foundation work for admission controllers

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#361]
We need to be able to offer webhooks in Kubernetes for some future functionalities, like CRD versioning and other use cases.

While fairly simple in principle, there is quite a bit of groundwork that we need to do to enable this and make it usable for a lot of people.

N.B. This epic covers the foundation work *only*: a separate epic covers the actual [CRD versioning](https://github.com/stackabletech/issues/issues/507)

## Step 1: Research

```[tasklist]
## Tasks
- [ ] https://github.com/stackabletech/documentation/pull/522
- [ ] https://github.com/stackabletech/documentation/pull/524
- [x] Spike: basic conversion example: https://github.com/stackabletech/airflow-operator/compare/main...spike/patching
- [x] Spike: create multi-version CRD in code: https://github.com/stackabletech/airflow-operator/compare/main...spike/patching
- [x] Spike webhook configuration for OLM using the secret op: https://github.com/stackabletech/openshift-certified-operators/pull/17
```

Expected research results

- We know how we want to deploy the webhooks
- We know how to deploy the CA bundles

## Step 2: Groundwork implementation

```[tasklist]
## Tasks: Framework changes
- [ ] https://github.com/stackabletech/operator-rs/pull/730
- [ ] https://github.com/stackabletech/operator-rs/pull/736
- [x] Implement ADR 34 (deployment): The webhook is a deployment via Helm
- [ ] https://github.com/stackabletech/issues/issues/540
```

## Acceptance criteria

- It is clear how the k8s API server trusts the webhooks, and it is clear how the required CA is managed
- There is a library/framework that makes it easy to write webhooks in the operators

## Follow up / Improvements

```[tasklist]
## Tasks
- [ ] https://github.com/stackabletech/operator-rs/issues/744
- [ ] https://github.com/stackabletech/operator-rs/issues/745
- [ ] https://github.com/stackabletech/issues/issues/507
```

----

<details>
<summary>OLD NOTES for reference</summary>

### Tasks
- Research: How to convert versions. Step by step (e.g. v1->v2, v2->v3) or full (v1->v3). In code via traits or webhook chaining?
- Add web service code to operator-rs so that operators can easily spin up endpoints
- Research: How to deploy webhooks (Deployment by operator, Deployment by external, Deployment as operator "controller" / endpoint)
- Research: How much control does an operator need/have over the “mutate” web server endpoint
- Spike two operators with the operator-rs base and add abstraction where possible

## CRD Versioning

> See https://github.com/stackabletech/documentation/issues/273

### Tasks
- Research: How to add multiple CRD versions in one CRD via kube/schemars -> https://docs.rs/kube/latest/kube/derive.CustomResource.html#versioning
- Adapt operator CRD crate structure in operators. Keep all structs from each CRD cycle / version in the operators e.g. ZookeeperClusterV1Alpha1 or ZookeeperClusterV1 in their own folder/crate for deserialization in the webhook
- https://github.com/stackabletech/issues/issues/482
- Research: Our CRDs are already very big, how do we handle multiple versions (which basically double or triple the size) in terms of space requirements?
- Research: Enable YAML anchors and aliases to reduce CRD size

## Other Use-Cases for Validating/Mutating Webhooks

- https://github.com/stackabletech/commons-operator/issues/111

## CA

Webhooks need to enable TLS and thus have a valid certificate that is signed by a known ca in the cluster.
These CAs then need to be configured via so called caBundles for the service endpoints. See https://github.com/stackabletech/documentation/pull/522.

### Tasks
- Contributor / Developer guide on how to maintain the webhooks if additional versions are added
- Any user docs required? This is more a black box that "just" works.
</details>
