### ISSUE TITLE
Signing images & publishing signatures

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#370]
I want all our images to be signed and those signatures made available so our customers can validate their authenticity.

How: 
- We want signatures to be compatible with OpenShift https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/building_running_and_managing_containers/assembly_signing-container-images_building-running-and-managing-containers & https://developers.redhat.com/blog/2019/10/29/verifying-signatures-of-red-hat-container-images#
- Need to investigate if we can also distribute signatures via an OCI registry itself
- Potentially publish signatures as part of our release notes on the homepage
- Preference should be given to https://github.com/sigstore/cosign as it's a de-facto standard

A rough outline:
```[tasklist]
- [x] Research: Find out which signing methods do exist in the Docker world and pick one
- [x] Pick a tool to do the actual signing, make sure it can be integrated into CI
- [x] Enable signing for one image (spike branch)
- [ ] https://github.com/stackabletech/documentation/issues/422
- [x] Sign operator images
- [ ] https://github.com/stackabletech/docker-images/issues/414
- [ ] https://github.com/stackabletech/issues/issues/409
```

**Comment by sbdtu5498** [comment]
How about using Cosign and providing the public key? I just did a similar issue, so if it is fine, I can tackle it. Cosign also supports keyless signing but keyless signing may not now be fully integrated with the various CI tooling. So for the time being signing with the key can be an approach

**Comment by dervoeti** [comment]
Thank you very much for your offer to help! But we already did most of the work, we did in fact decide to use cosign with keyless signing. We are currently testing it and will release it soon.
