### ISSUE TITLE
Release 23.7

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#372]
# Stackable Release 23.7

### General pre-requisites (before feature freeze)

```[tasklist]
- [ ] https://github.com/stackabletech/issues/issues/375
- [ ] https://github.com/stackabletech/operator-rs/issues/588
- [x] Bump operator-rs is on 0.41.0 for all product operators.
- [ ] https://github.com/stackabletech/issues/issues/393
- [x] Run getting-started scripts from Jenkins. All run successfully 27.06 (part-Jenkins, part-local) with the exception of the nifi/helm option, which is the only test that explicitly tests ExternalIP. Repeated 05.07 following latest changes (quotas, pod overrides).
- [x] ~An initial check for running clusters should be carried out about a week before the feature freeze (this is mentioned under "Check that an upgrade can be performed on an existing cluster without data loss" below): this will enable us to fix things in main, and can be done by running the demos against release 23.4 and then upgrading the operators.~ This will be done after the release (see task below).
- [ ] https://github.com/stackabletech/stackable-utils/pull/47
- [ ] https://github.com/stackabletech/operator-templating/issues/253
- [ ] https://github.com/stackabletech/issues/issues/402
```

### Other release-specific pre-requisites
- [x] #334 

### Feature freeze

This will not be so crucial with release branches, but is nonetheless sensible as it will make it easier to cherry-pick any release-related bugfixes from main into the release branch.

### End of the release cycle (Release day)

```[tasklist]
#### Technical tasks
- [x] Create release branches for docker-images (see stackable-utils for script to create branches)
- [x] Create release tag(s) for docker-images (see stackable-utils for scripts to create tags)
- [x] Create release branches for operators (see stackable-utils for script to create branches)
- [x] Create release tag(s) for operators (see stackable-utils for scripts to create tags)
- [x] Update operator changelogs in main using the post-release script
- [x] Check integration tests (see the Nuclino link below)
- [x] Check getting started scripts (see the Nuclino link below)
- [x] Check (new) stackablectl Stacks and Demos (see the Nuclino link below)
- [x] test with locally updated (to new release number) `releases.yaml`
- [ ] https://github.com/stackabletech/release/pull/24
- [x] Check that an upgrade can be performed on an existing cluster without data loss.
```

```[tasklist]
#### Documentation tasks
- [x] Check the Changelog and/or issue labels to compile Release Highlights
- [ ] https://github.com/stackabletech/documentation/pull/420
- [x] Document how to use stackablectl to uninstall all and install new release
- [x] Document how to use helm to uninstall all and install new release
- [x] Every breaking change of all our operators
- [x] List dropped supported product versions (if there are some)
- [x] List supported k8s versions
- [x] ~Sync supported k8s versions in the READMEs with what is in the release notes (and apply templating)~ The READMEs now reference the docs.
- [x] Update version of main documentation repo
- [x] Set the release to "Released" in the Feature Tracker and create a new release
- [x] Add documentation note (release notes): when we change the default pvc size, the user needs to delete the sts, as we are not allowed to change the pvc in sts spec
```

Marketing tasks can now reference published documentation.

```[tasklist]
#### Marketing tasks
- [x] Write marketing / customer oriented release summary to be published in the marketing channels
- [x] Update the homepage banner (as long as we have it) to point to the new release
- [x] Write a blogpost / news article announcing the new release (optional)
- [x] Write a description of new demos for hmepage/demos section (23.7: no new demos)
- [x] Announce Release on linkedIn
- [x] Announce Release on Twitter (optional)
- [x] Announce Release in Newsletter (optional)
- [x] Produce a release highlight video (optional)
- [x] Announce Release on Hacker News (optional)?
- [x] Inform Kubernetes Podcast about Release (optional)
- [x] Post an announcement in the GitHub [Discussions Announcement forum](https://github.com/stackabletech/community/discussions/categories/announcements)
- [x] Post to the DOK Community (Lars)
- [x] Post via OSBA (Lars)
- [x] Announce release on Discord
```

```[tasklist]
#### Post-release tasks
- [x] Bump Rust version. This can be done [in this file](https://github.com/stackabletech/operator-templating/blob/main/repositories.yaml) by changing rust_version and also for the ubi base image [here](https://github.com/stackabletech/docker-images/blob/main/ubi8-rust-builder/Dockerfile#L25). Please be aware that this action will change it for all repositories at the same time (when merging the templating PRs).
- [ ] https://github.com/stackabletech/operator-templating/pull/270
- [ ] https://github.com/stackabletech/docker-images/pull/419
- [x] Run renovate manually
- [x] Check/bump ubi8 base image
- [ ] https://github.com/stackabletech/docker-images/pull/420
- [x] ~Create issue for release-specific Openshift certification~ Not being done for this release.
- [x] Define product versions to include in the next release (added as a prep item in https://github.com/stackabletech/issues/issues/407)
- [x] Decide if hello-world and edc operators should be included in the release scripts (on the arch board)
- [ ] https://github.com/stackabletech/stackable-utils/pull/48
```
#### Testing

Use the table here: https://app.nuclino.com/Stackable/Engineering/Release-237-e76f95cb-da97-47bf-b22e-12535ea2632f
