### ISSUE TITLE
Operator fails "silently" to update Cluster's resource

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#383]
This is a tracking ticket for the whole functionality. It originates from the [trino cluster issue](https://github.com/stackabletech/trino-operator/issues/342).

## Refinement:
We've discussed several option alongside automatic resizing and restarting of `STS` to keep the user working.

However, we'd like to implement only the first step, since it is easy to overlook.

We'd suggest:
Create an Event in Cluster Ressource e.g. TrinoCluster:
TrinoCluster CRD -> TrinoCluster CR will log an event "Changes could not be applied due to following reason: "Event from STS" " ( made up, could be better )

The advantage would be that TrinoCluster appears unhealthy in ArgoCD e.g. which will make it more easy to detect as a user.

**Prerequisites:**
- [ ] Discussion of a solution in the Architecture Board
- [ ] Decision on relevance
- [ ] Spike in an operator (Suggestion is Zookeeper)

**Tasks:**
- [ ] https://github.com/stackabletech/trino-operator/issues/342
- [ ] https://github.com/stackabletech/zookeeper-operator/issues/679
- [ ] https://github.com/stackabletech/hive-operator/issues/339
- [ ] https://github.com/stackabletech/airflow-operator/issues/276
- [ ] https://github.com/stackabletech/druid-operator/issues/438
- [ ] https://github.com/stackabletech/hbase-operator/issues/358
- [ ] https://github.com/stackabletech/hdfs-operator/issues/352
- [ ] https://github.com/stackabletech/kafka-operator/issues/586
- [ ] https://github.com/stackabletech/nifi-operator/issues/469
- [ ] https://github.com/stackabletech/spark-k8s-operator/issues/239
- [ ] https://github.com/stackabletech/superset-operator/issues/366

**Definition of Done:**
- PVC's can be resized on the fly via sts / podtemplate definition

**Comment by nightkr** [comment]
So, more generally, the root issue here is that we don't properly report reconciliation errors as Events, right?

**Comment by maltesander** [comment]
> So, more generally, the root issue here is that we don't properly report reconciliation errors as Events, right?

I think that works as expected. The problem is that we cannot resize PVCs (or at least increase, decrease brings up other problems) via the pod template as far is i checked. CPU and memory worked though.
But then yeah, then the event / error is not very clear about that.

**Comment by lfrancke** [comment]
Decided not to tackle this at the moment

**Comment by Maleware** [comment]
Error message appear to be sufficient. Nothing to do just now.

However at some point we want to resize PVCs through our operators. Thus not closing the ticket just yet.
