### ISSUE TITLE
Set explicit resources on all containers

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#394]
Part of https://github.com/stackabletech/issues/issues/368, **only for the products, not the operators**

**Container resources**: https://docs.google.com/spreadsheets/d/1iWX1g4HaY3sFN9846BYd8kXZDU6FQkwSPmILsWMClE0/edit

Set up resource quotas in in integration tests:

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/289
- [ ] https://github.com/stackabletech/druid-operator/pull/444
- [ ] https://github.com/stackabletech/hbase-operator/pull/366
- [ ] https://github.com/stackabletech/hdfs-operator/pull/359
- [ ] https://github.com/stackabletech/hive-operator/pull/345
- [ ] https://github.com/stackabletech/kafka-operator/pull/595
- [ ] https://github.com/stackabletech/nifi-operator/pull/476
- [ ] https://github.com/stackabletech/opa-operator/pull/453
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/249
- [ ] https://github.com/stackabletech/superset-operator/pull/371
- [ ] https://github.com/stackabletech/trino-operator/pull/434
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/693
- [ ] https://github.com/stackabletech/hdfs-operator/pull/365
- [x] edc - We will handle resources in a larger refactoring later on
- [ ] https://github.com/stackabletech/hello-world-operator/pull/14
```

**Comment by sbernauer** [comment]
:partying_face:
