### ISSUE TITLE
Signed Commits

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#400]
```[tasklist]
### Tasks
- [x] Research how signed commits in Git work
- [x] Evaluate https://github.com/sigstore/gitsign
- [x] Document the workflow to setup signed commits in Nuclino
- [x] Test the documentation
- [x] Present signed commits to the team
- [x] Research how best to require signed commits across all our repositories
- [x] Enable required signed commits
- [x] Add an item to the Onboarding Handbook and the Employee Handbook
```

**Comment by lfrancke** [comment]
The documentation can currently be found here: https://app.nuclino.com/Stackable/Knowledge-Base/Git-Signed-Commits-819632a1-7354-4f8d-876f-5d89c6e4bca9

**Comment by lfrancke** [comment]
gitsign is not currently supported by GitHub so I will exclude it as an allowed/supported mechanism for now

https://github.com/sigstore/gitsign/issues/40

**Comment by lfrancke** [comment]
I decided not to require signed commits for now. We might revisit this later. Last task is to add it to Nuclino.
