### ISSUE TITLE
Demos/Release 23.7: test demos pre-release and create a corresponding PR

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#402]
See https://github.com/stackabletech/stackablectl/pull/269

```[tasklist]
### Tasks
- [x] demo airflow-scheduled-job
- [x] demo hbase-hdfs-load-cycling-data
- [x] demo: nifi-kafka-druid-earthquake-data
- [x] demo: nifi-kafka-druid-water-level-data
- [x] demo: spark-k8s-anomaly-detection-taxi-data
- [x] demo: trino-iceberg
- [x] demo: trino-taxi-data
- [x] demo: data-lakehouse-iceberg-trino-spark: (tested in reduced scope: fewer resources and less data)
- [x] demo: logging
- [x] stack: monitoring
- [x] stack: tutorial-openldap
- [x] stack: openldap
- [x] demo: jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data
- [x] stack: dual-hive-hdfs-s3
```
