### ISSUE TITLE
Increase the size limit of the log volume

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#403]
Operators:

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/299
- [ ] https://github.com/stackabletech/commons-operator/pull/167
- [ ] https://github.com/stackabletech/druid-operator/pull/452
- [ ] https://github.com/stackabletech/edc-operator/pull/20
- [ ] https://github.com/stackabletech/hbase-operator/pull/375
- [ ] https://github.com/stackabletech/hdfs-operator/pull/372
- [ ] https://github.com/stackabletech/hello-world-operator/pull/18
- [ ] https://github.com/stackabletech/hive-operator/pull/354
- [ ] https://github.com/stackabletech/kafka-operator/pull/604
- [ ] https://github.com/stackabletech/listener-operator/pull/83
- [ ] https://github.com/stackabletech/nifi-operator/pull/486
- [ ] https://github.com/stackabletech/opa-operator/pull/460
- [ ] https://github.com/stackabletech/secret-operator/pull/294
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/259
- [ ] https://github.com/stackabletech/superset-operator/pull/383
- [ ] https://github.com/stackabletech/trino-operator/pull/445
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/704
```
