### ISSUE TITLE
Let operators pick stackable version automatically

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#404]
As a user I don't want to specify the image.stackableVersion in every custom resource as this is tedious and error-prone.
Problems:
1. Tedious: All CRs need to be touched every release. All docs either point to 0.0.0-dev or a fixed release. Should I point to 23.7 or 23?
2. Error prone: During the trino (and others) bump 23.4 -> 23.7 the 23.4 did not work with the 23.7 image, so users were not able to only upgrade the operator to 23.7, as the image was too old for the operator => Crashloop, version needed to be bumped in the CR. Another problem: Should I point to 23.7 or 23?
3. Does not support only upgrading the operators without the need to touch every CR in the cluster (see 2. trino example)

The proposed solution should fix all this problems.

A follow-up task is to default the productVersion to our LTS line as well, so that users don't need to specify even a single version. This is however more complicated (think of when a release line ends in 23.4 and a new one starts in 23.7. *When* should the operator upgrade the product? In many cases the operator does not even support updating the product (e.g. https://github.com/stackabletech/hdfs-operator/issues/362))

```[tasklist]
### Tasks
- [x] stackable version can be omitted, in this case it defaults to the same *full* version of the operator (e.g. 23.7.0)
- [x] This must also work for 0.0.0-dev operators and -pr versions (this should all work automatically - needs to be tested however)
- [ ] https://github.com/stackabletech/documentation/pull/425
- [ ] https://github.com/stackabletech/operator-rs/pull/619
- [x] All tests are updated
- [x] All docs are updated
- [ ] https://github.com/stackabletech/airflow-operator/pull/312
- [ ] https://github.com/stackabletech/druid-operator/pull/458
- [ ] https://github.com/stackabletech/hbase-operator/pull/385
- [ ] https://github.com/stackabletech/hive-operator/pull/360/
- [ ] https://github.com/stackabletech/hdfs-operator/pull/381
- [ ] https://github.com/stackabletech/kafka-operator/pull/611
- [ ] https://github.com/stackabletech/nifi-operator/pull/493
- [ ] https://github.com/stackabletech/opa-operator/pull/467
- [ ] https://github.com/stackabletech/trino-operator/pull/441
- [ ] https://github.com/stackabletech/trino-operator/pull/455
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/267
- [ ] https://github.com/stackabletech/superset-operator/pull/390
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/711
- [ ] https://github.com/stackabletech/documentation/pull/433
- [ ] https://github.com/stackabletech/kafka-operator/pull/613
- [ ] https://github.com/stackabletech/documentation/pull/434
- [x] All stacks + demos are updated => NOT done, as this can be done once 22.11 is released and stacks are bumped
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/268
- [ ] https://github.com/stackabletech/trino-operator/pull/456
```
