### ISSUE TITLE
Upgrade Vector to version 0.31.0

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/issues#406]
# Description

Vector should be upgraded to the latest version (which is version 0.31.0 at the time of writing). Currently, version 0.26.0 is used. In stackabletech/docker-images#412, the changelogs from version 0.26.0 to 0.31.0 were checked and no features or bugfixes were found which would be significant for the Stackable Data Platform. But there are some breaking changes which would require adjustments in [operator-rs](https://github.com/stackabletech/operator-rs/) and the integration tests of all operators. So if an important bugfix is released in the future then the burden of upgrading would be quite high. To reduce the risk to face a huge workload at an inopportune time, the upgrade should be done soon.

The integration tests use the [Vector Helm Charts](https://github.com/vectordotdev/helm-charts) to set up a Vector aggregator for testing. Often Helm chart version 0.19.0 is used which deploys Vector 0.27.0. This Helm chart version should be upgraded to version 0.23.0 which deploys Vector 0.31.0.

# Importance and urgency

The upgrade is not important but should be done in the medium term for the reasons mentioned above.

# Workaround

Version 0.26.0 works fine, so there is no need for a workaround.

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/docker-images/pull/429
- [ ] https://github.com/stackabletech/operator-rs/pull/625
- [ ] https://github.com/stackabletech/stackablectl/pull/272
- [ ] https://github.com/stackabletech/operator-templating/pull/275
- [ ] https://github.com/stackabletech/airflow-operator/pull/308
- [ ] https://github.com/stackabletech/druid-operator/pull/459
- [ ] https://github.com/stackabletech/hbase-operator/pull/382
- [ ] https://github.com/stackabletech/hdfs-operator/pull/378
- [ ] https://github.com/stackabletech/hive-operator/pull/361
- [ ] https://github.com/stackabletech/kafka-operator/pull/612
- [ ] https://github.com/stackabletech/nifi-operator/pull/494
- [ ] https://github.com/stackabletech/opa-operator/pull/465
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/269
- [ ] https://github.com/stackabletech/superset-operator/pull/391
- [ ] https://github.com/stackabletech/trino-operator/pull/453
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/709
```

## Issue checklist

This is a simple checklist of things to bear in mind when creating a new issue.

- [x] Describe the use-case, as far is possible. For instance, using the pattern "As a XXXX, I would like XXXX to be able to do XXXX" helps to identify the feature as well as the problem it is intended to address.
- [x] Indicate an approximate level of importance and urgency.
- [x] Indicate if there is a known work-around until such time as the issue has been implemented.
