### ISSUE TITLE
SDP operators in OperatorHub

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#410]
As an interested user looking for available Kubernetes Operators I'd like to find the Stackable Operators on operatorhub.io

This is a suggested tasklist, change it if it's appropriate

```[tasklist]
### Tasks
- [ ] Evaluate the steps neceesary to show up on OperatorHub: https://operatorhub.io/contribute
- [ ] Decide whether we want to spend the effort and how much of it can be automatted
- [ ] If we decide to do it: Do it and document the steps
```
