### ISSUE TITLE
Fix issues in cyclonedx-rust-cargo so it creates valid SBOMs

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#411]
```[tasklist]
### Tasks
- [ ] https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/444
- [ ] https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/14
- [ ] https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/441
```
