### ISSUE TITLE
Switch to workspace dependencies

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#416]
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/314
- [ ] https://github.com/stackabletech/druid-operator/pull/460
- [ ] https://github.com/stackabletech/hbase-operator/pull/387
- [ ] https://github.com/stackabletech/hdfs-operator/pull/382
- [ ] https://github.com/stackabletech/hive-operator/pull/362
- [ ] https://github.com/stackabletech/kafka-operator/pull/614
- [ ] https://github.com/stackabletech/nifi-operator/pull/495
- [ ] https://github.com/stackabletech/opa-operator/pull/468
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/270
- [ ] https://github.com/stackabletech/superset-operator/pull/392
- [ ] https://github.com/stackabletech/trino-operator/pull/458
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/714
- [ ] https://github.com/stackabletech/commons-operator/pull/173
- [ ] https://github.com/stackabletech/listener-operator/pull/98
- [ ] https://github.com/stackabletech/secret-operator/pull/303
- [ ] https://github.com/stackabletech/hello-world-operator/pull/21
```
