### ISSUE TITLE
OpenShift support improvements

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#432]
## Issue checklist

In this epic we collect issues ranging from development to deployment and support on the OpenShift platform.

### Development

```[tasklist]
### Tasks
- [ ] Generate OLM operator bundles in a similar way to Helm charts
- [ ] Add Tilt support for OpenShift (SCCs are not installed now)
- [ ] Run automated kuttl tests on OpenShift
```

### Publishing and Deployment (OLM)

```[tasklist]
### Tasks
- [ ] Support and document "disconnected" deployments.
- [ ] Investigate how to customize OLM deployments (aka Helm values)
- [ ] Run automated certification pipelines (with and without publishing )
- [ ] Run automated pipelines to publish operators to the community operator hub
```

### Maintenance (platform updates)

```[tasklist]
### Tasks
- [ ] Figure out steps required to make updates as seamless as possible (no downtime, patch resources, etc)
```

### Certification

```[tasklist]
### Tasks
- [ ] Automate the certification process (does the RH portal have an API?)
```

**Comment by razvan** [comment]
Closing this. All existing tasks have been addressed. See comments in the task lists.

New issues will be created directly under #511
