### ISSUE TITLE
Support PodDisruptionBudgets

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#435]
Break-week topic of @sbernauer 

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/documentation/pull/452
- [ ] https://github.com/stackabletech/operator-rs/pull/653
- [ ] https://github.com/stackabletech/operator-rs/pull/661
- [ ] https://github.com/stackabletech/documentation/pull/454
- [ ] https://github.com/stackabletech/documentation/pull/461
- [ ] https://github.com/stackabletech/airflow-operator/pull/330
- [ ] https://github.com/stackabletech/druid-operator/pull/477
- [ ] https://github.com/stackabletech/hbase-operator/pull/399
- [ ] https://github.com/stackabletech/hdfs-operator/pull/394
- [ ] https://github.com/stackabletech/hive-operator/pull/376
- [ ] https://github.com/stackabletech/kafka-operator/pull/625
- [ ] https://github.com/stackabletech/nifi-operator/pull/509
- [ ] https://github.com/stackabletech/opa-operator/pull/480
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/288
- [ ] https://github.com/stackabletech/superset-operator/pull/407
- [ ] https://github.com/stackabletech/trino-operator/pull/481
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/730
- [ ] https://github.com/stackabletech/hello-world-operator/pull/27
- [x] edc - not needed
- [ ] https://github.com/stackabletech/hdfs-operator/issues/398
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/731
```

**Comment by lfrancke** [comment]
Can this be closed?

**Comment by sbernauer** [comment]
Yes :)
