### ISSUE TITLE
Support running on non-default cluster DNS settings

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#436]
Reported in https://github.com/orgs/stackabletech/discussions/35

Currently we hard-code `svc.cluster.local` in a lot of places.
This is bad, as some user installations have a non-default installation by doing stuff such as https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/, e.g. `--cluster-domain=<default-local-domain>`.
We need users to be able to configure the Service DNS suffix.

Possible solutions:
1. Add an cli flag (or better: env var) to the product operators which overrides the `svc.cluster.local` default.
2. More ideal: Somehow let operators detect the DNS suffix of the k8s cluster and use that
3. Maybe listener-operator can help us here
4. [...]

# Research Tasks

- [x] Leave out e.g. `cluster.local` and let the DNS lookup do its thing? What about secret op certs? (timeboxed 2h) -> does not work with secret op
- [x] How do other operatores deal with DNS cluster settings? (timeboxed 2h) -> Strimzi e.g. uses env vars as well alla `KUBERNETES_SERVICE_DNS_DOMAIN`

# Refinement

## Option 1: Use ENV var only

- The operator uses an ENV var (e.g. `CLUSTER_DNS_SUFFIX`) deployed via helm (openshift will differ)
- Will default to `cluster.local` if not set

### Pro

- Easy to implement
- Straight forward, no need parsing resolv.conf
- Foundation for Option 2 that can be extended
- Implementation does not differ for Kubernetes / OS

### Con

- Openshift/Olm: We cannot set the var `CLUSTER_DNS_SUFFIX` for the secret and listener operator (due its special daemonset deployment).
  We can however edit the demonset afterwards and add the env var (cumbersome but possible).

## Option 2: Use ENV var + kubernetes + dns suffix auto detection

1. Operator reads an env var e.g. `CLUSTER_DNS_SUFFIX` (containing e.g. `my-cluster.local`)
	- If this exists use the suffix provided in there and **return**
2. If `CLUSTER_DNS_SUFFIX` does not exist, determine whether we run in kubernetes or not via
	- Checking e.g. `KUBERNETES_SERVICE_HOST` variable
	- Checking e.g. `KUBERNETES_SERVICE_PORT` variable
3. If we run in Kubernetes, read and parse the `resolv.conf`
	```
	cat /etc/resolv.conf 
	search sble-operators.svc.cluster.local svc.cluster.local cluster.local
	nameserver 10.243.21.53
	options ndots:5
	```
	We need to parse the "shortest" entry in the last "search" entry (here: `cluster.local`). 

   If we do not run in Kubernetes, we default to `cluster.local` and **return**

4. If this did not result in a proper DNS suffix we do **not** default, but error out. There wont be any working deployment.

### Pro

- Non breaking (unless we act upon positive research results from research task 1)
- Definite improvement for Kubernetes and Openshift (the resolv.conf parsing)
- Implementation does not differ for Kubernetes / OS

### Con

- Openshift/Olm: We cannot set the `CLUSTER_DNS_SUFFIX` for the secret and listener operator (due its special demonset deployment).
  We can however edit the demonset afterwards and add the env var (cumbersome but possible).
- The auto-detection is only a 95% solution, since there may be edge cases not considered for now. But users can set their DNS explicitly using the config env var.

## Option 3: DNS operator (OS) / Custom object (Kubernetes) containing the DNS suffix read by all operators

- Openshift offers a DNS operator which status could be queried to retrieve the cluster domain/dns https://docs.openshift.com/container-platform/4.17/networking/dns-operator.html#nw-dns-view_dns-operator
- We could "mimic" that behavior in normal kubernetes and provide a custom object or extract from kube-dns / core-dns

### Pro

- Generic solution utilizing OS DNS operator or kube-dns / coredns

### Con

- Operators will differ for kubernetes / openshift
- Currently operators do not "know" if they run on Kubernetes or OS (its just our templating around that)
- More implementation effort

## Option 4: Provide a config map in the namespace of the operators containing common shared settings

- We deploy an additional configmap in the operator namespace containing shared settings like cluster domain

### Pro

- Implementation does not differ for Kubernetes / OS
- Simple solution
- Possible preperation for other shared settings

### Con

- Which namespace? Possible name collisions if installed in default?
- Not sure if that is possible / acceptable in OS
- Deployed by us or by user?

## Outcome

- Chosen option 2

**Comment by fhennig** [comment]
maybe a bit of a tangential question, but 

> Add an cli flag to the product operators which overrides the svc.cluster.local default.

How is the customer supposed to use CLI flags? since the Operator is in the container

**Comment by sbernauer** [comment]
Good question!
I *though* there is some sort of configuration that is passed to our operators but I can't find it, so it might be wrong.

Anyway, in case we can not automatically detect it the new setting must go into the [values.yaml](https://github.com/stackabletech/trino-operator/blob/25996080441e6f131ceb2e0f4245fcde2ec9aef4/deploy/helm/trino-operator/values.yaml) of the operators, the helm-chart can than e.g. set an env var or cli flag on our operators

**Comment by nightkr** [comment]
`values.yaml` into env var is largely the way to go for those config things IMO. We use it for secret-op's kubelet dir already.

For this specifically, it looks like we could auto-detect it from the resolvconf, but there should definitely be an option to override it as well.

**Comment by NickLarsenNZ** [comment]
Just pointing out that the overridable K8s DNS suffix is `cluster.local` (as opposed to `svc.cluster.local`)

**Comment by Techassi** [comment]
> For this specifically, it looks like we could auto-detect it from the resolvconf, but there should definitely be an option to override it as well.

I already wrote a basic `resolv.conf` parser for a different (personal) project [here](https://github.com/portal-rs/portal/blob/main/crates/common/src/resolv.rs). It could serve as a jumping-off point for our own implementation.

**Comment by NickLarsenNZ** [comment]
If we want to auto-detect, I suggest we find a source of truth within the cluster.

The kube-api might give this in server-info. There is also core-dns config, but we shouldn't assume they run core-dns either.

**Comment by maltesander** [comment]
Thats an OS `resolv.conf`
```
cat /etc/resolv.conf
search openshift-service-ca-operator.svc.cluster.local svc.cluster.local cluster.local cmx.repl-openshift.build
nameserver 172.30.0.10
options ndots:5
```

**Comment by maltesander** [comment]
# Tasks for Option 2

## Preperation

- [ ] Create generic entry in docs to point operators to explaining the CLUSTER_DNS_DOMAIN env var and the mechanism to autodetect / parse the resolve.conf
- [ ] Update operator templating and add the env var `CLUSTER_DNS_DOMAIN` (defaults to `cluster.local`) to the operator deployments
- [ ] Prepare helper methods in operator RS to check env var / parse resolve.conf  etc. that will be used in operators
- [ ] In every operator:
	1. Create entry in `<product>-operator/deploy/helm/<product>-operator/values.yaml` like `clusterDnsDomain: cluster.local`
	2. Use the created helper methods to read dns env var / or parse resolve.conf
	3. Pass on extracted dns suffix to the operator context
	4. Use created field from context for e.g. FQDN / service methods (certs, etc)

## Rollout (sorted for desired order)

- [ ] Secret
- [ ] Listener
- [ ] Commons
- [ ] OPA
- [ ] ZooKeeper
- [ ] Hive
- [ ] Hadoop HDFS
- [ ] Airflow
- [ ] Druid
- [ ] HBase
- [ ] Kafka
- [ ] NiFi
- [ ] Spark
- [ ] Superset
- [ ] Trino
- [ ] EDC
- [ ] Hello World

**Comment by maltesander** [comment]
Closing this. Option 1 (only read ENV var for cluster domain) was chosen and implemented.

**Comment by maltesander** [comment]
General docs https://docs.stackable.tech/home/nightly/guides/kubernetes-cluster-domain
Link in Kubernetes docs https://docs.stackable.tech/home/nightly/kubernetes/#_configuring_the_cluster_domain

Release notes:
```
The cluster domain (default `cluster.local`) which caused problems in non-default cluster setups can now be configured in all operators using the ENV variable `KUBERNETES_CLUSTER_DOMAIN` or setting the helm value `kubernetesClusterDomain` during installation as described [here](https://docs.stackable.tech/home/nightly/guides/kubernetes-cluster-domain).
```
