### ISSUE TITLE
Platform Authorization

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#438]
This is a super-epic to track the work needed until we have an integrated authorization story for our platform.
This epic will be split into sub-epics to generate units of work that can be pulled onto the board and finished in a reasonable amount of time.
For now I have simply added tasks lists below, to make discussions easier.

```[tasklist]
### Design
- [ ] Write ADR on abstraction layer 
- [ ] Write ADR on group mapping architecture (consider jwt, oidc, ldap, static, ...)
- [ ] Implement user group mapper for Keycloak
- [ ] Implement user group mapper for LDAP

```

```[tasklist]
### Group based authorization
- [ ] First release of group mapper tool (with Keycloak backend)
- [ ] Implement user group mapper for LDAP
- [ ] Other mappers according to ADR
```

```[tasklist]
### HDFS
- [ ] Implement Authorizer
- [ ] Implement Group Mapper (not for all tools)
- [ ] Define abstraction layer according to guidelines set out in ADR 
- [ ] Implement Rego rule file for abstraction layer
- [ ] Implement abstraction layer in CRDs
```

```[tasklist]
### Trino
- [ ] https://github.com/trinodb/trino/pull/17940
- [ ] Define abstraction layer according to guidelines set out in ADR 
- [ ] Implement Rego rule file for abstraction layer
- [ ] Implement abstraction layer in CRDs
```

```[tasklist]
### Druid
- [ ] https://github.com/stackabletech/druid-operator/issues/368
- [ ] Define abstraction layer according to guidelines set out in ADR 
- [ ] Implement Rego rule file for abstraction layer
- [ ] Implement abstraction layer in CRDs
```

**Comment by fhennig** [comment]
This is very broadly also related: https://github.com/stackabletech/issues/issues/124 

Since this ticket is an initiative now, maybe we can have another tasklist with "Ideas/Nice to Have" or something where tickets like the one above can go?
