### ISSUE TITLE
Upgrade Vector from version 0.31.0 to 0.33.0

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/issues#444]
Vector can be upgraded from version 0.31.0 (released 2023-07-05) to version 0.33.0  (released 2023-09-27).

## Release notes

* https://vector.dev/releases/0.33.0/
* https://vector.dev/releases/0.32.2/
* https://vector.dev/releases/0.32.1/
* https://vector.dev/releases/0.32.0/

### Version 0.33.0

- The default configuration format is now YAML. TOML still works and there are no plans to deprecate it. We should nevertheless convert our configuration to YAML because the documentation defaults to YAML and it makes things easier if both use the same format.
- > The `gelf` codec now defaults to framing using null byte (`\0`) when encoding. Previously it defaulted to newline (`\n`) but the GELF server implementation expects the null byte.

  This could affect our customers who use Graylog. It must be tested if changes are required to the configuration of the Vector aggregator if it is also upgraded. If changes are needed then it should be mentioned in our release notes and the customers should be informed.
- > the deprecated `to_timestamp` function was removed

  This function was already replaced in #406.

 ### Version 0.32.0
 
 - > Upgrade of OpenSSL from 1.1.1 to 3.1.2
 
   This is worth knowing but should not affect us.
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/operator-rs/pull/670
- [ ] https://github.com/stackabletech/docker-images/pull/479
- [ ] https://github.com/stackabletech/stackablectl/pull/286
- [ ] https://github.com/stackabletech/airflow-operator/pull/334
- [ ] https://github.com/stackabletech/airflow-operator/pull/339
- [ ] https://github.com/stackabletech/druid-operator/pull/480
- [ ] https://github.com/stackabletech/hbase-operator/pull/403
- [ ] https://github.com/stackabletech/hdfs-operator/pull/409
- [ ] https://github.com/stackabletech/hive-operator/pull/377
- [ ] https://github.com/stackabletech/kafka-operator/pull/627
- [ ] https://github.com/stackabletech/nifi-operator/pull/513
- [ ] https://github.com/stackabletech/opa-operator/pull/482
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/291
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/301
- [ ] https://github.com/stackabletech/superset-operator/pull/415
- [ ] https://github.com/stackabletech/trino-operator/pull/491
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/732
```

**Comment by siegfriedweber** [comment]
> The `gelf` codec now defaults to framing using null byte (`\0`) when encoding. Previously it defaulted to newline (`\n`) but the GELF server implementation expects the null byte.

The GELF TCP input requires a null byte as delimiter (see https://github.com/Graylog2/graylog2-server/issues/1240). The GELF HTTP input still must be delimited by a newline. Therefore the framing method must now be explicitly set to `newline_delimited`:

```yaml
---
role: Aggregator
customConfig:
  sinks:
    graylog:
      type: http
      encoding:
        codec: gelf
      framing:
        method: newline_delimited
```

**Comment by lfrancke** [comment]
Can this issue be closed?

**Comment by maltesander** [comment]
Yeah was done with the product images and @siegfriedweber moved it to done :)
