### ISSUE TITLE
Update product versions for release 23.11

### ISSUE THREAD

**Issue by maltesander** [stackabletech/issues#446]
We want to update our product versions for the release 23.11.

The single source of truth for this release is currently https://docs.google.com/spreadsheets/d/1uR6nJR3nMxSI51dPFbVJTqA4R3p7UkGU5acrXJNOyNQ/edit#gid=866098130.

This is a developing ticket and please feel free to add missing items.

The tasks are collected here for now but will be splitted in single tickets for each operator.

# General task overview

A collection of all possible tasks, may differ from operator to operator.

## nexus

- [ ] Upload new product versions marked as "Add" in nuclino into nexus (use scripts where available)
- [ ] Optional(?): Remove product versions marked as "Remove" from nexus
- [ ] Upload new versions for vector, jmx-exporter, phonex etc. (use scripts where available)

## docker-images

- [ ] Add new product versions marked as "Add" in nuclino to conf.py
- [ ] Remove product versions marked as "Remove" from conf.py
- [ ] Create softlinks for hardcoded helpers (like jmx-exporter) e.g. see https://github.com/stackabletech/docker-images/blob/b03f901d06029474787cb8b38b758eab8f8d5a87/trino/Dockerfile#L35
- [ ] Automate upload via scripts for products where possible e.g. see https://github.com/stackabletech/docker-images/blob/main/hadoop/upload_new_hadoop_version.sh
- [ ] Build all images

## operators

- [ ] Adapt examples and/or getting started guide to latest version
- [ ] Add new versions to supported versions in docs
- [ ] Add deprecated versions in docs
- [ ] Remove versions marked as "Remove" from supported versions in docs
- [ ] Grep through the whole repo for removed versions to be sure they are not used anywhere anymore
- [ ] Remove versions marked as "Remove" from integrationtests (including removed versions from other operators if used in the tests)
- [ ] Remove hardcoded versions for helpers (e.g. jmx-exporter)
- [ ] Run full integration test suite

# Per operator

## Airflow
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/477
- [ ] https://github.com/stackabletech/airflow-operator/pull/334
- [ ] https://github.com/stackabletech/airflow-operator/pull/339
```

## Druid
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/485
- [ ] https://github.com/stackabletech/druid-operator/pull/480
```

## HBase
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/494
- [ ] https://github.com/stackabletech/hbase-operator/pull/403
```

## Hadoop HDFS
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/478
- [ ] https://github.com/stackabletech/hdfs-operator/pull/409
```

## Hive
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/472
- [ ] https://github.com/stackabletech/hive-operator/pull/377
```

## Kafka
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/476
- [ ] https://github.com/stackabletech/kafka-operator/pull/627
```
## NiFi
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/473
- [ ] https://github.com/stackabletech/nifi-operator/pull/513
```

## Spark
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/475
- [ ] https://github.com/stackabletech/ny-tlc-report/pull/6
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/291
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/301
```

## Superset
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/482
- [ ] https://github.com/stackabletech/docker-images/pull/489
- [ ] https://github.com/stackabletech/superset-operator/pull/415
```

## Trino
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/trino-operator/issues/485
- [ ] https://github.com/stackabletech/docker-images/pull/487
- [ ] https://github.com/stackabletech/trino-operator/pull/491
- [ ] https://github.com/stackabletech/trino-operator/pull/494
```

## ZooKeeper
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/470
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/732
```

## OPA
```[tasklist]
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/docker-images/pull/471
- [ ] https://github.com/stackabletech/opa-operator/pull/482
```

## Vector
```[tasklist]
- [ ] https://github.com/stackabletech/docker-images/pull/479
- [ ] https://github.com/stackabletech/operator-rs/pull/670
```

**Comment by maltesander** [comment]
Please contact me before starting anything here.

**Comment by maltesander** [comment]
All done!
