### ISSUE TITLE
Run/check getting-started scripts pre-release 23.11

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#451]
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/304
- [ ] https://github.com/stackabletech/superset-operator/pull/419
- [ ] https://github.com/stackabletech/nifi-operator/pull/523
```
