### ISSUE TITLE
Tracking: Migrate demos/stacks to new repository

### ISSUE THREAD

**Issue by Techassi** [stackabletech/issues#455]
```[tasklist]
## Tasks
- [x] Move demo/stack files to new `demos` repository
- [ ] https://github.com/stackabletech/stackablectl/pull/291
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/140
- [ ] https://github.com/stackabletech/stackable-cockpit/issues/98
```
```[tasklist]
### Documentation Tasks
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/160
- [ ] https://github.com/stackabletech/demos/pull/6
- [ ] https://github.com/stackabletech/documentation/pull/502
- [ ] https://github.com/stackabletech/demos/pull/7
```

**Comment by fhennig** [comment]
Could we then completly archive the 'stackablectl' repo?

**Comment by Techassi** [comment]
> Could we then completly archive the 'stackablectl' repo?

In theory: yes!
