### ISSUE TITLE
Tracking: OIDC support

### ISSUE THREAD

**Issue by Techassi** [stackabletech/issues#462]
This issue tracks the implementation of OIDC support across the SDP.

```[tasklist]
### General Tasks
- [ ] https://github.com/stackabletech/operator-rs/pull/680
- [ ] https://github.com/stackabletech/documentation/pull/460
```

```[tasklist]
### Operator Tasks
- [ ] https://github.com/stackabletech/trino-operator/tree/feature/support-oauth2
```

**Comment by fhennig** [comment]
I had this one before: https://github.com/stackabletech/issues/issues/431 (for context)

**Comment by Techassi** [comment]
Oh you are right. Let me merge some of the contents then.
