### ISSUE TITLE
ARM64 RoadMap (Tracking Epic)

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#463]
# Why we do that?
Our goal is to have a stable, official release with 24.7 as fully supported, tested and maintainable arm release. Thus the following shows a top level roadmap for SDP moving to multi architecture releases. 

# Overview
1. Infrastructure to build arm64 images 
2. Pipeline to build arm64 images
3. Testing infrastructure
4. Arm-safe dependency updating
5. Knowledge: https://app.nuclino.com/Stackable/Knowledge-Base/SDP-on-ARM64-801af485-a5d4-428e-a274-e118d65b7da4

RELEASE! 🙌

# Prerequisites:
Defines what's necessary to have sufficient infrastructure to build and test on

```[tasklist]
### Infrastructure Tasks
- [ ] https://github.com/stackabletech/issues/issues/483
- [ ] https://github.com/stackabletech/issues/issues/473
- [ ] https://github.com/stackabletech/issues/issues/474
- [x] A build runner is available in GitHub
```

# Development:

```[tasklist]
### Product and Operator images
- [ ] https://github.com/stackabletech/issues/issues/475
- [ ] https://github.com/stackabletech/issues/issues/519
- [ ] https://github.com/stackabletech/demos/issues/18
- [ ] https://github.com/stackabletech/issues/issues/516
- [ ] https://github.com/stackabletech/issues/issues/518
- [x] Scan ARM images for vulnerabilities
- [ ] https://github.com/stackabletech/issues/issues/582
```

```[tasklist]
### Tooling
```

```[tasklist]
### Dev process changes
- [ ] https://github.com/stackabletech/issues/issues/517
- [ ] https://github.com/stackabletech/issues/issues/487
- [ ] https://github.com/stackabletech/issues/issues/545
- [ ] https://github.com/stackabletech/issues/issues/546
```

```[tasklist]
### OpenShift
- [ ] https://github.com/stackabletech/issues/issues/559
- [ ] https://github.com/stackabletech/issues/issues/560
```

## Open questions

- even after everything is build on ARM for ARM, there might still be AMD binaries in the images. We want to check for that somehow: https://github.com/stackabletech/issues/issues/478 - Not clear how we can check this thoroughly. Manual scan of the image? @Maleware 
- nightly tests on ARM?
- long-term testing? We have the opportunity to have a long running test cluster _for free_! https://github.com/stackabletech/issues/issues/479
    - Test scenarios are regularly running and test arm64 images to some extend ( best case: A living cluster which does stuff like crawling, using, saving and things with data )

```[tasklist]
### Testing
- [ ] https://github.com/stackabletech/issues/issues/581
```

```[tasklist]
### Documentation
- [ ] https://github.com/stackabletech/issues/issues/577
```

**Comment by Maleware** [comment]
Docs: https://github.com/stackabletech/documentation/pull/527
