### ISSUE TITLE
Pipeline for automatically pushing arm64 images to Harbor is established

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#475]
We need to implement an workflow where this runner is used.

Prerequisites:
 - [x] [Build release 23.11.0 manually | issues#483](https://github.com/stackabletech/issues/issues/483) - we built all operators and all products for ARM once, so we know that it all works.
 - [x] There is an ARM runner to build on to run the CI

## Tasks

```[tasklist]
### Tasks
- [x] Add a new repo in Harbor the ARM images.
- [ ] https://github.com/stackabletech/issues/issues/552
- [ ] https://github.com/stackabletech/issues/issues/553
- [x] Add missing binaries to Nexus if they are not available for ARM yet. If ARM is not supported, ignore it
- [x] document products for which we cannot support ARM - this might be Superset, Airflow and Listener Operator
- [x] Ubi8-rust-builder multi arch to Harbor
```

## Open Questions

- Do we want to only build releases for ARM, or everything?
    - good: better dev experience for ARM devs
    - bad: more expensive because more build minutes and more storage costs. Basically everything is doubled.

## Acceptance Criteria

- products
    - product images are pushed to Harbor by using a manual triggered GH action
    - Products actually work on ARM - If they don't, this is documented
    - There is a list of products that we do not support for ARM (if any)
- operators
    - operator images are build as multi-architecture images and pushed to Harbor

**Comment by lfrancke** [comment]
Could you change the title of the issue to make sure what it refers to?
Place a reference in the text for example
"above" is a bit ambiguous :)

Thank you!

**Comment by Maleware** [comment]
I added the tasks as prerequisites, thanks for pointing it out.

We are currently using a Azure arm64 cluster to keep developing. Means, technically prerequisites are met but not in the way intended. 

Tasks will be checked as soon as we have physical hardware.

**Comment by lfrancke** [comment]
But can you please change the title of the issue as I asked in my previous comment?
It contains the word "above" which does not make sense

**Comment by Maleware** [comment]
The macOS arm64 github runner doesn't look very promising. Moving on to some others:

1. BuildJet do have a ARM64 runner and Ubuntu https://buildjet.com/for-github-actions/docs/about/pricing
2. CircleCI have some arm64 runner too https://circleci.com/docs/using-arm/

**Comment by lfrancke** [comment]
Please only look at BuildJet for now
Can you please update the tasklist in the ticket?

**Comment by Maleware** [comment]
https://github.com/stackabletech/docker-images/pull/600

this is going to conclude this ticket finally.

**Comment by Maleware** [comment]
This tracks now the progress of the other two tickets. When those are done, this can be reviewed.

**Comment by Maleware** [comment]
Release `24.3.0` is untested released in `stackable-experimental` as `multi architecture release` .

**Comment by lfrancke** [comment]
Did you update the docs? The tutorial you wrote says that only 23.11 is supported, that's not true anymore.

**Comment by Maleware** [comment]
I can do it right now. I planned to update docs when I have done basic testing if this is fine for you :)

**Comment by lfrancke** [comment]
Yep, that sounds good, thanks! I just don't want to be forgotten, thanks for being on top of this.

**Comment by Maleware** [comment]
This can be closed as all tasks are closed.
