### ISSUE TITLE
Generate OLM operator bundles in a similar way to Helm charts

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#484]
**Update 2024.03.06:** We decided to postpone this until after the release 24.3.
**Update 2024.04.05:** possibly replaced by https://github.com/stackabletech/issues/issues/561

As devs we want to automate the OpenShift releases, as it is currently a lot of manual work every release.

## Scope

This is about generating the OLM bundles initially.

- Making the actual release into the OpenShift repo is not part of this ticket. This is most likely just copying the bundles from the operator repos into the OpenShift releases repo
- Upgrading is also not part of this ticket

## Context

What do we need to know to generate the OLM bundles?
- Upgrade paths - leave empty for now
- related images - we need to write down in advance which images the bundle will pull. This means we need to write down which registry to pull from. - this information is not enforced
    - one related image is the operator image itself
    - product images maybe not considered for now
- CRDs - need to be split and put in
- What about common infos that are currently only in Helm? Maintain in Helm and OLM? Have a common source and generate? 
- operator specific "stuff"

we need changes in:
- operator-templating
- operator specific stuff

## Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/issues/issues/510
- [ ] after the spike: refine again
- [ ] roll something to all operators
```

## Acceptance Criteria

- In every operator there is a `deploy/OLM` directory that contains the OLM bundle
- The "Chart" can be generated without human intervention, just like the Helm Chart

**Comment by adwk67** [comment]
Closed in favour of https://github.com/stackabletech/issues/issues/561
