### ISSUE TITLE
tracking: Add labels to templated resources in operator Helm Charts

### ISSUE THREAD

**Issue by Techassi** [stackabletech/issues#501]
This requires changes in the manually maintained `values.yaml` file. 

This is used so users can add labels to the operator (and ClusterRole etc.) when installing with the Helm Chart.

(Note: At the moment, the operators _do not_ forward these labels to the resources that they deploy as part of the demo/stack. )

### References

- https://github.com/stackabletech/operator-rs/pull/723
- https://github.com/stackabletech/issues/issues/188

```[tasklist]
### Prerequisites
- [ ] https://github.com/stackabletech/operator-templating/pull/313
```
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/374
- [ ] https://github.com/stackabletech/commons-operator/pull/203
- [ ] https://github.com/stackabletech/druid-operator/pull/509
- [ ] https://github.com/stackabletech/edc-operator/pull/49
- [ ] https://github.com/stackabletech/hbase-operator/pull/441
- [ ] https://github.com/stackabletech/hdfs-operator/pull/460
- [ ] https://github.com/stackabletech/hello-world-operator/pull/48
- [ ] https://github.com/stackabletech/hive-operator/pull/406
- [ ] https://github.com/stackabletech/kafka-operator/pull/657
- [ ] https://github.com/stackabletech/listener-operator/pull/142
- [ ] https://github.com/stackabletech/nifi-operator/pull/560
- [ ] https://github.com/stackabletech/opa-operator/pull/507
- [ ] https://github.com/stackabletech/secret-operator/pull/352
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/344
- [ ] https://github.com/stackabletech/superset-operator/pull/448
- [ ] https://github.com/stackabletech/trino-operator/pull/528
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/763
```

**Comment by Techassi** [comment]
All linked PRs are merged, closing.
