### ISSUE TITLE
 Update product versions for release 24.3

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#502]
We want to update our product versions for the release 24.3.

[The single source of truth for this release](https://docs.google.com/spreadsheets/d/1uR6nJR3nMxSI51dPFbVJTqA4R3p7UkGU5acrXJNOyNQ/edit#gid=866098130)

This is a developing ticket and please feel free to add missing items.

The tasks are collected here for now but will be split into single tickets for each operator.

## Acceptance 

We want to bump old and new product versions with the latest ubi image releases. This means bumping the stackable version and rerunning the build actions. This includes our [Java base image](https://github.com/stackabletech/docker-images/tree/main/java-base) which should be done before updating any Java based products.

### Base images

- [ ] Java base image
- [ ] Check if JMX Prometheus Exporter was updated: https://github.com/prometheus/jmx_exporter
- [ ] Check if Vector has been updated
- [ ] Airflow
- [ ] Druid
- [ ] HBase (including HBase Operator Tools)
- [ ] Hadoop HDFS
- [ ] Hive (including JDBC driver)
- [ ] Kafka
- [ ] NiFi
- [ ] OPA
- [ ] Spark
- [ ] Superset
- [ ] Trino
- [ ] ZooKeeper

# General task overview

A collection of all possible tasks, may differ from operator to operator.

## nexus

- [ ] Upload new product versions marked as "Add" in nuclino into nexus (use scripts where available)
- [ ] Optional(?): Remove product versions marked as "Remove" from nexus
- [ ] Upload new versions for vector, jmx-exporter, phonex etc. (use scripts where available)

## docker-images

- [ ] Add new product versions marked as "Add" in nuclino to conf.py
- [ ] Remove product versions marked as "Remove" from conf.py
- [ ] Create softlinks for hardcoded helpers (like jmx-exporter) e.g. see https://github.com/stackabletech/docker-images/blob/b03f901d06029474787cb8b38b758eab8f8d5a87/trino/Dockerfile#L35
- [ ] Automate upload via scripts for products where possible e.g. see https://github.com/stackabletech/docker-images/blob/main/hadoop/upload_new_hadoop_version.sh
- [ ] Build all images

## operators

- [ ] Adapt examples and/or getting started guide to latest version
- [ ] Add new versions to supported versions in docs
- [ ] Add deprecated versions in docs
- [ ] Remove versions marked as "Remove" from supported versions in docs
- [ ] Grep through the whole repo for removed versions to be sure they are not used anywhere anymore
- [ ] Remove versions marked as "Remove" from integrationtests (including removed versions from other operators if used in the tests)
- [ ] Remove hardcoded versions for helpers (e.g. jmx-exporter)
- [ ] Run full integration test suite

# Per operator

```[tasklist]
### Airflow: new: 2.7.3, 2.8.1; deprecated: 2.7.2, 2.7.3; remove: 2.6.1
- [ ] https://github.com/stackabletech/docker-images/pull/562
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/airflow-operator/pull/387
```

```[tasklist]
### Druid: new: 28.0.1; deprecated: 27.0.0
- [ ] https://github.com/stackabletech/docker-images/pull/558
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/druid-operator/pull/518
```

```[tasklist]
### HBase: remove: 2.4.12
- [ ] https://github.com/stackabletech/docker-images/pull/567
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/hbase-operator/pull/454
```

```[tasklist]
### Kafka: new; 3.5.2, 3.6.1; deprecated: 3.5.1, 3.5.2; remove: 3.4.0
- [ ] https://github.com/stackabletech/docker-images/pull/559
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/kafka-operator/pull/664
```

```[tasklist]
### NiFi: new: 1.25.0; deprec.: 1.23.2
- [ ] https://github.com/stackabletech/docker-images/pull/552
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/nifi-operator/pull/571
```

```[tasklist]
### Spark: new: 3.4.2; depr.: 3.4.1; remove: 3.4.0
- [ ] https://github.com/stackabletech/docker-images/pull/560
- [ ] https://github.com/stackabletech/ny-tlc-report/pull/7
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/357
```

```[tasklist]
### Superset: new: 2.1.3, 3.0.3, 3.1.0; depr.: 2.1.1, 3.0.1, 3.0.3; rem.: 2.1.0
- [ ] https://github.com/stackabletech/docker-images/pull/563
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/superset-operator/pull/457
```

```[tasklist]
### Trino: new: 438 or latest; depr.: 428
- [ ] https://github.com/stackabletech/docker-images/pull/547
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/trino-operator/pull/536
```

```[tasklist]
### Trino: new: 439, remove 438 again
- [ ] https://github.com/stackabletech/docker-images/pull/570
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/trino-operator/pull/539
```

```[tasklist]
### ZooKeeper: new: 3.9.1; remove: 3.8.1
- [ ] https://github.com/stackabletech/docker-images/pull/551
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/771
```

```[tasklist]
### OPA: new: 0.61.0; depr.: 0.57.0
- [ ] https://github.com/stackabletech/docker-images/pull/538
- [x] nexus packages and docker images available
- [ ] https://github.com/stackabletech/opa-operator/pull/518
```

```[tasklist]
### Vector: new: 0.35.0; rem.: 0.33.0
- [x] docker-images PR
- [x] nexus packages and docker images available
- [x] operator-changes PR
```

**Comment by maltesander** [comment]
All done!
