### ISSUE TITLE
Support for custom labels in our operators

### ISSUE THREAD

**Issue by Techassi** [stackabletech/issues#503]
Follow-up of #188

When `stackablectl` (and in the future our Cockpit) deploys resources into a Kubernetes cluster, we and the user are currently unable to properly identify them afterwards. Adding a common set of labels to the resources we deploy will solve this issue.

```[tasklist]
### Tasks
- [ ] Improve existing ADR (https://docs.stackable.tech/home/nightly/contributor/adr/adr031-resource-labels). Also decide on how the user configures custom labels in our operators.
- [ ] Label operators deployed by `stackablectl` as part of a demo/stack with the demo/stack that they are part of
- [ ] Enable operators to label the resources that they deploy with completely custom labels (to be refined)
- [ ] Enable operators to label the resources that are part of a demo/stack to add the demo/stack label (requires the previous task)
```
