### ISSUE TITLE
OpenShift Initiative

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#511]
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/issues/issues/399
- [ ] Figure out how OLM op updates across OS versions work
- [ ] Run integration tests as developer instead of kubeadmin
- [ ] Port demos to OpenShift
- [ ] https://github.com/stackabletech/issues/issues/641
- [ ] Publish operators to the community catalog
- [ ] Publish operators to the marketplace catalog
- [ ] Publish to the RedHat software catalog (https://catalog.redhat.com/software/search)
- [ ] https://github.com/stackabletech/issues/issues/415
- [ ] https://github.com/stackabletech/issues/issues/562
- [ ] https://github.com/stackabletech/issues/issues/353
- [ ] https://github.com/stackabletech/issues/issues/432
```

For histroical reasons, this a list of issues that are now done:

* https://github.com/stackabletech/issues/issues/434
* https://github.com/stackabletech/issues/issues/484
* https://github.com/stackabletech/issues/issues/371
* https://github.com/stackabletech/issues/issues/561
* https://github.com/stackabletech/issues/issues/495
* https://github.com/stackabletech/issues/issues/571
* https://github.com/stackabletech/issues/issues/564
* https://github.com/stackabletech/issues/issues/575
* Clarify the RBAC rules and SCC requirements for running SDP on OpenShift: https://github.com/stackabletech/documentation/pull/646
* https://github.com/stackabletech/issues/issues/607
* https://github.com/stackabletech/issues/issues/624
