### ISSUE TITLE
Use syft to create SBOMs of product images and publish them in Harbor

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/issues#512]
```[tasklist]
### Tasks
- [x] Try to generate somewhat reasonable looking SBOMs using syft
- [x] Have a look at whether we can leverage SBOMs from the projects themselves (e.g. the ones published on Maven Repository)
- [x] Check SBOM contents and metadata, validate the schema
- [x] Add the commands to the Github Action (generate SBOM and attestation)
```

```[tasklist]
### Products
- [x] Airflow
- [x] Druid
- [x] HBase
- [x] Hadoop HDFS
- [x] Hive
- [x] Kafka
- [x] NiFi
- [x] Spark
- [x] Superset
- [x] Trino
- [x] ZooKeeper
- [x] OPA
```
