### ISSUE TITLE
Add Stackable vendor label to default values.yaml for Helm Charts

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#513]
As a user
I want to have the vendor label `stackable.tech/vendor: Stackable` on the operators I install with Helm
so I can see which of my operators are vendored by stackable.

This requires adjusting the values.yaml file in each Operator repo, to add the vendor label.

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/380
- [ ] https://github.com/stackabletech/druid-operator/pull/513
- [ ] https://github.com/stackabletech/hbase-operator/pull/444
- [ ] https://github.com/stackabletech/hdfs-operator/pull/464
- [ ] https://github.com/stackabletech/hive-operator/pull/408
- [ ] https://github.com/stackabletech/kafka-operator/pull/659
- [ ] https://github.com/stackabletech/nifi-operator/pull/566
- [ ] https://github.com/stackabletech/opa-operator/pull/511
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/346
- [ ] https://github.com/stackabletech/superset-operator/pull/452
- [ ] https://github.com/stackabletech/trino-operator/pull/530
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/767
- [ ] https://github.com/stackabletech/commons-operator/pull/208
- [ ] https://github.com/stackabletech/listener-operator/pull/145
- [ ] https://github.com/stackabletech/secret-operator/pull/359
- [ ] https://github.com/stackabletech/hello-world-operator/pull/50
- [ ] https://github.com/stackabletech/edc-operator/pull/51
```

**Comment by fhennig** [comment]
@sbernauer I think I approved them all

**Comment by sbernauer** [comment]
That would be awesome :)

**Comment by sbernauer** [comment]
It was intentional, just in case you approve and have a nitpick ;)
I think you missed airflow and spark-k8s

**Comment by fhennig** [comment]
@sbernauer I didn't have notifications for those repos (now I do) - it's all done now :partying_face:
