### ISSUE TITLE
Run integration tests for all products once with ARM

### ISSUE THREAD

**Issue by fhennig** [stackabletech/issues#519]
For all operators, run the integration tests on ARM.
If anything fails, it needs to be fixed.

```[tasklist]
### Products
- [x] Airflow
- [x] Druid ( fix needed: https://github.com/stackabletech/druid-operator/pull/581 ) ( up to cleanup step. PVC's deletion exceeded deadline )
- [x] HBase
- [x] Hadoop HDFS
- [x] Hive
- [x] Kafka
- [x] NiFi
- [x] Spark (fix needed: https://github.com/stackabletech/spark-k8s-operator/pull/423 )
- [x] Superset ( fails with 2.1.0, connection error to pg. Can not fix it now, works on amd64, look at comment for more info)
- [x] Trino
- [x] ZooKeeper
- [x] Commons
- [x] Listener
- [x] OPA
- [x] Secret
- [x] EDC ( omitted )
```
```[tasklist]
### Tasks
- [ ] Testing Release 23.11.0
- [ ] Testing Release 24.3.0
```

**Comment by Maleware** [comment]
Superset test results: 
```
--- FAIL: kuttl (2796.16s)                                                                                                                                                                 
    --- FAIL: kuttl/harness (0.00s)                                                                                                                                                        
        --- PASS: kuttl/harness/cluster-operation_superset-latest-3.1.0_openshift-false (194.56s)                                                                                          
        --- PASS: kuttl/harness/smoke_superset-3.1.0_openshift-false (126.73s)                                                                                                             
        --- FAIL: kuttl/harness/logging_superset-2.1.3_openshift-false (471.83s)                                                                                                           
        --- PASS: kuttl/harness/druid-connection_superset-3.1.0_openshift-false (197.91s)                                                                                                  
        --- PASS: kuttl/harness/druid-connection_superset-3.0.3_openshift-false (249.30s)                                                                                                  
        --- FAIL: kuttl/harness/druid-connection_superset-2.1.3_openshift-false (338.96s)                                                                                                  
        --- PASS: kuttl/harness/smoke_superset-3.0.3_openshift-false (128.77s)                                                                                                             
        --- FAIL: kuttl/harness/smoke_superset-2.1.3_openshift-false (336.62s)                                                                                                             
        --- PASS: kuttl/harness/logging_superset-3.1.0_openshift-false (159.68s)                                                                                                           
        --- PASS: kuttl/harness/ldap_superset-3.1.0_ldap-authentication-server-verification-tls_openshift-false (161.41s)                                                                  
        --- FAIL: kuttl/harness/ldap_superset-2.1.3_ldap-authentication-server-verification-tls_openshift-false (358.19s)                                                                  
        --- PASS: kuttl/harness/ldap_superset-3.1.0_ldap-authentication-no-tls_openshift-false (142.03s)                                                                                   
        --- PASS: kuttl/harness/ldap_superset-3.1.0_ldap-authentication-insecure-tls_openshift-false (138.95s)                                                                             
        --- PASS: kuttl/harness/ldap_superset-3.0.3_ldap-authentication-server-verification-tls_openshift-false (173.18s)                                                                  
        --- PASS: kuttl/harness/ldap_superset-3.0.3_ldap-authentication-no-tls_openshift-false (192.66s)                                                                                   
        --- PASS: kuttl/harness/ldap_superset-3.0.3_ldap-authentication-insecure-tls_openshift-false (146.40s)                                                                             
        --- PASS: kuttl/harness/logging_superset-3.0.3_openshift-false (95.08s)                                                                                                            
        --- PASS: kuttl/harness/oidc_superset-3.0.3_openshift-false (251.52s)
        --- PASS: kuttl/harness/oidc_superset-3.1.0_openshift-false (225.45s)                                                                                                              
        --- FAIL: kuttl/harness/oidc_superset-2.1.3_openshift-false (398.15s)                                                                                                              
        --- FAIL: kuttl/harness/ldap_superset-2.1.3_ldap-authentication-no-tls_openshift-false (367.05s)
        --- PASS: kuttl/harness/resources_superset-latest-3.1.0_openshift-false (67.23s)                                                                                                   
        --- FAIL: kuttl/harness/ldap_superset-2.1.3_ldap-authentication-insecure-tls_openshift-false 
```

Fails with:
```
superset 2024-07-02 07:58:16,211:ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```

Can't be fixed at this moment.

**Comment by Maleware** [comment]
All tests passed on `arm64`

**Comment by NickLarsenNZ** [comment]
@Maleware can this be closed now?

**Comment by soenkeliebau** [comment]
spoke with @Maleware and he confirmed that this can be closed.
