### ISSUE TITLE
Write a RegoRule set for HDFS

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#523]
As a user of the SDP I want to have a robust Rego rule library that I can use to define my policies.

_For now_ it's fine to first have these rules _somewhere_, because we're not yet sure how they should be deployed. It probably makes sense to have them in a kuttl test for now.

```[tasklist]
### Tasks
- [x] Create a ruleset with RegoRules for HDFS, for a usage scenario. This should be done in pure Rego and commited into the operator repository. Tests should be used to simulate authorizer requests.
- [x] document findings about how the model works, what its quirks are etc. in the knowledge base: https://app.nuclino.com/Stackable/Engineering/Authorization-Mechanisms-across-platform-products-210a0804-4f2c-44de-afa8-5be65553967d
- [x] Think about regex support https://github.com/stackabletech/hdfs-utils/pull/11
- [x] Think about special handling for /tmp - We decided to not do that for now https://stackable-workspace.slack.com/archives/C031A56R127/p1710415621344699
- [ ] https://github.com/stackabletech/hdfs-operator/pull/510
- [x] Update the rules in the end-to-end-security stack
```

## Acceptance criteria

- There is a branch in the operator repository with the ruleset and tests that simulate the authorizer requests. Put in a kuttl test.
- There is a knowledge base article about how the HDFS OPA authorizer works and what its authorization model is. The article should also show some edge case operations like renaming a table that requires two resource permissions (source and target)

**Comment by sbernauer** [comment]
Everything is done, kuttl tests and end-to-end-security stack is updated :)

**Comment by lfrancke** [comment]
What is the visible outcome of this?

**Comment by lfrancke** [comment]
Can you then please just insert a link to the rego rules or the directory they live in?

**Comment by maltesander** [comment]
Think its here https://github.com/stackabletech/hdfs-utils/tree/main/rego

**Comment by lfrancke** [comment]
Thank you!
