### ISSUE TITLE
Update built crate to fix RUSTSEC-2024-0013

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#526]
We use the built crate, which pulls in libgit2 which has a vulnerability against it - issue details can be found at the bottom.

The fix is to simply update built to the latest version.

Affected products

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/hdfs-operator/issues/473
- [ ] https://github.com/stackabletech/edc-operator/issues/55
- [ ] https://github.com/stackabletech/airflow-operator/issues/386
- [ ] https://github.com/stackabletech/hello-world-operator/issues/54
- [ ] https://github.com/stackabletech/hbase-operator/issues/451
- [ ] https://github.com/stackabletech/hive-operator/issues/413
- [ ] https://github.com/stackabletech/zookeeper-operator/issues/772
- [ ] https://github.com/stackabletech/spark-k8s-operator/issues/353
- [ ] https://github.com/stackabletech/superset-operator/issues/456
- [ ] https://github.com/stackabletech/trino-operator/issues/537
- [ ] https://github.com/stackabletech/kafka-operator/issues/663
- [ ] https://github.com/stackabletech/nifi-operator/issues/572
- [ ] https://github.com/stackabletech/listener-operator/issues/149
- [ ] https://github.com/stackabletech/opa-operator/issues/520
- [ ] https://github.com/stackabletech/commons-operator/issues/212
```

Issue Details: 

> Memory corruption, denial of service, and arbitrary code execution in libgit2

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Package             | `libgit2-sys`                      |
| Version             | `0.15.2+1.6.4`                   |
| URL                 | [https://github.com/rust-lang/git2-rs/pull/1017](https://github.com/rust-lang/git2-rs/pull/1017) |
| Date                | 2024-02-06                         |
| Patched versions    | `>=0.16.2`                  |

The [libgit2](https://github.com/libgit2/libgit2/) project fixed three security issues in the 1.7.2 release. These issues are:

* The `git_revparse_single` function can potentially enter an infinite loop on a well-crafted input, potentially causing a Denial of Service. This function is exposed in the `git2` crate via the [`Repository::revparse_single`](https://docs.rs/git2/latest/git2/struct.Repository.html#method.revparse_single) method.
* The `git_index_add` function may cause heap corruption and possibly lead to arbitrary code execution. This function is exposed in the `git2` crate via the [`Index::add`](https://docs.rs/git2/latest/git2/struct.Index.html#method.add) method.
* The smart transport negotiation may experience an out-of-bounds read when a remote server did not advertise capabilities.

The `libgit2-sys` crate bundles libgit2, or optionally links to a system libgit2 library. In either case, versions of the libgit2 library less than 1.7.2 are vulnerable. The 0.16.2 release of `libgit2-sys` bundles the fixed version of 1.7.2, and requires a system libgit2 version of at least 1.7.2.

It is recommended that all users upgrade.

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2024-0013.html) for additional details.

**Comment by soenkeliebau** [comment]
I'll close this issue as there is nothing else to do for now. 

I'll move https://github.com/lukaslueg/built/issues/62 onto the board in the "track" column and once there is movement on it, we can consider updating.
