### ISSUE TITLE
Verify and fix overrides in all operators

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#548]
## Issue checklist

Verify (and fix if necessary) that property overrides (env, conf) work as intended in all operators.

There have been reports that this is not the case. Examples:

* https://github.com/stackabletech/hdfs-operator/issues/497
* https://github.com/stackabletech/trino-operator/pull/556

This issue tracks the state of this feature across all operators:

- [x] airflow-operator. See e.g. https://github.com/stackabletech/airflow-operator/issues/453 (https://github.com/stackabletech/airflow-operator/pull/490)
- [x] commons-operator -> not using overrides
- [x] druid-operator (https://github.com/stackabletech/druid-operator/pull/615)
- [x] edc-operator @xeniape (https://github.com/stackabletech/edc-operator/pull/120)
- [x] hbase-operator @adwk67 https://github.com/stackabletech/hbase-operator/pull/550 https://github.com/stackabletech/hbase-operator/pull/552
- [x] hdfs-operator @razvan https://github.com/stackabletech/hdfs-operator/pull/576 https://github.com/stackabletech/hdfs-operator/pull/577
- [x] hello-world-operator @razvan https://github.com/stackabletech/hello-world-operator/pull/114
- [x] hive-operator @razvan https://github.com/stackabletech/hive-operator/pull/507
- [x] kafka-operator @razvan (check that configOverrides works at role level as well as role-group level) https://github.com/stackabletech/kafka-operator/pull/752
- [x] listener-operator -> not using overrides
- [x] nifi-operator @razvan https://github.com/stackabletech/nifi-operator/pull/669
- [x] opa-operator @razvan -> not using overrides
- [x] secret-operator -> not using overrides
- [x] spark-k8s-operator @adwk67 See https://github.com/stackabletech/spark-k8s-operator/pull/451, https://github.com/stackabletech/spark-k8s-operator/pull/455
- [x] superset-operator @razvan https://github.com/stackabletech/superset-operator/pull/531
- [x] trino-operator @razvan  https://github.com/stackabletech/trino-operator/pull/633
- [x] zookeeper-operator @razvan https://github.com/stackabletech/zookeeper-operator/pull/855

```[tasklist]
### Tasks
- [x] Rust tests added (if possible) - similar to https://github.com/stackabletech/trino-operator/pull/556
- [x] Decision regarding property overrides https://github.com/stackabletech/decisions/issues/22
- [x] https://github.com/stackabletech/operator-rs/pull/841
- [x] Bump `stackable-operator` version in operators to `0.74.0`
```

**Comment by lfrancke** [comment]
Can you please include a snippet that we can use for the release notes later?

e.g. (the table is hard to read)

- fix: config overrides were not always honored in X, Y and Z, they now are

**Comment by razvan** [comment]
Here is a snippet that demonstrates how environment and configuration overrides work for Apache Zookeeper:

```
spec:
  servers:
    envOverrides:
      COMMON_VAR: role-value # overridden by role group below
      ROLE_VAR: role-value   # only defined here at role level
    configOverrides:
      zoo.cfg:
        prop.common: role
        prop.role: role
    roleGroups:
      primary:
        replicas: 2
        config:
          myidOffset: 10
        envOverrides:
          COMMON_VAR: group-value # overrides role value
          GROUP_VAR: group-value # only defined here at group level
        configOverrides:
          zoo.cfg:
            prop.common: group
            prop.group: group 
```

This example is fictional because the properties written to the `zoo.cfg` file are not used by Zookeeper in any way.

What ends up being written in the Pod's environment are the variables:

```
COMMON_VAR=group-value
ROLE_VAR=role-value
GROUP_VAR=group-value
```

Similarly, the `zoo.cfg `file of the `primary` group will contain:

```
prop.common=group
prop.role=role
prop.group=group 
```

Of course, these are not the only settings that the operator will configure.

**Comment by lfrancke** [comment]
Thank you, that is useful but not really all that usually goes into the release notes.
We'd need a sentence on what has been changed/fixed and this could then go in there in addition to that.

**Comment by lfrancke** [comment]
The tests are not really release notes material. If I were to read release notes I'd be interested in knowing which operators were actually fixed.
It's a bit hard to see from the list above, can you give me the list of operators that had bugs before but are fixed in 24.11?

**Comment by razvan** [comment]
>It's a bit hard to see from the list above, can you give me the list of operators that had bugs before but are fixed in 24.11?

Yes, it's not easy for me either. Luckily we used conventional commit messages so I'm pretty sure it was:

* Trino
* Spark
* Hbase
* Airflow
