### ISSUE TITLE
build process in https://github.com/stackabletech/docker-images/ is updated to build for ARM as well (Using BuildJet)

### ISSUE THREAD

**Issue by Maleware** [stackabletech/issues#552]
```[tasklist]
### Tasks
- [x] Pipeline dev.yaml is using buildjet to build multiarchitecture using manifest lists => https://github.com/stackabletech/docker-images/pull/614
- [x] Pipeline release.yaml is using buildjet to build multiarchitecture using manifest lists (with caution because of 24.3)
- [x] ~Failing Products are documented and tickets to fix the product are in place (might already be)~ We have no failing products anymore :)
```

**Comment by Maleware** [comment]
https://github.com/stackabletech/docker-images/pull/616

Will resolve the last step of this
