### ISSUE TITLE
Release 24.7

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#557]
# Stackable Release 24.7

> [!IMPORTANT]
> Important dates:
> - 17th June - Release planning.
> - Plan to do the busy work (pre-release testing) during the on-site.
> - Set patch versions 2 weeks before.
> - 23rd for beginning the release

## Known issues
- Secret `secret-provisioner-tls-ca` needs to move to the `stackable-operators` namespace (see issue in stretch goals).

## Release checklists

```[tasklist]
### General pre-requisites (before feature freeze)
- [x] **2024-07-08 to 2024-07-12**
- [ ] https://github.com/stackabletech/issues/issues/594
- [ ] https://github.com/stackabletech/issues/issues/519
- [ ] https://github.com/stackabletech/operator-templating/pull/406
- [ ] https://github.com/stackabletech/operator-rs/pull/822
- [ ] https://github.com/stackabletech/operator-rs/pull/823
- [ ] https://github.com/stackabletech/issues/issues/601
- [x] **2024-07-15 to 2024-07-19**
- [ ] https://github.com/stackabletech/issues/issues/603
- [ ] https://github.com/stackabletech/demos/pull/57
- [ ] https://github.com/stackabletech/issues/issues/608
- [ ] https://github.com/stackabletech/demos/pull/59
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/307
- [ ] https://github.com/stackabletech/opa-operator/pull/557
- [ ] https://github.com/stackabletech/airflow-operator/pull/474
- [ ] https://github.com/stackabletech/documentation/pull/629
```

```[tasklist]
### Other release-specific pre-requisites
- [ ] https://github.com/stackabletech/druid-operator/pull/590
- [x] Stretch goal https://github.com/stackabletech/secret-operator/issues/453
```

### Feature freeze

This will not be so crucial with release branches, but is nonetheless sensible as it will make it easier to cherry-pick any release-related bugfixes from main into the release branch.

### End of the release cycle (Release day)

```[tasklist]
#### Technical tasks
- [x] Create release branches for docker-images (see stackable-utils for script to create branches)
- [x] Create release tag(s) for docker-images (see stackable-utils for scripts to create tags)
- [x] Create release branches for operators (see stackable-utils for script to create branches)
- [x] Create release tag(s) for operators (see stackable-utils for scripts to create tags)
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/309
- [x] Update changelogs in main branches (see stackable-utils for script to do this)
- [ ] https://github.com/stackabletech/crddocs/pull/38
- [ ] https://github.com/stackabletech/release/pull/30
- [ ] https://github.com/stackabletech/issues/issues/613
- [ ] https://github.com/stackabletech/demos/issues/65
- [x] Test with locally updated (to new release number) `releases.yaml`
- [x] Check that an upgrade can be performed on an existing cluster without data loss.
```

```[tasklist]
#### Documentation tasks
- [ ] https://github.com/stackabletech/documentation/pull/631
- [x] Check the Changelog and/or issue labels to compile Release Highlights
- [x] Upgrade guide: Document how to use stackablectl to uninstall all and install new release
- [x] Upgrade guide: Document how to use helm to uninstall all and install new release
- [x] Upgrade guide: Every breaking change of all our operators
- [x] Upgrade guide: List dropped supported product versions (if there are some)
- [x] ~Upgrade guide: List dropped supported operators (if there are some)~
- [x] Upgrade guide: List supported k8s versions
- [ ] https://github.com/stackabletech/documentation/pull/633
- [x] Run release scripts for documentation https://github.com/stackabletech/documentation/pull/635/
- [x] Set the release to "Released" in the Feature Tracker and create a new release
- [x] Document breaking changes of JVM metrics https://github.com/prometheus/jmx_exporter/releases/tag/1.0.1
- [x] Document Superset 2.1.3 is not supported on ARM because of Postgres version problems (ask Maxi)
- [ ] https://github.com/stackabletech/documentation/issues/637
```

Marketing tasks can now reference published documentation.

```[tasklist]
#### Marketing tasks
- [x] Write marketing / customer oriented release summary to be published in the marketing channels
- [x] Update the homepage banner (as long as we have it) to point to the new release
- [x] Write a blogpost / news article announcing the new release (optional)
- [x] Write a description of new demos for homepage/demos section
- [x] ~~Announce Release in Newsletter (optional)~~
- [x] ~~Produce a release highlight video (optional)~~
- [x] ~~Announce Release on Hacker News (optional)~~
- [x] Post an announcement in the GitHub [Discussions Announcement forum](https://github.com/stackabletech/community/discussions/categories/announcements) and make it a pinned discussion while at the same time removing the old pinned thread
- [x] Post an announcement in Discord
- [x] ~~Post an announcement on DOK Community in the #be-shameless Channel (Ping Lars or Jim)~~
- [x] ~~Post an announcement via OSBA (Ping Lars)~~
- [x] ~~Send announcement to Kubernetes Podcast (Ping Lars)~~
- [x] ~~Send announcement to Heise~~
- [x] Ping the stackable-ionos-tech channel or anyone responsible once all tags are created
```

```[tasklist]
### Post-release tasks
- [x] Update the list of supported SDP versions in Jira @jimvin
- [x] Bump Rust version. This can be done [in this file](https://github.com/stackabletech/operator-templating/blob/main/config/rust.yaml) by changing `rust_version` and also for the ubi base image [here](https://github.com/stackabletech/docker-images/blob/main/ubi8-rust-builder/Dockerfile#L25). Please be aware that this action will change it for all repositories at the same time (when merging the templating PRs).
- [x] Check/bump versions of kube-rs and k8s-openapi (also checking the version of k8s we build against)
- [x] Check/bump ubi8 base image
- [ ] https://github.com/stackabletech/issues/issues/631
- [ ] https://github.com/stackabletech/issues/issues/625
- [x] Define product versions to include in the next release
- [ ] ~Add branch protection to release branches once they are stable~ https://github.com/stackabletech/stackable-utils/issues/81
- [ ] https://github.com/stackabletech/issues/issues/615
```

**Comment by sbernauer** [comment]
We can close this issue, with an follow-up being a Release retro, which @NickLarsenNZ will ping Lars when he's back
