### ISSUE TITLE
Improve experience for users of the log aggregation feature

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#574]
## Description

We had some issues in the past with customers running into limitations with the size of our logging volumes causing Pods to be killed because `Usage of EmptyDir volume "log" exceeds the limit`.
This issue is about fixing the underlying issue and documenting the behavior and how users can modify settings themselves if needed.

## Value

We want this feature so that Pods do not crash arbitrarily under normal circumstances especially when the load is high and lots of logs are produced. This will lead to fewer support cases for us.
         
## Dependencies

- I (@lfrancke) am unsure about the exact dependencies but I assume this will require changes to the documentation as well as a change in operator-rs.
- Depending on the exact implementation it might also require changes to each operator

## Tasks

```[tasklist]
- [x] Agree on a new default size for log volumes
- [x] Investigate whether we want to lower the [`checkIncrement`](https://logback.qos.ch/manual/appenders.html#checkIncrement) setting (and equivalent for other logging implementations)
- [x] Potentially implement the changes from the investigation
- [x] Document what customers need to change if they still run into problems, clearly containing the error message
- [ ] https://github.com/stackabletech/operator-rs/pull/853
- [ ] https://github.com/stackabletech/nifi-operator/pull/671
```

## Acceptance Criteria

- Users can search our documentation for the above mentioned error and will find a page/section telling them where it's coming from and how to solve it
- NiFi (and other tools) will fail less under load due to log volume size restrictions

## (Information Security) Risk Assessment
      
I can not identify any additional significant risks this would introduce.
Should we increase the default volume size for logs it'd require more resources from customers, risking resource constraints.

### Quality

- This should be tested by getting one of our tools to emit a lot of log statements in a short amount of time (this could be done by e.g. increasing the log level of anything to TRACE) making sure it doesn't fail under these "normal" high load conditions
  - As this was originally reported for NiFi that'd be a good candidate

## Release Notes

_Draft as it's not implemented yet_

The ephemeral `EmptyDir` volumes used to store log files before being aggregated have their size increased from a default of X to X.
While logs are rolled by our tools they only do check so often and if a system is under high load the logs might actually grow beyond the bounds of the container causing an error: `Usage of EmptyDir volume "log" exceeds the limit`
This change will not prevent this from ever happening again but it'll decrease the likelihood.
We have also documented(LINK) this behavior and how to adjust the size of the volumes if needed.

##  Remarks

See our internal Slack discussion for more details: https://stackable-workspace.slack.com/archives/C031NP72H7T/p1710514724269639

**Comment by labrenbe** [comment]
The issue seems to be caused by Logback (NiFi and Zookeeper) which is the only logging framework used us that only periodically checks the log file size. Log4j1, Log4j2 and Trino's Airlift always check the file size before adding a new line and roll over if the file would become to large.

Log4j1: https://github.com/apache/logging-log4j1/blob/v1_2_17/src/main/java/org/apache/log4j/RollingFileAppender.java#L279
Log4j2: https://github.com/apache/logging-log4j2/blob/2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/appender/rolling/RollingFileManager.java#L401
Logback: https://github.com/qos-ch/logback/blob/v_1.5.7/logback-core/src/main/java/ch/qos/logback/core/rolling/SizeBasedTriggeringPolicy.java#L59
Airlift: https://github.com/airlift/airlift/blob/262/log-manager/src/main/java/io/airlift/log/RollingFileMessageOutput.java#L229

**Comment by sbernauer** [comment]
@labrenbe you requested review from @siegfriedweber, would it be ok to assign him and move this to in Review to not bother others?

**Comment by lfrancke** [comment]
Are there any docs for this and could you write a short snippet to be used for release notes?
It should not be more than one or two sentences possibly linking to more docs
