### ISSUE TITLE
Check if any documentation refers to UBI8 and update it

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#585]
```[tasklist]
### Tasks
- [x] Check if we refer to UBI anywhere in our docs and update any references.
- [x] Check the READMEs of our operators (in operator-templating?)
- [x] Check README of docker-images repository
- [ ] https://github.com/stackabletech/documentation/pull/612
- [ ] https://github.com/stackabletech/docker-images/pull/693
```

If we find a reference to "UBI 8" we need to update it.
Ideally to something that works without a version.

**Comment by lfrancke** [comment]
Done, thank you!
