### ISSUE TITLE
Make TLS certificate lifetime configurable using the CRD

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#586]
## Description

Relevant decision: https://github.com/stackabletech/issues/issues/673

As a user of SDP I want to be able to configure the lifetime of generated certificates (by the secret operator) from within the custom resources itself without having to use any podOverrides.  

## Value

We want this to reduce the documentation and support overhead this causes.
Multiple customers have asked how to change the lifetime of certificates and we've had to provide custom override snippets.
This will make it easier for us and for our users.
Lifetimes should use a human-readable duration format like [`stackable_operator::time::Duration`](https://github.com/stackabletech/operator-rs/blob/4127d8dc6e235f27d60e8402e44fee4159ce4085/crates/stackable-operator/src/time/duration.rs#L67), which also closely resembles the Go / K8s format.
         
## Dependencies

This will require a CRD change which needs to be discussed and voted on before it can be implemented.
    
## Tasks

```[tasklist]
- [x] Brainstorm/Design CRD solution and vote on it
- [x] Implement required changes across all operators that support TLS including handling minimum and maximum lifetimes
- [x] Add a documentation concept page explaining the change => https://github.com/stackabletech/documentation/pull/689
- [x] Remove any documentation refering to the old way of configuring this using podOverrides. First PR: https://github.com/stackabletech/trino-operator/pull/681
- [x] Close https://github.com/stackabletech/secret-operator/issues/353
```

TODO: Amend the tasklist with a list of all operators needing this CRD change.

## Acceptance Criteria

- Users have a way of configuring TLS certificate lifetime without resorting to podOverrides
  
## (Information Security) Risk Assessment

While this does touch TLS which in itself is a security mechanism in most cases all it does is to simplify a setting that can already be set using podOverrides.

By making it easier to increase the default lifetime we potentially decrease the security of the product and this needs to be mentioned in the documentation page.

## Release Notes

Certificates automatically generated by our secret-operator default to a lifetime of one day plus/minus a bit of jitter (TODO: Is this correct?). This does lead to automatic restarts of pods when the certificates are regenerated which can lead to brief service interruptions or a brief performance hit during these restarts. Some customers have therefore asked for ways to increase the lifetime of these certiifcates. This was always possible using `podOverrides` and in this release we have made it easier by adding a dedicated field to the CRDs of our X and X (TODO) operators called `TODO` which allows specifying the lifetime in a more convenient way. We have also updated the documentation(LINK, TODO).

**Comment by razvan** [comment]
| Operator  | Certificate usage analysis                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Decision |
| --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------- |
| airflow   | Uses TLS only for OIDC and LDAP authentication.                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| druid     | - DruidClusterConfig::tls field is a DruidTls struct whth only one field server_and_internal_secret_class<br>- DuidClusterConfig::authentication -> uses the same SecretClass as the tls field above. This is a list of providers (ldap, oidc) that may also refer to a SecretClass::Tls<br>- DruidClusterConfig::ingestion -> s3connection which needs a mount point for a client cert<br>- DruidAuthenticationConfig enum has oidc and ldap variants that reference a secret class |          |
| hdfs      | - ClusterConfig::authentication for the web UIs may use TLS cert.                                                                                                                                                                                                                                                                                                                                                                                                                    |          |
| hello     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| hive      | - Tls certs only used for S3 connection. No changes seem necessary here.                                                                                                                                                                                                                                                                                                                                                                                                             |          |
| kafka     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| listener  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| nifi      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| opa       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| secret    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| spark     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| superset  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| trino     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
| zookeeper |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |
|           |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |          |

**Comment by sbernauer** [comment]
I think I would be in favor of adding this to a global struct in operator-rs and have this on every operator (every if it's *currently* not used) for consistency reasons. Ideally this is also on a commons struct we can pass around, e.g. on the `Client`, so we don't end up with the 11th struct being passed around all operator functions arguments.

Btw, until we get behind https://github.com/stackabletech/secret-operator/issues/320 this flag should control **all** secret-op TLS volumes (so also for TLS clients), reason being that the motivation behind this issue are too frequent Pod restarts.

**Comment by razvan** [comment]
> I think I would be in favor of adding this to a global struct in operator-rs and have this on every operator (every if it's _currently_ not used) for consistency reasons. 

Sounds sensible but I also think think there are corner cases where this redundancy will cause confusion. One example is Druid and it's authentication methods.

IMO the more interesting questions are backwards compatibility and how to handle authentication classes.

**Comment by sbernauer** [comment]
I think I would consider this attribute (something like `.spec.clusterConfig.tlsFoo`) as "all TLS certs you mount should have the lifetime x".
Regardless if it is used to secure the https server, LDAP ca cert, S3 ca cert or OIDC ca cert

**Comment by razvan** [comment]
# Operators

Decision #673 implementation status.

- [ ] airflow
- [ ] commons
- [ ] druid
- [ ] edc
- [ ] hbase
- [ ] hdfs
- [ ] hello
- [ ] hive
- [ ] kafka
- [ ] listener
- [ ] nifi
- [ ] opa
- [ ] secret
- [ ] spark
- [ ] superset
- [ ] trino
- [ ] zookeeper

**Comment by razvan** [comment]
Snippet for the release notes:

> Users can now configure the lifetime of self signed certificates directly in the product's custom resources.
> A new field `requestedSecretLifetime` can be added to the role or group level of each product role.
> The value  is a string defining a duration such as  `24h' for a day or `7d` for a week.
> The specified lifetime is constrained by the `maxCertificateLifetime` field of the corresponding `SecretClass`.

**Comment by razvan** [comment]
PR for documentation: https://github.com/stackabletech/documentation/pull/688

**Comment by lfrancke** [comment]
Will this be in 24.11.1? It's a new feature so I guess it shouldn't but I'm not sure if we're set up with release branches?

I obviously have the same question about all of the other products as well.

**Comment by sbernauer** [comment]
Nope, this is only part of 25.3.x

**Comment by razvan** [comment]
Release notes:
```
Users can now configure the lifetime of self-signed certificates directly
in the product's custom resources which influences the frequency of pod restarts.
Details can be found at xref:concepts:operations/temporary_credentials_lifetime.adoc[]
```
