### ISSUE TITLE
Publish CSAF continuously as feed

### ISSUE THREAD

**Issue by dervoeti** [stackabletech/issues#592]
```[tasklist]
### Tasks
- [x] Create Github Action to publish a CSAF document for specific vulnerabilities
- [x] Sign and hash CSAF documents
- [x] Add legal disclaimer to CSAF documents
- [x] Add security contact
- [x] Get the document and file structure verified
```

**Comment by dervoeti** [comment]
Mostly done, waiting for review from our contacts at BSI, they might find some more things to improve.

**Comment by dervoeti** [comment]
Got a list of things to fix / improve, I'm working on it, will be reviewed again by the end of next week

**Comment by dervoeti** [comment]
Feedback is implemented, CSAF VEX statements will be published here: https://advisories.stackable.tech/ via a [Github Action](https://github.com/stackabletech/advisories/actions/workflows/publish_advisory.yaml).
