### ISSUE TITLE
Instrument operators and allow OpenTelemetry OTLP exporters to be used

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#598]
## Description

> [!NOTE]
> This is Part 2, moved here from the original epic: https://github.com/stackabletech/issues/issues/531

## Value
         

For both developers of the operators and the end users of the operators, trace data can be invaluable when trying to understand what the application is doing. More-so when the data comes from multiple systems and shares trace context data (distributed tracing).

Some of the immediate points of value are:
- Simplify tracing and telemetry initialization and provider shutdown
- Switch from the deprecated Jaeger trace exporter to OTLP which opens up the options for trace receivers (eg: opentelemetry-collector, Grafana Tempo, Observability SaaS offerings).

## Dependencies
    

Operators will pull in [stackable-telemetry](https://github.com/stackabletech/operator-rs/tree/main/crates/stackable-telemetry) as a dependency.

## Tasks

```[tasklist]
### Tasks
- [ ] Instrument all `stackable-operator::logging::initialize_logging`
- [ ] Add Clap arguments for enabling/disabling logging/tracing
- [ ] Add Helm values to aid in enabling/disabling logging/tracing
- [ ] Initialise operators with `stackable-telemetry::Tracing`
- [ ] Instrument functions and record Semantic Convention + useful attributes on spans
- [ ] Make a demo, using the Stack (jaeger + otel-collector and enrichment with k8s metadata)
- [ ] Allow Otel Exporter enabling/config for operators installed via stackablectl
```

## Acceptance Criteria
  

- [ ] Uses the stackable-telemetry crate.
- [ ] Logging/Tracing config is configurable through environment vars and Helm values and stackablectl.
- [ ] Reconciliation traces visible in a UI (eg: Jaeger/Tempo).

## Accessibility Assessment

Unknown

## Quality
          
   

Unknown

## Release Notes
                     

Instrument operators and add OpenTelemetry OTLP exporters for logs and traces.
