### ISSUE TITLE
Run/check getting-started scripts

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#603]
For each operator with a `getting_started.sh` script, run the following:

```sh
# Some of the scripts are in a code/ subdirectory
# pushd docs/modules/superset/examples/getting_started
# pushd docs/modules/superset/examples/getting_started/code
pushd $(fd -td getting_started | grep examples); cd code 2>/dev/null || true

# Make a fresh cluster (~12 seconds)
kind delete cluster && kind create cluster
./getting_started.sh stackablectl

# Make a fresh cluster (~12 seconds)
kind delete cluster && kind create cluster
./getting_started.sh helm

popd
```

Add the following checklist to the PRs:

~~~
```[tasklist]
### Run getting_started.sh via
- [ ] `stackablectl`
- [ ] `helm`
```
~~~

```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/airflow-operator/pull/466
- [ ] https://github.com/stackabletech/druid-operator/pull/589
- [ ] https://github.com/stackabletech/hbase-operator/pull/528
- [ ] https://github.com/stackabletech/hdfs-operator/pull/553
- [ ] https://github.com/stackabletech/hive-operator/pull/489
- [ ] https://github.com/stackabletech/kafka-operator/pull/732
- [ ] https://github.com/stackabletech/nifi-operator/pull/646
- [ ] https://github.com/stackabletech/opa-operator/pull/601
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/432
- [ ] https://github.com/stackabletech/superset-operator/pull/515
- [ ] https://github.com/stackabletech/trino-operator/pull/616
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/838
```

> [!IMPORTANT]
> kafka-operator requires kafkacat (kcat in nix)

> [!NOTE]
> The list above was generated by:
> ```sh
> # cd to directory where you store the stackabletech repos locally
> find -name 'getting_started.sh' -not -path './operator-templating/*' \
> | cut -d/ -f2 \
> | sort \
> | sed 's/^/- [ ] /'
> ```

If you want to reuse a cluster, you can delete everything by doing:

```sh
# Delete Stackable Custom Resources
kubectl get crds | grep stackable | cut -d' ' -f1 | xargs -I {} kubectl -n default delete {} --all

# Delete well-known Kubernetes Resources in the default namespace
kubectl -n default delete all --all --grace-period 0

# Delete the operators
stackablectl release uninstall dev

# delete the Stackable Custom Resource Definitions
kubectl get crds | grep stackable | cut -d' ' -f1 | xargs -I {} kubectl delete crd {}

# You might need to check on any Helm releases
helm list
helm uninstall ...
```

**Comment by NickLarsenNZ** [comment]
Earlier in the process I was fixing as many lint issues as I could (even for files that weren't touched). But from now (kafka-operator), I will only fix what is required to speed up the process.
