### ISSUE TITLE
Metrics, Monitoring - Milestones 1 & 2

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#61]
We want to introduce Monitoring & Metrics in our stack.

The way we plan on doing this is to integrate with existing technology.
For metrics we want to offer a common view to the outside world and the technology/standard we decided on is the OpenMetrics standard which builds upon the Prometheus Exposition Format.
This means that we want to enable Prometheus endpoints where they are available in our projects.
Where it's not available we'll have to provide a translation layer which will often consist of a JMX Exporter.

## Architecture

Our idea is to have a single VictoriaMetrics (or Cortex/Thanos, need to investigate) per physical server which collects metrics from processes running on the same server.
This allows us to collect stats even when the network is down or the remaining monitoring stack is down for some reason.

We need to discuss how this would/should work in a Kubernetes native scenario. A sidecar Victoria per process seems like overkill. A DaemonSet might work but also has its challenges (one being, and I might be wrong here, that the Pods can't access "localhost" easily).

These VictoriaMetrics daemons can then be queried by a central Prometheus (or compatible) instance using the Federation functionality from VictoriaMetrics.
Alternatively they can query all the daemons directly from Grafana but then we'd probably need to deploy https://github.com/jacksontj/promxy or similar.

## Service Discovery

For pull based monitoring to work the tools doing the monitoring need to know about all services they should pull from.
Victoria and the others support a wide variety of sources (e.g. Consul, Kubernetes, HTTP, ...). We need to decide on one of those and implement it.

## Packaging

For some of our projects this approach means that we'll have to package additional tooling/software in our builds.

## Web UIs

Some products have web UIs that expose metric data. This generally comes in three forms:
- HTML pages (for the end user)
- JMX JSON dumps
- Prometheus endpoints

These _can_ serve as sources for our metrics but we need to be wary because those web UIs usually serve multiple purposes.
Most also expose some HTML views, diagnostic data, logs, config, etc. and most of these web UIs can be disabled by the user and users sometimes do this to expose as little information as possible. Some web UIs also contained bugs in the past and so on.

Long story short: It might be worth relying on other sources for our metrics if they are available because we can expose only what we need there and if a user opts to disable JMX well then he/she knows what they are doing while it's not obvious that our monitoring relies on web UIs (which could also be secured for example in which case our monitoring might need Kerberos tickets or similar credentials).

## JMX

We looked at Jolokia, jmxtrans and JMX Exporter and ruled out all but the last.
- Jolokia does not offer a Prometheus compatible API
- jmxtrans can push data but also not Prometheus compatible
- JMX Exporter works fine but does not support TLS, it's still the best we found.
   - Requires a rule configuration file per product.  Rules are used for two purposes: to limit the amount of metrics exposed and to translate JMX MBean names into Prometheus compatible metric names.
   - Requires (and this might be a big disadvantage) a static TCP port per JVM. 

## Victoria Metrics

Can scrape metrics from various sources.

### Scraping with static_config

See [static_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config)

Disadvantages:
- Scrape targets are configured in a file. This file would need to be updated automatically every time a pod changes it's status.

## Node metrics

We also want to offer a way to collect metrics from the underlying hosts themselves.
There are a couple of options:
- Prometheus Node Exporter
- Netdata
- Telegraf
... probably others

## Dashboards

We don't want to provide our own dashboarding solution but we do want to provide pre-configured dashboards for Grafana (and potentially other tools if there are other candidates).
This part might be relatively simple but we need to investigate how generic these dashboards can be made (e.g. no reference to servers etc.).

## Alerting

Alerting will be part of a different Epic.

## CR status / Health checks / Readiness checks

We would like to expose some basic health information in our custom resource statuses as well.
This does not need to be a full monitoring solution but should give an overview over the general health of the system (red, green, yellow,...)
We will probably need this anyway

## Product specifics

There is a good chance that we might want to provide product specific additions to collect stats that are not exposed via JMX etc.
This could be the case for Kafka for example.
See Kafka Exporter or KMinion.

## Log collection

Log collection is handled as part of #75

## Pushing metrics

There are two ways to push metrics into Prometheus or VictoriaMetrics. In both cases, the entity where the metrics are pushed must be configured as a scrape target by the actual metric aggregator. Unfortunately none of them seem to be a viable solution for our usecase for various reasons which are described below.

### [Prometheus Node Exporter](https://github.com/prometheus/node_exporter)

In addition to collecting hardware metrics, the node exporter can collect metrics from text files using the [textfile collector](https://github.com/prometheus/node_exporter#textfile-collector). We could then configure the JMXTrans [rolling file writer](https://github.com/jmxtrans/jmxtrans-agent) to write these metric files.

Unfortunately, for some unknown reason this collector ignores metric timestamps so it's largely unusable. See note [here](https://github.com/prometheus/node_exporter#textfile-collector)

### [Prometheus Push Gateway](https://github.com/prometheus/pushgateway)

The push gateway provides a simple line API for but JMXTrans has no writer that supports http(s).

# Milestones

## Milestone 1

- Choose technologies (Metrics aggregator, JMX Exporter)
- Decide on deployment solution for: JMX Exporter and Metric aggregator (e.g. Victoria), Operator vs. DaemonSet vs. ...?
- Design a way to configure/dynamically reconfigure the Metric aggregator when sources change (ideally without restart of the Metric aggregator)
- Make testable in test dev cluster
- PoC implementation of the Metric pipeline (JMX -> Metric aggregator) for one or two of our operators

At the end of Milestone 1 we'd like to be able to have a Metric aggregator per physical/virtual machine that provides a Prometheus Federation API. We'd like this aggregator to automatically pull metrics from services running on the same server (care must be taken to distinguish the timeseries by e.g. namespace & name of the monitored service) which includes automatic reconfiguration when services change.

## Milestone 2
- Add Nifi & OPA operators
- Monitor nodes in the monitoring operator (make configurable an crd)
  - Brief research into DaemonSets 
- Implement Prometheus Federation (research & maybe spike)
- Collection of host level metrics (e.g. Netdata)

### Out of scope
- Selection of relevant metrics
  - For now we're happy to just ingest everything
- Log collection
- Dashboarding
- Security (e.g. JMX Exporter & Metric aggregator don't need authentication, authorization or transport encryption) -> Security Epic (https://github.com/stackabletech/issues/issues/5)
- Packaging -> https://github.com/stackabletech/issues/issues/39

### Subtasks

- [x] #62 
- [x] #63 

### TODOs
- [x] k8s discovery : investigate filtering by node (works with field selectors (nodeName) or with label nodeName)
- [x] k8s discovery : investigate scaling (new pods, pods are deleted -> service discovery works with scaling)
- [x] k8s discovery : investigate config deployment (stackable monitoring operator > daemon sets)
- [x] deployment : tls certificates und path to kubeconfig (can be read from kube config)
- [x] k8s discovery : test with victoriametrics (worked but for now we decided to go with prometheus)
- [x] Decide what scrapers to use [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) / [http_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config) / [consul](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config) -> (kubernetes_sd_config: http_sd_config works with static_configs, consul too big / complex for our purpose)
- [x] Evaluate and investigate push / pull metrics with victoria (decided to stay with pull -> jmx ports have to be provided from user via custom resource)
- [x] packaging : Bundle jmx_exporter + rules config (issue already exists) into the product packages (ZooKeeper)
- [x] packaging : Bundle jmx_exporter + rules config (issue already exists) into the product packages (Kafka)
- [x] Adapt Zookeeper operator to run jmx_exporter (container env variables) and extend custom resource for jmx_exporter port
- [x] Adapt Kafka operator to run jmx_exporter (container env variables) and extend custom resource for jmx_exporter port
- [x] Implement "Monitoring" operator using prometheus
- [x] Make monitoring available in the test-dev-cluster. See issue linked below.
- [ ] **question**: how to handle network outages ?
