### ISSUE TITLE
Openshift certification 24.7.0

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#625]
**TODOs**
- [x] Run pipelines for all operators without submitting
- [x] deploy operators from catalogs
- [x] run selected tests
  - [x] tests for secret-operator
  - [x] tests for listener-operator
  - [x] tests for zookeeper-operator
  - [x] tests for opa-operator
  - [x] tests for spark-k8s-operator
  - [x] kerberos tests for hdfs-operator
  - [x] gitsync test for airflow-operator
  - [x] smoke test for kafka-operator
  - [x] smoke test for trino-operator. 🔴  Failed. Was a problem with resources.
  - [x] tests for druid-operator @razvan 
  - [x] tests for commons-operator @adwk67 
  - [x] tests for hive-operator @razvan
  - [x] tests for hbase-operator @razvan
  - [x] tests for nifi-operator @adwk67 
  - [x] tests for superset-operator @adwk67 
- [x] Run pipelines for all operators and submit and check PRs
- [x] check certified ops that all is present and correct

## Follow-up for the next release

- add support for listener and secret to the build-manifests.py script and remove the build-manifests.sh script.
✅  remove individual product listings from the RH portal with the exception of the general platform one

### Clarify with RedHat

- What is the problem [here](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/4278#issuecomment-2275887290) and what is the correct solution ? 
-  Targeting a new OS version leads to a pipeline failure. Figure out how a new operator version can replace an old operator version in a catalog that doesn't contain the old operator. Example: commons 24.11 replaces 24.7.0 in the v4.16 catalog. But that catalog doesn't know about 24.7.0. because 24.7.0 only supports v4.11 to v4.15.
- clarify the operator-pipeline differences we see between us and what the certified operators repo is doing.
- a pipeline that has been closed can be automatically re-opened without warning: e.g. [here](https://github.com/redhat-openshift-ecosystem/certified-operators/pull/4278#issuecomment-2276219324)

(these points were submitted to Redhat on 09.08.2024 at 11:45 via the certification feedback form).

## Incidents

- The PR for the listener operator had a failure. It was closed by us but reopened automatically and merged,
- Now the operator is not in the catalog.

**Comment by adwk67** [comment]
Cert PRs
- [ ] commons-operator @adwk67 
- [ ] listener-operator
- [ ] secret-operator
- [ ] zookeeper-operator
- [ ] opa-operator
- [ ] airflow-operator
- [ ] druid-operator
- [ ] hbase-operator
- [ ] hdfs-operator
- [ ] hive-operator
- [ ] kafka-operator
- [ ] nifi-operator
- [ ] spark-k8s-operator
- [ ] superset-operator
- [ ] trino-operator

**Comment by sbernauer** [comment]
Waiting on  feedback from RedHat regarding the listener-op certification problems

**Comment by razvan** [comment]
Opened a new case with RH for the listener operator: https://rhcert.connect.redhat.com/#/cases/03901826

**Comment by sbernauer** [comment]
done
