### ISSUE TITLE
Make product service accounts configurable

### ISSUE THREAD

**Issue by razvan** [stackabletech/issues#630]
## Description
    
Stackable operators create service accounts for each stacklet they manage.

This has multiple problems:
- it's a waste of resources. These SAs are basically the same.
- it requires additional RBAC permissions for the operators themselves
- it's not (easily) configurable by users.

## Tasks

- [ ] Let package managers (Helm, OLM) deploy the product service accounts.
- [ ] Cleanup operator code and RBAC rules.
- [ ] Allow users to override the product SAs by adding a new field aptly named `serviceAccountName` to the product CRDs.
- [ ] Document the defaults and what users can change
- [ ] Write tests.

**Comment by NickLarsenNZ** [comment]
See also: https://github.com/stackabletech/issues/issues/675
