### ISSUE TITLE
tracking: Replace reviewdog with pre-commit in CI

### ISSUE THREAD

**Issue by Techassi** [stackabletech/issues#637]
This issue tracks the replacement of `reviewdog` with `pre-commit` in CI based on the decision https://github.com/stackabletech/decisions/issues/25.

```[tasklist]
### Replacements
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/319
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/320
- [ ] https://github.com/stackabletech/operator-rs/pull/854
- [ ] https://github.com/stackabletech/operator-rs/pull/856
- [ ] https://github.com/stackabletech/docker-images/pull/823
- [ ] https://github.com/stackabletech/docker-images/pull/824
- [ ] https://github.com/stackabletech/operator-templating/pull/422
- [ ] https://github.com/stackabletech/operator-templating/pull/423
- [ ] https://github.com/stackabletech/demos/pull/92
- [ ] https://github.com/stackabletech/image-tools/pull/42
- [ ] https://github.com/stackabletech/trino-lb/pull/49
- [ ] https://github.com/stackabletech/documentation/pull/657
- [ ] https://github.com/stackabletech/beku.py/pull/28
```

**Comment by Techassi** [comment]
All linked PRs are merged, closing.
