### ISSUE TITLE
Replace operator initialize_logging with stackable-telemetry initialization

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#639]
The old initialize_logging implementation currently requires `opentelemetry-jaeger` which is now deprecated in favour of the vendor/collector agnostic OTLP protocol in `opentelemetry-otlp`.

**This is preventing us from updating the opentelemetry related crates.** (as seen in https://github.com/stackabletech/operator-rs/pull/867, among other past PRs).

The recommended path forward for using Jaeger is to use the OTLP protocol.
[stackable-telemetry] already supports this, and so it is about time we deprecate the old log initialization and jaeger protocol and use [stackable-telemetry].

[stackable-telemetry]: https://github.com/stackabletech/operator-rs/blob/1487096d434bae0052c64afbe0c33b7b2507a39e/crates/stackable-telemetry/src/tracing.rs#L39-L61

## :green_circle: General

This section contains general improvements to `stackable-telemetry` (and related crates). Links to PRs are added as we encounter room for improvements during rollout / usage. This Phase can mostly be considered as long-running in the background.

### General stackable-telemetry improvements
- [x] https://github.com/stackabletech/operator-rs/pull/901
- [x] https://github.com/stackabletech/operator-rs/pull/940
- [x] https://github.com/stackabletech/operator-rs/pull/933
- [x] https://github.com/stackabletech/operator-rs/pull/944
- [x] https://github.com/stackabletech/operator-rs/pull/951
- [x] https://github.com/stackabletech/operator-rs/pull/995
- [ ] _Link for using `filter::Directive` for more granular level setting_
- [ ] Further [improve the ergonomics of the TracingBuilder](https://github.com/stackabletech/operator-rs/pull/901#discussion_r1860798808)
- [ ] Handle the more granular `tracing_subscriber::filter::Directive` (instead of just `tracing::level_filters::LevelFilter`).
- [x] https://github.com/stackabletech/operator-rs/pull/1001
- [x] https://github.com/stackabletech/operator-rs/pull/1007
- [x] https://github.com/stackabletech/operator-rs/pull/1010
- [x] https://github.com/stackabletech/operator-rs/pull/1009
- [x] https://github.com/stackabletech/operator-rs/pull/1011
- [x] https://github.com/stackabletech/operator-rs/pull/1016

## :green_circle: Deprecation

This section contains various links to PRs which deprecate old functions and ways of doing things. Most of the deprecation was introduced in `stackable-operator` 0.88.0.

### Deprecation Tasks
- [x] https://github.com/stackabletech/operator-rs/pull/950
- [x] https://github.com/stackabletech/operator-rs/pull/989
- [x] https://github.com/stackabletech/operator-rs/pull/977

## 🟢 Rollout

This phase is currently in progress and involves many moving parts. We aim to finish up the initial rollout as fast as possible to unblock other developers. This includes work in `operator-rs` and downstream operators. The rollout should take care of _all_ breaking changes and other developers can continue working without the need to fix something themselves.

### General
- [x] Improve formatting of `stackable_operator::utils::print_startup_string()` by using Span fields.

<details>
<summary>Initial rollout</summary>

These PRs were merged with the less-than ideal implementation because the PRs were blocking the rollout of https://github.com/stackabletech/operator-rs/pull/1002, and the ideal implementation came after that in https://github.com/stackabletech/operator-rs/pull/1001.

### Operators (initial rollout to unblock others)
- [x] https://github.com/stackabletech/airflow-operator/pull/601
- [x] https://github.com/stackabletech/druid-operator/pull/703
- [x] https://github.com/stackabletech/hbase-operator/pull/640
- [x] https://github.com/stackabletech/hdfs-operator/pull/661
- [x] https://github.com/stackabletech/hive-operator/pull/585
- [x] https://github.com/stackabletech/kafka-operator/pull/840
- [x] https://github.com/stackabletech/nifi-operator/pull/767
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/547
- [x] https://github.com/stackabletech/superset-operator/pull/610
- [x] https://github.com/stackabletech/trino-operator/pull/728
- [x] https://github.com/stackabletech/zookeeper-operator/pull/927
- [x] https://github.com/stackabletech/commons-operator/pull/338
- [x] https://github.com/stackabletech/listener-operator/pull/291
- [x] https://github.com/stackabletech/opa-operator/pull/703
- [x] https://github.com/stackabletech/secret-operator/pull/581

</details>

This rollout implements https://github.com/stackabletech/operator-rs/pull/1001, which could only be done after https://github.com/stackabletech/operator-rs/pull/1002 was rolled out.

### Operators (ideal rollout)
- [x] https://github.com/stackabletech/airflow-operator/pull/608
- [x] https://github.com/stackabletech/druid-operator/pull/710
- [x] https://github.com/stackabletech/hbase-operator/pull/648
- [x] https://github.com/stackabletech/hdfs-operator/pull/668
- [x] https://github.com/stackabletech/hive-operator/pull/592
- [x] https://github.com/stackabletech/kafka-operator/pull/847
- [x] https://github.com/stackabletech/nifi-operator/pull/776
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/554
- [x] https://github.com/stackabletech/superset-operator/pull/617
- [x] https://github.com/stackabletech/trino-operator/pull/735
- [x] https://github.com/stackabletech/zookeeper-operator/pull/934
- [x] https://github.com/stackabletech/commons-operator/pull/344
- [x] https://github.com/stackabletech/commons-operator/pull/345
- [x] ~listener-operator~ Done in https://github.com/stackabletech/listener-operator/pull/291
- [x] https://github.com/stackabletech/opa-operator/pull/710
- [x] https://github.com/stackabletech/secret-operator/pull/587

## :green_circle: Enablement

This phase is to allow stackable-telemetry to be configurable via the Helm chart,  and have it documented.

### General
- [x] Search for and update any documentation for configuring Jaeger (will now use OTLP).
- [x] https://github.com/stackabletech/stackable-cockpit/pull/369
- [x] https://github.com/stackabletech/operator-templating/pull/501
- [x] Set rolling period to Hourly in Helm (previously this was the default in stackable-operator code)

### Example `values.yaml` design

```yaml
telemetry:
  consoleLog:
    enabled: true # (true)
    level: debug # (null)
    format: plain # (null), plain, json, later: logfmt
  fileLog:
    enabled: false # (true)
    level: debug # (null)
    rotationPeriod: never # (hourly)
    maxFiles: 2 # (6)
  otelLogExporter:
    enabled: true # (false)
    level: debug # (null)
    endpoint: my-collector:4317 # (null)
  otelTraceExporter:
    enabled: true # (false)
    level: debug # (null)
    endpoint: my-collector:4317 # (null)
```

_Values in braces `()` are default values_

```[tasklist]
### Templating
- [x] https://github.com/stackabletech/operator-templating/pull/501
- [x] https://github.com/stackabletech/operator-templating/pull/505
```

<details>
<summary>Initial Rollout</summary>

### Operators
- [x] https://github.com/stackabletech/airflow-operator/pull/610
- [x] https://github.com/stackabletech/druid-operator/pull/711
- [x] https://github.com/stackabletech/hbase-operator/pull/649
- [x] https://github.com/stackabletech/hdfs-operator/pull/669
- [x] https://github.com/stackabletech/hive-operator/pull/593
- [x] https://github.com/stackabletech/kafka-operator/pull/848
- [x] https://github.com/stackabletech/nifi-operator/pull/778
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/556
- [x] https://github.com/stackabletech/superset-operator/pull/620
- [x] https://github.com/stackabletech/trino-operator/pull/736
- [x] https://github.com/stackabletech/zookeeper-operator/pull/935
- [x] https://github.com/stackabletech/commons-operator/pull/346
- [x] https://github.com/stackabletech/listener-operator/pull/296
- [x] https://github.com/stackabletech/opa-operator/pull/713
- [x] https://github.com/stackabletech/secret-operator/pull/588

</details>

<details>
<summary>Helm Fix Rollout</summary>

### Helm Fixes
- [x] https://github.com/stackabletech/airflow-operator/pull/611
- [x] https://github.com/stackabletech/druid-operator/pull/712
- [x] https://github.com/stackabletech/hbase-operator/pull/650
- [x] https://github.com/stackabletech/hdfs-operator/pull/670
- [x] https://github.com/stackabletech/hive-operator/pull/594
- [x] https://github.com/stackabletech/kafka-operator/pull/849
- [x] https://github.com/stackabletech/nifi-operator/pull/779
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/557
- [x] https://github.com/stackabletech/superset-operator/pull/621
- [x] https://github.com/stackabletech/trino-operator/pull/737
- [x] https://github.com/stackabletech/zookeeper-operator/pull/936
- [x] https://github.com/stackabletech/commons-operator/pull/347
- [x] https://github.com/stackabletech/listener-operator/pull/297
- [x] https://github.com/stackabletech/opa-operator/pull/714
- [x] https://github.com/stackabletech/secret-operator/pull/589

</details>

### Bump stackable-operator to 0.92.0
- [x] https://github.com/stackabletech/airflow-operator/pull/613
- [x] https://github.com/stackabletech/druid-operator/pull/714
- [x] https://github.com/stackabletech/hbase-operator/pull/652
- [x] https://github.com/stackabletech/hdfs-operator/pull/672
- [x] https://github.com/stackabletech/hive-operator/pull/596
- [x] https://github.com/stackabletech/kafka-operator/pull/851
- [x] https://github.com/stackabletech/nifi-operator/pull/782
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/560
- [x] https://github.com/stackabletech/superset-operator/pull/623
- [x] https://github.com/stackabletech/trino-operator/pull/739
- [x] https://github.com/stackabletech/zookeeper-operator/pull/938
- [x] https://github.com/stackabletech/commons-operator/pull/349
- [x] https://github.com/stackabletech/listener-operator/pull/299
- [x] https://github.com/stackabletech/opa-operator/pull/715
- [x] https://github.com/stackabletech/secret-operator/pull/591

### Tasks
- [x] ~Update observability stack/demo~
- [x] https://github.com/stackabletech/documentation/pull/731

### Acceptance Criteria

- [x] RollingFileAppender working the same as it did (logging tests pass for bundle_builder).
- [x] Tracing to Jaeger still works, only via OTLP rather than Jaeger.
- [x] Startup string uses Span fields instead of free-form text.
- [x] All operators use stackable-telemetry in place of the to-be deprecated initialize_logging.

Updated code snippets will appear here as soon as the API is finalized.
In the meantime, consider looking at the [official docs](https://stackabletech.github.io/operator-rs/stackable_telemetry/index.html).

**Comment by NickLarsenNZ** [comment]
> Given the level of configurability it has, having operators call into it directly seems undesirable. Couldn't `initialize_logging` just be changed to do that instead of the current impl?

Yes it could. It might just need some additional args for enabling things like the otlp subscribers (but maybe that already maps well enough from the current Jaeger option).

**Comment by Techassi** [comment]
## Release Notes

```adoc
* All operators support sending OpenTelemtry logs and traces.
* All operators use unified CLI arguments and environment variables to configure the exporters.
* The recommended operator deployment via Helm allows configuration via Helm values.
* Console logs are enabled by default, all other exporters are disabled by default.

Additionally see the official xref:concepts:observability/telemetry.adoc[telemetry documentation page] for further details.
```
