### ISSUE TITLE
tracking: CRD versioning MVP

### ISSUE THREAD

**Issue by Techassi** [stackabletech/issues#642]
This tracks the process of introducing versioning for all CRD related data types and CRDs itself across the SDP. In addition to cross-cutting tasks, there are still some open tasks specific to the `stackable-versioned` crate. The ADR on CRD versioning will be written based on learnings from all phases.

## Documentation Tasks

- [x] https://github.com/stackabletech/operator-rs/pull/957
- [x] https://github.com/stackabletech/operator-rs/pull/966
- [ ] https://github.com/stackabletech/documentation/pull/712

## Macro Tasks

- [x] https://github.com/stackabletech/operator-rs/pull/881
- [x] https://github.com/stackabletech/operator-rs/pull/883
- [x] https://github.com/stackabletech/operator-rs/pull/884
- [x] https://github.com/stackabletech/operator-rs/pull/891
- [x] https://github.com/stackabletech/operator-rs/pull/892
- [x] https://github.com/stackabletech/operator-rs/pull/912
- [x] https://github.com/stackabletech/operator-rs/pull/914
- [x] https://github.com/stackabletech/operator-rs/pull/919
- [x] https://github.com/stackabletech/operator-rs/pull/922
- [x] https://github.com/stackabletech/operator-rs/pull/923
- [x] https://github.com/stackabletech/operator-rs/pull/924
- [x] https://github.com/stackabletech/operator-rs/pull/925
- [x] https://github.com/stackabletech/operator-rs/pull/926
- [x] https://github.com/stackabletech/operator-rs/pull/958
- [x] https://github.com/stackabletech/operator-rs/pull/961
- [x] https://github.com/stackabletech/operator-rs/pull/967
- [x] https://github.com/stackabletech/operator-rs/pull/969
- [x] https://github.com/stackabletech/operator-rs/pull/971
- [x] https://github.com/stackabletech/operator-rs/pull/982
- [x] https://github.com/stackabletech/operator-rs/pull/991
- [x] https://github.com/stackabletech/operator-rs/pull/1043
- [x] https://github.com/stackabletech/operator-rs/pull/1033
- [x] https://github.com/stackabletech/operator-rs/pull/1041
- [x] https://github.com/stackabletech/operator-rs/pull/1038
- [x] https://github.com/stackabletech/operator-rs/pull/1045
- [x] https://github.com/stackabletech/operator-rs/pull/1035
- [x] https://github.com/stackabletech/operator-rs/pull/1030
- [x] https://github.com/stackabletech/operator-rs/pull/1053
- [x] https://github.com/stackabletech/operator-rs/pull/1050
- [x] https://github.com/stackabletech/operator-rs/pull/1056
- [x] https://github.com/stackabletech/operator-rs/pull/1066
- [x] https://github.com/stackabletech/operator-rs/pull/1057
- [x] https://github.com/stackabletech/operator-rs/pull/1061
- [x] https://github.com/stackabletech/operator-rs/pull/1065
- [x] https://github.com/stackabletech/operator-templating/pull/534
- [x] https://github.com/stackabletech/operator-rs/pull/1079
- [x] https://github.com/stackabletech/operator-rs/pull/1074

### Upstream `#[kube]` changes

- [x] https://github.com/kube-rs/kube/pull/1697
- [x] https://github.com/kube-rs/kube/pull/1644

### Upstream `darling` changes

- [x] https://github.com/TedDriggs/darling/pull/341

## Phase One

Introduce `stackable-versioned` in all operator CRDs. This includes adding the macro to the CRD structs and producing the current `v1alpha1` version without introducing any changes. Additionally, generate the merged CRD.

> [!TIP]
> Refer to the _model PR_ with explanations of each step: https://github.com/stackabletech/opa-operator/pull/661

Replace the items in the task lists below with the applicable Pull Requests.

### Tasks
- [x] https://github.com/stackabletech/operator-rs/pull/968
- [x] https://github.com/stackabletech/airflow-operator/pull/581
- [x] https://github.com/stackabletech/commons-operator/pull/353
- [x] https://github.com/stackabletech/druid-operator/pull/687
- [x] ~~edc-operator~~
- [x] https://github.com/stackabletech/hbase-operator/pull/624
- [x] https://github.com/stackabletech/hdfs-operator/pull/651
- [x] ~hello-world-operator~
- [x] https://github.com/stackabletech/hive-operator/pull/571
- [x] https://github.com/stackabletech/kafka-operator/pull/826
- [x] https://github.com/stackabletech/listener-operator/pull/307
- [x] https://github.com/stackabletech/nifi-operator/pull/752
- [x] https://github.com/stackabletech/opa-operator/pull/661
- [ ] https://github.com/stackabletech/secret-operator/pull/636
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/525
- [x] https://github.com/stackabletech/superset-operator/pull/597
- [x] https://github.com/stackabletech/zookeeper-operator/pull/917
- [x] https://github.com/stackabletech/trino-operator/pull/711

## Phase Two

Use the common versioned structs from _insert operator-rs PR here_.

### Tasks
- [x] https://github.com/stackabletech/airflow-operator/pull/623
- [x] https://github.com/stackabletech/druid-operator/pull/725
- [x] ~HBase~ Doesn't use common crd structs (bumped stackable-operator anyway in https://github.com/stackabletech/hbase-operator/pull/664)
- [x] https://github.com/stackabletech/hdfs-operator/pull/684
- [x] https://github.com/stackabletech/hive-operator/pull/604
- [x] https://github.com/stackabletech/kafka-operator/pull/861
- [x] https://github.com/stackabletech/nifi-operator/pull/793 (replaces https://github.com/stackabletech/nifi-operator/pull/798)
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/572
- [x] https://github.com/stackabletech/superset-operator/pull/635
- [x] https://github.com/stackabletech/trino-operator/pull/748
- [x] https://github.com/stackabletech/zookeeper-operator/pull/946
- [x] https://github.com/stackabletech/commons-operator/pull/357
- [x] https://github.com/stackabletech/listener-operator/pull/310
- [x] https://github.com/stackabletech/opa-operator/pull/727
- [x] https://github.com/stackabletech/secret-operator/pull/601 (replaces https://github.com/stackabletech/secret-operator/pull/600)

## Phase Three

This phase will be an end-to-end implementation of CRD versioning, meaning we do the following tasks:

- Pick an operator where we want to introduce a CRD change, consider items from https://github.com/stackabletech/issues/issues/504. The following two changes were choosen:
  - https://github.com/stackabletech/secret-operator/issues/627
  - https://github.com/stackabletech/secret-operator/issues/626
- Implement the webhook to enable automatic conversion between CRD versions.
- Document the changes and provide feedback on using `stackable-versioned` and `stackable-webhook`.

[^1]: https://github.com/stackabletech/issues/issues/507
