### ISSUE TITLE
chore(tracking): Release SDP 24.11.0

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#647]
# Stackable Release 24.11

> [!IMPORTANT]
> Important dates:
> - 🟢 2024-08-06 - Release planning
> - 🟢 2024-09-11 - Lock product versions
> - 🟢 2024-10-23 - Final operator-rs release (excluding bug fixes before the release)
> - 🟢 2024-10-25 - Bump operator-rs in each operator
> - 🟢 2024-10-28 - Begin pre-release tasks (week before on-site)
> - 🟢 2024-11-08 - Bump jmx_exporter, or roll back (See: https://github.com/stackabletech/issues/issues/649)
> - 🟢  2027-11-15 - Official release date
> 
> ~See the [24.11 feature tracking project](https://github.com/orgs/stackabletech/projects/42)~ _This link now points to a future release._

## Release checklists

Replace the items in the task lists below with the applicable Pull Requests / Issues

### General Prerequisites (before Feature Freeze)

> [!TIP]
> These tasks should be done earlier in the process to lessen the burden at Pre-release time.

```[tasklist]
### Early Pre-release tasks
- [x] Find out what is left before updating operator-rs across repos
- [ ] https://github.com/stackabletech/operator-rs/issues/898
- [ ] https://github.com/stackabletech/operator-templating/issues/450
- [ ] https://github.com/stackabletech/issues/issues/652
- [ ] https://github.com/stackabletech/docker-images/issues/831
```

> [!TIP]
> These tasks should be done a week or so before the release date.

```[tasklist]
### Pre-release
- [ ] https://github.com/stackabletech/operator-templating/pull/457
- [x] [Run all of the test suites in Jenkins (with all product versions, not just "nightly")](https://github.com/stackabletech/issues/issues/647#issuecomment-2443567223)
- [ ] https://github.com/stackabletech/issues/issues/657
- [ ] https://github.com/stackabletech/issues/issues/658
- [ ] https://github.com/stackabletech/issues/issues/664
- [x] Check stackable-utils scripts in dry-run mode work
```

### Other Pre-Requisites (before Feature Freeze)

Search for open issues labeleded with [`scheduled-for/2024-11`](https://github.com/search?q=org%3Astackabletech+label%3Ascheduled-for%2F2024-11&type=issues&state=open)

```[tasklist]
### Other release-specific pre-requisites
- [ ] https://github.com/stackabletech/demos/issues/62#issuecomment-2382221177
- [x] https://github.com/stackabletech/demos/pull/119
- [ ] https://github.com/stackabletech/issues/issues/649
- [ ] https://github.com/stackabletech/crddocs/issues/44
- [ ] https://github.com/stackabletech/demos/pull/122
- [ ] https://github.com/stackabletech/stackable-utils/issues/84
- [ ] https://github.com/stackabletech/stackable-utils/issues/83
- [ ] https://github.com/stackabletech/issues/issues/611
- [ ] https://github.com/stackabletech/crddocs-generator/pull/25
```

### Feature freeze

This will not be so crucial with release branches, but is nonetheless sensible as it will make it easier to cherry-pick any release-related bugfixes from main into the release branch.

### End of the release cycle (Release day)

```[tasklist]
#### Technical tasks
- [x] Temporarily remove branch protection before pushing the release branches/tags
- [x] Create release branches for docker-images (see stackable-utils for script to create branches)
- [x] Create release tag(s) for docker-images (see stackable-utils for scripts to create tags)
- [x] Create release branches for operators (see stackable-utils for script to create branches)
- [x] Create release tag(s) for operators (see stackable-utils for scripts to create tags)
- [x] Create release branch for demos (see stackable-utils for scripts to create branch)
- [x] ~~Create release tag for stackable-cockpit (optional, highly experimental, requires manual tag creation)~~
- [x] Update release version in changelogs on main branches (see stackable-utils for script to do this)
- [x] [Merge changelog PRs for operators](https://github.com/search?q=org%3Astackabletech+Update+CHANGELOG.md+from+release+24.11.0&type=pullrequests&p=2) @NickLarsenNZ
- [ ] https://github.com/stackabletech/crddocs/pull/45
- [x] Check (selected) integration tests on the new release branches @NickLarsenNZ
- [ ] https://github.com/stackabletech/issues/issues/672
- [ ] https://github.com/stackabletech/demos/pull/116
- [x] Run/Check demos with dev release and main branch and create draft PR for release-related changes
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/334
- [x] Test `stackablectl` with locally updated (to new release number) `releases.yaml` @Techassi
- [ ] https://github.com/stackabletech/release/pull/33
- [x] ARM testing @Maleware
- [x] Check that an upgrade can be performed on an existing cluster without data loss. (cycling-data)
- [x] Run all of the test suites @NickLarsenNZ
- [x] OpenShift Testing @razvan
- [ ] https://github.com/stackabletech/operator-rs/pull/909
- [ ] https://github.com/stackabletech/operator-rs/pull/910
```

```[tasklist]
#### Documentation tasks
- [x] Check the Changelog and/or issue labels to compile Release Highlights **Add to draft PR below**
- [x] Compile list of new product versions that are supported and compile a list of new product features to include in the Release Highlights **Add to draft PR below**
- [x] Upgrade guide: Document how to use stackablectl to uninstall all and install new release
- [x] Upgrade guide: Document how to use helm to uninstall all and install new release
- [x] Upgrade guide: Every breaking change of all our operators
- [x] Upgrade guide: List dropped supported product versions (if there are some)
- [x] Upgrade guide: List dropped supported operators (if there are some)
- [x] Upgrade guide: List supported k8s versions
- [ ] https://github.com/stackabletech/documentation/pull/679
- [x] Update SDP release version in documentation/modules/ROOT/pages/getting-started.adoc
- [x] Update the getting-started page in the main docs and check it works with this release: https://github.com/stackabletech/documentation/blob/main/modules/ROOT/pages/getting-started.adoc
- [ ] https://github.com/stackabletech/documentation/pull/685
- [ ] https://github.com/stackabletech/documentation/pull/686
- [ ] https://github.com/stackabletech/demos/pull/134
- [x] Cut a release branch (see [scripts/make-release-branch.sh](https://github.com/stackabletech/documentation/blob/main/scripts/make-release-branch.sh))
- [x] Update releases in the playbook (see [scripts/publish-new-version.sh](https://github.com/stackabletech/documentation/blob/main/scripts/publish-new-version.sh))
- [ ] https://github.com/stackabletech/demos/pull/135
- [ ] https://github.com/stackabletech/documentation/pull/684
- [x] Update version of main demos repo (antora.yml on the release branch) - manually done by @Techassi - needs scripting
- [x] Set the release to "Released" in the Feature Tracker and create a new release
- [x] If not already done, check the demos work for the new release
- [ ] ~OpenShift 4.16 certification (update the release notes on main and cherry pick to the release branch)~ defering to SDP 24.11.1
```

Marketing tasks can now reference published documentation.

```[tasklist]
#### Marketing tasks
- [x] Write marketing / customer oriented release summary to be published in the marketing channels
- [x] Update the homepage banner (as long as we have it) to point to the new release
- [x] Write a blogpost / news article announcing the new release (optional)
- [x] Announce Release on LinkedIn
- [x] Announce Release in Newsletter (optional)
- [x] Post an announcement in the GitHub [Discussions Announcement forum](https://github.com/stackabletech/community/discussions/categories/announcements) and make it a pinned discussion while at the same time removing the old pinned thread
- [x] Post an announcement in Discord
- [x] Post an announcement on DOK Community in the #be-shameless Channel (Ping Lars or Jim)
- [x] Send announcement to Heise
- [x] Ping the stackable-ionos-tech channel or anyone responsible once all tags are created
```

```[tasklist]
#### Post-release tasks
- [x] Update the list of supported SDP releases in Jira (ping Jim)
- [ ] ~Openshift certification. Create an issue from this [template](https://github.com/stackabletech/issues/blob/main/.github/ISSUE_TEMPLATE/olm_manifests.md) for the OLM manifests~ Deferring to 24.11.1
- [ ] https://github.com/stackabletech/documentation/pull/672
- [ ] https://github.com/stackabletech/issues/issues/669
- [ ] https://github.com/stackabletech/issues/pull/680
- [ ] https://github.com/stackabletech/documentation/pull/693
- [x] [Create the next release tracking task](https://github.com/stackabletech/issues/issues/new?template=release.md) https://github.com/stackabletech/issues/issues/683
- [ ] Fix the e2e security demo (ask @sbernauer)
```

**Comment by NickLarsenNZ** [comment]
Tests are all passing
![All green](https://github.com/user-attachments/assets/a06f0832-e826-400c-97d6-24c0303d0bd3)

**Comment by soenkeliebau** [comment]
# AirFlow
New version: 2.10.x
- Datasets no longer trigger inactive DAGs ([#38891](https://github.com/apache/airflow/pull/38891))
- OpenTelemetry Traces for Apache Airflow ([#37948](https://github.com/apache/airflow/pull/37948))
- Using Multiple Executors Concurrently ([#40701](https://github.com/apache/airflow/pull/40701))
- 

# Kafka
New version: 3.8.x
- [[KAFKA-15420](https://issues.apache.org/jira/browse/KAFKA-15420)] - Kafka Tiered Storage V1
- [[KAFKA-16399](https://issues.apache.org/jira/browse/KAFKA-16399)] - Add JBOD support in tiered storage
- [[KAFKA-15878](https://issues.apache.org/jira/browse/KAFKA-15878)] - KIP-768: Extend support for opaque (i.e. non-JWT) tokens in SASL/OAUTHBEARER
- [[KAFKA-7632](https://issues.apache.org/jira/browse/KAFKA-7632)] - Support setting zstd Compression Level
- [[KAFKA-15942](https://issues.apache.org/jira/browse/KAFKA-15942)] - Implement ConsumerInterceptor


# Superset
Only bugfix version

# Trino
New version: 455
- Add [Exasol connector](https://trino.io/docs/current/connector/exasol.html). ([#16083](https://github.com/trinodb/trino/issues/16083))
- Add support for the [euclidean_distance()](https://trino.io/docs/current/functions/array.html#euclidean_distance), [dot_product()](https://trino.io/docs/current/functions/array.html#dot_product), and [cosine_distance()](https://trino.io/docs/current/functions/array.html#cosine_distance) functions. ([#22397](https://github.com/trinodb/trino/issues/22397))
- Improve performance of queries with selective joins by performing fine-grained filtering of rows using dynamic filters. ([#22411](https://github.com/trinodb/trino/issues/22411))
- Improve performance for column masking with [Open Policy Agent access control](https://trino.io/docs/current/security/opa-access-control.html). ([#21359](https://github.com/trinodb/trino/issues/21359))
- Add support for an event listener plugin that publishes events to Kafka. ([#22426](https://github.com/trinodb/trino/issues/22426))
- [⚠️ Breaking change:](https://trino.io/docs/current/release.html#breaking-changes) Improve query concurrency when memory is low by removing the query.low-memory-killer.delay configuration property. ([#22936](https://github.com/trinodb/trino/issues/22936))
- Add query starting time in QueryStatistics in all [Event listeners](https://trino.io/docs/current/admin.html#admin-event-listeners). ([#23113](https://github.com/trinodb/trino/issues/23113))
- Add support S3 file system encryption with fault-tolerant execution mode. ([#22529](https://github.com/trinodb/trino/issues/22529))
- Fix memory tracking issue for aggregations that could cause worker crashes with out-of-memory errors. ([#23098](https://github.com/trinodb/trino/issues/23098))

# ZooKeeper
Only bugfix version

# Druid
New version: 30 (was experimental before)


# HBase
New version: 2.6.x (was experimental before)

# Hadoop
New version 3.4.x (was experimental before)


# NiFi
New version 2.0.x (was experimental before)

# Hive

# Spark 
Only bugfix version
