### ISSUE TITLE
Don't hardcode any user or group id in our operators

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#651]
Some of our operators might hardcode user id, group id, fsgroup or other security context related things. We need to move away from that.

The detailed explanation can be found in the parent issue.

## Step 1: Identify affected operators

Step 1 of this issue is to identify all operators that are "affected" and this seems to be the list:

I ran a search for "1000" and "run_as_user" on these operators.

- [x] Airflow
- [x] Druid
- [x] HBase
- [x] Hadoop HDFS
- [x] Hive
- [x] Kafka
- [x] NiFi
- [x] Spark
- [x] Superset
- [x] Trino
- [x] ZooKeeper
- [ ] Commons
- [ ] Listener
- [x] OPA
- [ ] Secret
- [ ] Hello World

TODO: For the ones not affected I want to double check by deploying and inspecting the pods

- [ ] Commons
- [ ] Listener
- [ ] Secret
- [ ] Hello World

## Step 2: Remove hardcoded ids and test

Only remove user id and group id usage from these operators.
Leave the fsGroup in for now as that needs a more sophisticated solution.
Not hardcoding user id and group id means they'll fall back to the values from the docker image.
See https://github.com/stackabletech/issues/issues/645 for details.

- [x] https://github.com/stackabletech/airflow-operator/pull/636
- [x] https://github.com/stackabletech/druid-operator/pull/718
- [x] https://github.com/stackabletech/hbase-operator/pull/660
- [x] https://github.com/stackabletech/hdfs-operator/pull/683
- [x] https://github.com/stackabletech/hive-operator/pull/603
- [x] https://github.com/stackabletech/kafka-operator/pull/862
- [x] https://github.com/stackabletech/nifi-operator/pull/801
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/575
- [x] https://github.com/stackabletech/superset-operator/pull/637
- [x] https://github.com/stackabletech/trino-operator/pull/752
- [x] https://github.com/stackabletech/zookeeper-operator/pull/950
- [x] https://github.com/stackabletech/opa-operator/pull/732

## Step 3: Change 1000/1000 defaults in docker-images

- https://github.com/stackabletech/docker-images/pull/1164

**Comment by sbernauer** [comment]
Yeah, `PVC default/druid-broker-default-0-tls-mount was not created for pod` is totally normal.
Testing plan LGTM

**Comment by sbernauer** [comment]
There are some unchecked boxes you might want to have a look at

**Comment by lfrancke** [comment]
You mean the affected operators? I only checked the boxes for those that need to be "treated"

**Comment by sbernauer** [comment]
I was mostly referring to

> TODO: For the ones not affected I want to double check by deploying and inspecting the pods

and the list below.
But you know best, feel free to ignore
