### ISSUE TITLE
chore(tracking): Update Rust dependencies of operators for SDP 24.11

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/issues#652]
This especially bumps to stackable-operator 0.80.0, which includes the non-default cluster domain support. 

Command used:

```shell
cargo +nightly update && cargo +nightly update --breaking -Z unstable-options && cargo +nightly update
```

```[tasklist]
### Bumps
- [ ] https://github.com/stackabletech/airflow-operator/pull/518
- [ ] https://github.com/stackabletech/druid-operator/pull/637
- [ ] https://github.com/stackabletech/hbase-operator/pull/574
- [ ] https://github.com/stackabletech/hdfs-operator/pull/591
- [ ] https://github.com/stackabletech/hive-operator/pull/522
- [ ] https://github.com/stackabletech/kafka-operator/pull/771
- [ ] https://github.com/stackabletech/nifi-operator/pull/694
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/480
- [ ] https://github.com/stackabletech/superset-operator/pull/549
- [ ] https://github.com/stackabletech/trino-operator/pull/655
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/870
- [ ] https://github.com/stackabletech/commons-operator/pull/290
- [ ] https://github.com/stackabletech/listener-operator/pull/237
- [ ] https://github.com/stackabletech/opa-operator/pull/637
- [ ] https://github.com/stackabletech/secret-operator/pull/510
- [ ] https://github.com/stackabletech/hello-world-operator/pull/125
```

**Comment by sbernauer** [comment]
All crates (including op-rs 0.80.0!) have been bumped
