### ISSUE TITLE
chore(tracking): Check and update getting-started scripts for 24.11

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#657]
## Pre-Release Getting Started Script Updates

Part of <https://github.com/stackabletech/issues/issues/647>

In each operator repository, run the following commands. If any updates are
required, open a PR using the applicable link below.

```shell
# Some of the scripts are in a code/ subdirectory
# pushd docs/modules/superset/examples/getting_started
# pushd docs/modules/superset/examples/getting_started/code
pushd $(fd -td getting_started | grep examples); cd code 2>/dev/null || true

# Make a fresh cluster (~12 seconds)
kind delete cluster && kind create cluster
./getting_started.sh stackablectl

# Make a fresh cluster (~12 seconds)
kind delete cluster && kind create cluster
./getting_started.sh helm

popd
```

> [!TIP]
> Create branches with predictable names so the links below work. Remember
> to replace `xx.(x)x` with the appropriate release version:
>
> ```sh
> git stash -m "unsaved work"
> git fetch origin
> git checkout -b fix/getting-started-pre-24.11 origin/main
> ```
>
> Then use the links below to automatically create applicable PRs for each operator
> using the PR template.

Replace the items in the task lists below with the applicable Pull Requests (if any).

```[tasklist]
### Getting Started Script Checks and Updates
- [x] Update getting-started script for airflow-operator @adwk67
- [x] ~Update getting-started script for commons-operator~ (no GSG)
- [x] https://github.com/stackabletech/druid-operator/pull/643
- [x] ~Update getting-started script for edc-operator~ (no GSG)
- [x] Update getting-started script for hbase-operator @NickLarsenNZ (~pending: https://github.com/stackabletech/hbase-operator/issues/508~ Not doing this release)
- [x] Update getting-started script for hdfs-operator @adwk67
- [x] ~Update getting-started script for hello-world-operator~
- [x] Update getting-started script for hive-operator @adwk67
- [x] https://github.com/stackabletech/kafka-operator/pull/778
- [x] ~Update getting-started script for listener-operator~ (no GSG)
- [x] Update getting-started script for nifi-operator @NickLarsenNZ
- [x] Update getting-started script for opa-operator @NickLarsenNZ
- [x] ~Update getting-started script for secret-operator~ (no GSG)
- [x] Update getting-started script for spark-k8s-operator @NickLarsenNZ
- [x] Update getting-started script for superset-operator @NickLarsenNZ
- [x] Update getting-started script for trino-operator @NickLarsenNZ (worked for @adwk67)
- [x] Update getting-started script for zookeeper-operator @NickLarsenNZ
```

**Comment by NickLarsenNZ** [comment]
On the first run of trino-operator getting_started it timed-out. I'll treat it as a transient error, but recording it here in case we see it more often in future.

```
❯ ./getting_started.sh stackablectl
installing Operators with stackablectl
Installed commons=0.0.0-dev operator
Installed secret=0.0.0-dev operator
Installed listener=0.0.0-dev operator
Installed trino=0.0.0-dev operator

Installed 4 operators

Use "stackablectl operator installed [OPTIONS]" to list installed operators.
Installing Trino cluster from trino.yaml
trinocluster.trino.stackable.tech/simple-trino created
Awaiting Trino rollout finish
Waiting for 1 pods to be ready...
error: timed out waiting for the condition
```

**Comment by adwk67** [comment]
#### Kafka-operator
As we are now using the listener, port 9093 is exposed instead of 9092. The broker reports:
`Failed authentication with /127.0.0.1 (channelId=127.0.0.1:9093-127.0.0.1:32822-112) (SSL handshake failed)`

**Comment by NickLarsenNZ** [comment]
I have tested the HBase getting-started without https://github.com/stackabletech/hbase-operator/issues/508 as it seems it won't make the release.

If https://github.com/stackabletech/hbase-operator/issues/508 is merged, the getting_started test needs doing.
