### ISSUE TITLE
chore(tracking): Test demos on nightly versions for 24.11

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#658]
## Pre-Release Demo Testing on Nightly

Part of <https://github.com/stackabletech/issues/issues/647>

> [!CAUTION]
> Ensure the [`next` branch is merged to `main`][1], otherwise you will be testing based on old product versions.
>
> This is needed until [stackablectl can deploy demos for a release][2].
>
> [1]: https://github.com/stackabletech/demos/compare/main...next
> [2]: https://github.com/stackabletech/stackable-cockpit/issues/310

This is testing:

1. The demos documented in nightly (with the updated product versions) still work.
2. That the operators can be upgraded from the current release to the nightly release and do not negatively impact the products.

> [!NOTE]
> Record any issues or anomalies during the process in a comment on this issue.
> Eg:
> ```
> :green_circle: **airflow-scheduled-job**
>
> The CRD had been updated and I needed to change the following in the manifest:
> ...
> ```

Replace the items in the task lists below with the applicable Pull Requests (if any).

```[tasklist]
### Testing Demos on Nightly
- [ ] [airflow-scheduled-job](https://docs.stackable.tech/home/nightly/demos/airflow-scheduled-job)
- [ ] [data-lakehouse-iceberg-trino-spark](https://docs.stackable.tech/home/nightly/demos/data-lakehouse-iceberg-trino-spark)
- [ ] [end-to-end-security](https://docs.stackable.tech/home/nightly/demos/end-to-end-security)
- [ ] [hbase-hdfs-load-cycling-data](https://docs.stackable.tech/home/nightly/demos/hbase-hdfs-load-cycling-data)
- [ ] [jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data](https://docs.stackable.tech/home/nightly/demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data)
- [ ] [logging](https://docs.stackable.tech/home/nightly/demos/logging)
- [ ] [nifi-kafka-druid-earthquake-data](https://docs.stackable.tech/home/nightly/demos/nifi-kafka-druid-earthquake-data)
- [ ] [nifi-kafka-druid-water-level-data](https://docs.stackable.tech/home/nightly/demos/nifi-kafka-druid-water-level-data)
- [ ] [signal-processing](https://docs.stackable.tech/home/nightly/demos/signal-processing)
- [ ] [spark-k8s-anomaly-detection-taxi-data](https://docs.stackable.tech/home/nightly/demos/spark-k8s-anomaly-detection-taxi-data)
- [ ] [trino-iceberg](https://docs.stackable.tech/home/nightly/demos/trino-iceberg)
- [ ] [trino-taxi-data](https://docs.stackable.tech/home/nightly/demos/trino-taxi-data)
```

<details>
<summary>Instructions</summary>

These instructions are for deploying the nightly demo, as well as upgrading the operators and CRDS.

```shell
# Install demo (stable operators)
stackablectl demo install <DEMO_NAME>

# --- IMPORTANT ---
# Run through the nightly demo instructions (refer to the tasklist below).

# Get a list of installed operators
stackablectl operator installed --output=plain

# --- OPTIONAL ---
# Sometimes it is necessary to upgrade Helm charts. Look for other Helm Charts
# which might need updating.

# First, see which charts are installed. You can ignore the stackable-operator
# charts, or anything that might have been installed outside of this demo.
helm list

# Next, add the applicable Helm Chart repositories. For example:
helm repo add minio https://charts.min.io/
helm repo add bitnami https://charts.bitnami.com/bitnami

# Finally, upgrade the Charts. For example:
helm upgrade minio minio/minio --version x.x.x
helm upgrade postgresql-hive bitnami/postgresql --version x.x.x
# --- OPTIONAL END ---

# Uninstall operators
stackablectl release uninstall <CURRENT_RELEASE>

# Update CRDs to nightly version (on main)
# Repeat this for every operator used by the demo
kubectl replace -f https://raw.githubusercontent.com/stackabletech/commons-operator/main/deploy/helm/commons-operator/crds/crds.yaml
kubectl replace -f https://raw.githubusercontent.com/stackabletech/...-operator/main/deploy/helm/...-operator/crds/crds.yaml

# Install nightly version of operators (use the list from the earlier step
# before deleting the operators)
stackablectl operator install commons ...

# Optionally update the product versions in the CRDs, e.g.:
kubectl patch hbaseclusters/hbase --type='json' -p='[{"op": "replace", "path": "/spec/image/productVersion", "value":"x.x.x"}]' # changed
```

</details>

**Comment by xeniape** [comment]
:orange_circle: **airflow-scheduled-job**

Anomalies during upgrade process:
- airflow-webserver restarts because of OOMKilled (not sure if coincidental or happens when accessing the ui)
- various UI elements/information not loading (dots in screenshot, might be related to the OOM problem) -> after increasing the memory resources, everything loaded
![Image](https://github.com/user-attachments/assets/185b47b0-085e-45d2-a190-8d4f0b93e2ab)
- when rerunning the `sparkapp_dag` after the upgrade, the `spark_pi_monitor` task is marked as failed, but didn't see any errors in the container logs and the SparkApplications in the cluster all had the status `Succeeded`

Anomalies during clean installation of nightly version:
- `sparkapp_dag` also fails here on the `spark_pi_monitor` task
- No OOM problems when installing the nightly version of the demo directly

**Comment by NickLarsenNZ** [comment]
> after increasing the memory resources, everything loaded

@xeniape, is there a PR for the resource increases? I have seen the OOM problem before, and I believe @sbernauer resolved it with more resources.

**Comment by sbernauer** [comment]
>  I have seen the OOM problem before, and I believe @sbernauer resolved it with more resources

Yes, but I can not find any commit for this any more... I would be in favor of bumping the memory, maybe even the default resources of airflow-operator. I have seen so many customer requests because of OOM, I would like to give the best experience to especially new users trying out demos (and playing around with them)

**Comment by Techassi** [comment]
#### ⌛ airflow-scheduled-job

Findings during initial installation:

- A lot of pods took long to initialize. This however could be related to my local hardware.
- Other than that, the demo worked fine

**Comment by NickLarsenNZ** [comment]
⌛ **data-lakehouse-iceberg-trino-spark**

...

**Comment by Techassi** [comment]
#### ⌛ logging

...

**Comment by labrenbe** [comment]
#### 🟢  trino-taxi-data

- Initial installation worked without any issues.
- Upgrade also worked without any issues.

**Comment by nightkr** [comment]
🟠 **nifi-kafka-druid-earthquake-data**

Cluster environment: k3s v1.31.0-k3s1 (via k3d)

# Upgrade

Upgraded to:
- Druid 30.0.0
- Kafka 3.8.0
- Left NiFi, Superset, ZooKeeper alone as they have no new stable version according to the docs

Notes:
- Had to delete kafka STS manually (due to the listener migration)
- Kafka TLS credentials have moved, had to change the kcat command to `kubectl exec -it kafka-broker-default-0 -c kcat-prober -- /bin/bash -c "/stackable/kcat -b localhost:9093 -X security.protocol=SSL -X ssl.key.location=/stackable/tls-kcat/tls.key -X ssl.certificate.location=/stackable/tls-kcat/tls.crt -X ssl.ca.location=/stackable/tls-kcat/ca.crt -L"` (and similar for the other kcat commands)
- Druid is unhappy after upgrade (supervisor status: "LOST_CONTACT_WITH_STREAM")
  - `"message": "org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition earthquakes-7 could be determined",`
  - Seemed to recover eventually, maybe this is just a leftover issue from the upgrade?

# Clean install

Notes:
- Same TLS issue as when upgrading
- Druid only shows processed unless I go to "view raw", not thrownaway/unparseable (I assume this was also a thing when upgrading, but I didn't notice)
- No data has been pushed to deep storage yet, waiting for that to clear

**Comment by adwk67** [comment]
🟠 **jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data**

- clean install: no problems
- upgrade:

**Comment by adwk67** [comment]
🟠 **spark-k8s-anomaly-detection-taxi-data**
- clean install:
- upgrade:

**Comment by adwk67** [comment]
🟠 **trino-iceberg**

- clean install: no problems
- upgrade:

**Comment by nightkr** [comment]
🟡   **nifi-kafka-druid-water-level-data**

Cluster environment: k3s v1.31.0-k3s1 (via k3d)

# Upgrade

Upgraded to:
- Druid 30.0.0
- Kafka 3.8.0
- Left NiFi, Superset, ZooKeeper alone as they have no new stable version according to the docs

Notes:
- Had to delete kafka STS manually (due to the listener migration)
- `stackablectl stacklet list` used old format for Kafka
- Kafka TLS credentials have moved, had to change the kcat command to `kubectl exec -it kafka-broker-default-0 -c kcat-prober -- /bin/bash -c "/stackable/kcat -b localhost:9093 -X security.protocol=SSL -X ssl.key.location=/stackable/tls-kcat/tls.key -X ssl.certificate.location=/stackable/tls-kcat/tls.crt -X ssl.ca.location=/stackable/tls-kcat/ca.crt -L"` (and similar for the other kcat commands)
- Broken link in demo docs to cert warning
- Druid only shows processed unless I go to "view raw", not thrownaway/unparseable
- According to the Druid UI, the average `stations` row size is 0B, but if I view the data it still looks correct
  - Measurements *does* have a calculated row size
  - Seems to be due to it not having been persisted yet

# Clean install

Notes:
- Same issues as when upgrading
- Minio is empty since Druid hasn't had time to flush yet (I assume this is the good old Druid flushing delay...)

**Comment by NickLarsenNZ** [comment]
⌛ **hbase-hdfs-load-cycling-data**

...

**Comment by xeniape** [comment]
⌛  **end-to-end-security**

Anomalies during upgrade process:
- Analysis needed for HDFS <-> Kerberos errors after operators upgrade when trying the [HDFS upgrade process](https://docs.stackable.tech/home/nightly/hdfs/usage-guide/upgrading#_preparing_hdfs). Internal discussion here: https://stackable-workspace.slack.com/archives/C04072NLUP7/p1731599614215069

Anomalies during clean installation of nightly version:
- None
