### ISSUE TITLE
chore(tracking): Ensure integration tests are successful on OpenShift for 24.11

### ISSUE THREAD

**Issue by adwk67** [stackabletech/issues#664]
```[tasklist]
### Integration Tests on Openshift
- [x] airflow-operator @adwk67 Overrides test fails on redis/postgresql install. Fixed in https://github.com/stackabletech/airflow-operator/pull/531
- [x] commons-operator
- [x] druid-operator @adwk67
- [x] hbase-operator
- [x] hdfs-operator
- [x] hello-world-operator
- [x] hive-operator. @adwk67 Flakiness: cluster-operation test failed first time but was OK when run in isolation.
- [x] kafka-operator
- [x] listener-operator. @adwk67 Some test failures. See https://github.com/stackabletech/listener-operator/pull/246
- [x] nifi-operator @adwk67 Test failures: smoke, upgrade. Testing with https://github.com/stackabletech/nifi-operator/pull/708
- [x] opa-operator
- [x] secret-operator @adwk67 Some test failures. See https://github.com/stackabletech/secret-operator/pull/518 and the listener PR above.
- [x] spark-k8s-operator @adwk67 hbase-connector test fails. Works with the listener PR.
- [x] superset-operator @adwk67
- [x] trino-operator
- [x] zookeeper-operator @adwk67
```

**Comment by adwk67** [comment]
#### Nifi
- upgrade test
  - reporting task for 2.0.0. fails with
  - Exception: Failed to retrieve ReportingTask[StackablePrometheusReportingTask/8081]: (409)

**Comment by adwk67** [comment]
Closing as all operators have been tested.
