### ISSUE TITLE
serviceAccount and roleBinding objects can accidentally get deleted

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/issues#675]
**Observed Behavior**
When deploying multiple clusters of the same product (Airflow, NiFi, ...) into one namespace and then deleting one of them, it can happen that the `roleBinding` and `serviceAccount` objects that are shared by all these clusters accidentally get deleted as well.

**Root Cause**
The reason for this is shown in the following diagram 

![Image](https://github.com/user-attachments/assets/156ac97f-a159-47d4-99b3-a1b41bed202d)

All cluster objects share the same roleBinding and serviceAccount objects. Which in principle works fine, as the content is the same with regards to every cluster.

Stackable operators track the resources they deploy via labels to ensure that they can delete "orphaned" objects that are no longer needed, this is done via the labels `app.kubernetes.io/managed-by` and `app.kubernetes.io/instance` as can be seen in the snippet below.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2024-11-22T13:23:34Z"
  labels:
    app.kubernetes.io/instance: simple-nifi2
    app.kubernetes.io/managed-by: nifi.stackable.tech_nificluster
    app.kubernetes.io/name: nifi
  name: simple-nifi2-serviceaccount
```

Whenever the object with the type matching `mangedBy` and the name matching `instance` is deleted, this serviceAccount will also be deleted as it is considered "orphaned" now.

In the scenario shown in the diagram above, the value for the `instance` label will constantly be set to either "simple-nifi" or "simple-nifi2" depending on which cluster was last changed. If that cluster is then deleted, the roleBinding and serviceAccount will also be cleaned up until the other cluster is next reconciled and the objects are recreated.

**Workaround**
The only currently know workaround is to trigger a manual reconciliation of the now broken cluster object by making some change, for example adding an annotation:

`kubectl patch zookeepercluster/simple-zk --type=merge --patch=({metadata:{annotations:{touch: (date now)}}} | to json)`

**Fix**
The best fix for this seems to be to move to individual roleBinding and serviceAccount objects for every cluster, instead of sharing them.

**Todos**
- [x] https://github.com/stackabletech/airflow-operator/pull/545
- [x] https://github.com/stackabletech/airflow-operator/pull/546
- [x] https://github.com/stackabletech/airflow-operator/pull/548
- [x] https://github.com/stackabletech/druid-operator/pull/657
- [x] https://github.com/stackabletech/druid-operator/pull/658
- [x] https://github.com/stackabletech/druid-operator/pull/659
- [x] https://github.com/stackabletech/hbase-operator/pull/594
- [x] https://github.com/stackabletech/hbase-operator/pull/595
- [x] https://github.com/stackabletech/hbase-operator/pull/597
- [x] https://github.com/stackabletech/hdfs-operator/pull/616
- [x] https://github.com/stackabletech/hdfs-operator/pull/617
- [x] https://github.com/stackabletech/hdfs-operator/pull/618
- [x] https://github.com/stackabletech/hive-operator/pull/544
- [x] https://github.com/stackabletech/hive-operator/pull/545
- [x] https://github.com/stackabletech/hive-operator/pull/547
- [x] https://github.com/stackabletech/kafka-operator/pull/793
- [x] https://github.com/stackabletech/kafka-operator/pull/794
- [x] https://github.com/stackabletech/kafka-operator/pull/795
- [x] https://github.com/stackabletech/nifi-operator/pull/717
- [x] https://github.com/stackabletech/nifi-operator/pull/719
- [x] https://github.com/stackabletech/nifi-operator/pull/720
- [x] https://github.com/stackabletech/opa-operator/pull/656
- [x] https://github.com/stackabletech/opa-operator/pull/657
- [x] https://github.com/stackabletech/opa-operator/pull/658
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/498
- [x] https://github.com/stackabletech/spark-k8s-operator/pull/500
- [x] https://github.com/stackabletech/superset-operator/pull/568
- [x] https://github.com/stackabletech/superset-operator/pull/570
- [x] https://github.com/stackabletech/superset-operator/pull/571
- [x] https://github.com/stackabletech/trino-operator/pull/672
- [x] https://github.com/stackabletech/trino-operator/pull/674
- [x] https://github.com/stackabletech/trino-operator/pull/675
- [x] https://github.com/stackabletech/zookeeper-operator/pull/889
- [x] https://github.com/stackabletech/zookeeper-operator/pull/890
- [x] https://github.com/stackabletech/zookeeper-operator/pull/891

**Integration tests Kind & Managed**

- [x]  Airflow - Kind 1.29.8 ✅ - [OKD 4.15](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/airflow-operator-it-custom/12/) ✅ - @siegfriedweber 
- [x]  Druid - Kind 1.29.8 ✅ - [OKD 4.15](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/druid-operator-it-custom/21/) ✅ - @siegfriedweber 
- [x]  HBase - kind 1.29.2 ✅ - [OKD 4.14](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hbase-operator-it-custom/39/) ✅ - 2 tests failed, succeeded manually - @maltesander 
- [x]  Hadoop HDFS - AKS 1.29.9 ✅  - [OKD 4.15](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/11/) ✅ - @soenkeliebau 
- [x]  Hive - kind 1.29.2 ✅  - [OKD 4.14](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hive-operator-it-custom/11/) ✅ - @maltesander 
- [x]  Kafka - Kind 1.29.8 ✅ - [OKD 4.15](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/kafka-operator-it-custom/16/) ✅ - @siegfriedweber 
- [x]  NiFi - AKS 1.29.9 ✅  - [OKD 4.15](https://testing.stackable.tech/job/nifi-operator-it-custom/25/) ✅ - @soenkeliebau 
- [x]  Spark
- [x]  Superset - Kind 1.29.8 ✅ - [OKD 4.15](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/superset-operator-it-custom/8/) ✅ - @siegfriedweber 
- [x] Trino - AKS 1.29.9 ✅ - OKD 4.14 ✅  - @soenkeliebau 
- [x]  ZooKeeper - kind 1.29.2 ✅  - [OKD 4.14](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/9/) ✅ -  @maltesander 
- [x] OPA - kind 1.29.2 ✅  - [OKD 4.14](https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/opa-operator-it-custom/9/) ✅ - @maltesander

**Comment by maltesander** [comment]
Spark only requires it in the history server and seems to be correct https://github.com/stackabletech/spark-k8s-operator/blob/ab33c0de443ab391734f6c1bd6c1ce7d4a48fe4c/rust/operator-binary/src/history/history_controller.rs#L476

Only difference is `name_any` vs `name_unchecked`.

**Comment by maltesander** [comment]
```[tasklist]
### Integration tests Kind & Managed
- [ ] Airflow - Malte
- [ ] Druid
- [ ] HBase - Malte
- [ ] Hadoop HDFS
- [ ] Hive
- [ ] Kafka
- [ ] NiFi 
- [ ] Spark
- [ ] Superset
- [ ] Trino
- [ ] ZooKeeper - Malte
- [ ] OPA
```

**Comment by maltesander** [comment]
# Zookeeper

## Kind

```
stackablectl op in commons secret listener zookeeper=0.0.0-pr889 && \
./scripts/run_tests.sh --skip-release --parallel=2
```

```
--- PASS: kuttl (529.46s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/znode_zookeeper-latest-3.9.2_openshift-false (81.10s)
        --- PASS: kuttl/harness/cluster-operation_zookeeper-latest-3.9.2_openshift-false (85.97s)
        --- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-false_use-client-auth-tls-true_openshift-false (248.98s)
        --- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-true_use-client-auth-tls-true_openshift-false (244.18s)
        --- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-true_use-client-auth-tls-false_openshift-false (90.14s)
        --- PASS: kuttl/harness/delete-rolegroup_zookeeper-3.9.2_openshift-false (135.66s)
        --- PASS: kuttl/harness/smoke_zookeeper-3.9.2_use-server-tls-false_use-client-auth-tls-false_openshift-false (52.50s)
        --- PASS: kuttl/harness/logging_zookeeper-3.9.2_openshift-false (63.63s)
PASS
```

## Managed

running https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/zookeeper-operator-it-custom/9/

**Comment by maltesander** [comment]
# Hive

## Kind 🟠

```
stackablectl op in commons secret listener hive=0.0.0-pr544 && \
./scripts/run_tests.sh --skip-release --parallel=2
```

```
--- FAIL: kuttl (1359.63s)
    --- FAIL: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/logging_postgres-12.5.6_hive-4.0.0_openshift-false (400.87s)
        --- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-3.1.3_krb5-1.21.1_openshift-false_s3-use-tls-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (452.56s)
        --- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-3.1.3_openshift-false_s3-use-tls-true (162.94s)
        --- PASS: kuttl/harness/logging_postgres-12.5.6_hive-3.1.3_openshift-false (203.31s)
        --- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-4.0.0_openshift-false_s3-use-tls-true (127.02s)
        --- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-4.0.0_openshift-false_s3-use-tls-false (106.88s)
        --- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-4.0.0_krb5-1.21.1_openshift-false_s3-use-tls-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (115.41s)
        --- PASS: kuttl/harness/smoke_postgres-12.5.6_hive-3.1.3_openshift-false_s3-use-tls-false (121.92s)
        --- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-4.0.0_krb5-1.21.1_openshift-false_s3-use-tls-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (117.97s)
        --- PASS: kuttl/harness/upgrade_postgres-12.5.6_hive-old-3.1.3_hive-new-4.0.0_openshift-false (87.78s)
        --- PASS: kuttl/harness/kerberos-s3_postgres-12.5.6_hive-3.1.3_krb5-1.21.1_openshift-false_s3-use-tls-true_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (147.11s)
        --- PASS: kuttl/harness/resources_hive-4.0.0_openshift-false (137.81s)
        --- PASS: kuttl/harness/orphaned-resources_hive-latest-4.0.0_openshift-false (207.43s)
        --- FAIL: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-4.0.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_openshift-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (70.05s)
        --- PASS: kuttl/harness/resources_hive-3.1.3_openshift-false (126.87s)
        --- FAIL: kuttl/harness/kerberos-hdfs_postgres-12.5.6_hive-3.1.3_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_openshift-false_kerberos-realm-PROD.MYCORP_kerberos-backend-mit (49.23s)
        --- PASS: kuttl/harness/cluster-operation_hive-latest-4.0.0_openshift-false (70.15s)
FAIL
ERROR:root:kuttl failed

```

## Openshift 4.14 (okd)

running

**Comment by soenkeliebau** [comment]
# Trino

## AKS 1.29.9 🟢

```
stackablectl -r sup148release.yaml re in sup148
./scripts/run_tests.sh --skip-release --test-suite nightly
```

```
=== NAME  kuttl
    harness.go:408: run tests finished
    harness.go:516: cleaning up
    harness.go:573: removing temp folder: ""
--- PASS: kuttl (1487.91s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/orphaned-resources_trino-latest-455_openshift-false (103.68s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-false_use-tls-false_use-internal-tls-true_openshift-false (84.93s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-true_use-tls-true_use-internal-tls-true_openshift-false (88.36s)
        --- PASS: kuttl/harness/authentication_trino-latest-455_ldap-use-tls-false_openshift-false (334.47s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-true_use-tls-true_use-internal-tls-false_openshift-false (136.83s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-true_use-tls-false_use-internal-tls-true_openshift-false (83.84s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-false_use-tls-true_use-internal-tls-true_openshift-false (87.86s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-true_use-tls-false_use-internal-tls-false_openshift-false (141.77s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-false_use-tls-true_use-internal-tls-false_openshift-false (82.93s)
        --- PASS: kuttl/harness/tls_trino-latest-455_use-authentication-false_use-tls-false_use-internal-tls-false_openshift-false (80.05s)
        --- PASS: kuttl/harness/opa-authorization_trino-latest-455_hive-latest-4.0.0_opa-0.66.0_keycloak-25.0.0_openshift-false (377.39s)
        --- PASS: kuttl/harness/cluster-operation_trino-latest-455_openshift-false (81.90s)
        --- PASS: kuttl/harness/smoke_trino-455_hive-4.0.0_opa-0.66.0_hdfs-3.4.0_zookeeper-3.9.2_s3-use-tls-true_openshift-false (602.10s)
        --- PASS: kuttl/harness/resources_trino-latest-455_openshift-false (66.87s)
        --- PASS: kuttl/harness/logging_trino-455_openshift-false (80.48s)
        --- PASS: kuttl/harness/authentication_trino-latest-455_ldap-use-tls-true_openshift-false (292.45s)
PASS
```

## Openshift 4.14 (okd)

...

**Comment by soenkeliebau** [comment]
# NiFi

## AKS 1.29.9 🟢

```
stackablectl -r sup148release.yaml re in sup148
./scripts/run_tests.sh --skip-release --test-suite nightly
```

```
=== NAME  kuttl
    harness.go:408: run tests finished
    harness.go:516: cleaning up
    harness.go:573: removing temp folder: ""
--- PASS: kuttl (784.03s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/cluster_operation_zookeeper-latest-3.9.2_nifi-latest-2.0.0_openshift-false (122.19s)
        --- PASS: kuttl/harness/smoke_zookeeper-3.9.2_nifi-2.0.0_openshift-false_listener-class-external-unstable (177.83s)
        --- PASS: kuttl/harness/resources_zookeeper-latest-3.9.2_nifi-2.0.0_openshift-false (72.75s)
        --- PASS: kuttl/harness/upgrade_zookeeper-latest-3.9.2_nifi_old-1.27.0_nifi_new-2.0.0_openshift-false (389.41s)
        --- PASS: kuttl/harness/logging_zookeeper-latest-3.9.2_nifi-2.0.0_openshift-false (98.80s)
        --- PASS: kuttl/harness/orphaned_resources_zookeeper-latest-3.9.2_nifi-2.0.0_openshift-false (90.33s)
        --- PASS: kuttl/harness/oidc_zookeeper-latest-3.9.2_nifi-2.0.0_oidc-use-tls-true_openshift-false (228.17s)
        --- PASS: kuttl/harness/smoke_zookeeper-3.9.2_nifi-2.0.0_openshift-false_listener-class-cluster-internal (170.96s)
        --- PASS: kuttl/harness/ldap_zookeeper-latest-3.9.2_nifi-2.0.0_ldap-use-tls-true_openshift-false (182.96s)
PASS
```

## Openshift 4.14 (okd)

...

**Comment by soenkeliebau** [comment]
# HDFS

## AKS 1.29.9 🟢

```
stackablectl -r sup148release.yaml re in sup148
./scripts/run_tests.sh --skip-release --test-suite nightly
````

``
=== NAME  kuttl
    harness.go:408: run tests finished
    harness.go:516: cleaning up
    harness.go:573: removing temp folder: ""
--- PASS: kuttl (2689.42s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/logging_hadoop-3.4.0_zookeeper-latest-3.9.2_openshift-false (435.07s)
        --- PASS: kuttl/harness/topology-provider_hadoop-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_kerberos-backend-mit_openshift-false (267.87s)
        --- PASS: kuttl/harness/kerberos_hadoop-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_opa-0.67.1_kerberos-realm-PROD.MYCORP_kerberos-backend-mit_openshift-false (1098.23s)
        --- PASS: kuttl/harness/smoke_hadoop-3.4.0_zookeeper-3.9.2_zookeeper-latest-3.9.2_number-of-datanodes-2_datanode-pvcs-2hdd-1ssd_listener-class-external-unstable_openshift-false (232.22s)
        --- PASS: kuttl/harness/cluster-operation_hadoop-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (230.92s)
        --- PASS: kuttl/harness/orphaned-resources_hadoop-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (144.50s)
        --- PASS: kuttl/harness/profiling_hadoop-3.4.0_zookeeper-latest-3.9.2_openshift-false (171.48s)
        --- PASS: kuttl/harness/kerberos_hadoop-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_opa-0.67.1_kerberos-realm-CLUSTER.LOCAL_kerberos-backend-mit_openshift-false (1178.05s)
        --- PASS: kuttl/harness/smoke_hadoop-3.4.0_zookeeper-3.9.2_zookeeper-latest-3.9.2_number-of-datanodes-2_datanode-pvcs-2hdd-1ssd_listener-class-cluster-internal_openshift-false (811.96s)
PASS
```

## Openshift 4.15 (okd) 🟢

https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/11/

**Comment by maltesander** [comment]
# HBase

## Kind 1.29.2 🟢

```
stackablectl op in commons secret listener zookeeper=0.0.0-pr889 opa=0.0.0-pr656 hdfs=0.0.0-pr616 hbase=0.0.0-pr594 && \
./scripts/run_tests.sh --skip-release --parallel=2 --test-suite nightly
```

```
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/logging_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (202.80s)
        --- PASS: kuttl/harness/snapshot-export_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (300.06s)
        --- PASS: kuttl/harness/opa_hbase-opa-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_opa-0.67.1_openshift-false (299.96s)
        --- PASS: kuttl/harness/overrides_hbase-latest-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (122.42s)
        --- FAIL: kuttl/harness/kerberos_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_listener-class-external-unstable_kerberos-realm-PROD.MYCORP_kerberos-backend-mit_openshift-false (724.16s)
        --- PASS: kuttl/harness/kerberos_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_krb5-1.21.1_listener-class-cluster-internal_kerberos-realm-PROD.MYCORP_kerberos-backend-mit_openshift-false (653.44s)
        --- PASS: kuttl/harness/orphaned_resources_hbase-latest-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (299.98s)
        --- PASS: kuttl/harness/profiling_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (300.05s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.18_hdfs-3.4.0_zookeeper-3.9.2_listener-class-cluster-internal_openshift-false (184.58s)
        --- PASS: kuttl/harness/omid_hbase-2.4.18_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false_omid-1.1.2 (415.40s)
        --- PASS: kuttl/harness/smoke_hbase-2.4.18_hdfs-3.4.0_zookeeper-3.9.2_listener-class-external-unstable_openshift-false (299.97s)
        --- PASS: kuttl/harness/resources_hbase-latest-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (112.00s)
        --- PASS: kuttl/harness/cluster-operation_hbase-latest-2.6.0_hdfs-latest-3.4.0_zookeeper-latest-3.9.2_openshift-false (144.05s)
```

## Openshift 4.14 (okd)

**Comment by siegfriedweber** [comment]
scheduled for SDP 24.11.1

**Comment by lfrancke** [comment]
Could you please add a release note snippet for this?

**Comment by siegfriedweber** [comment]
# Release notes

## Breaking changes

Distinct ServiceAccounts are now used for the Stacklets, so that multiple Stacklets of the same product can be deployed in one namespace. Existing Stacklets will use the newly created ServiceAccounts after restart. Manually adapted ServiceAccounts must be updated.
