### ISSUE TITLE
chore(tracking): SDP Release 24.11.1

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/issues#683]
# Stackable Release 24.11.1

> [!IMPORTANT]
> Important dates:
> - ... - Release planning
> - 2025-01-20 - Target release date

## Release checklists

Replace the items in the task lists below with the applicable Pull Requests / Issues

### General Pre-Requisites (before Feature Freeze)

> [!NOTE]
> Most of these tasks are not required for a patch release..

```[tasklist]
### Early Pre-release tasks
- [ ] https://github.com/stackabletech/issues/issues/684
- [x] ~Define product versions to include in the next release~ Patch release
- [x] ~[Update and release operator-rs workspace members](https://github.com/stackabletech/operator-rs/issues/new?template=release-workspace-members.md)~
- [x] ~[Update Rust toolchain of operators](https://github.com/stackabletech/operator-templating/issues/new?template=pre-release.md)~
- [x] ~[Update Rust dependencies of operators](https://github.com/stackabletech/issues/issues/new?template=pre-release-operator-rust-deps.md)~
- [x] ~[Update Container Images](https://github.com/stackabletech/docker-images/issues/new?template=early-pre-release.md)~
```

> [!NOTE]
> These tasks are note required for a patch release.

```[tasklist]
### Pre-release
- [ ] ~Run all of the test suites in Jenkins (with all product versions, not just "nightly")~
- [x] ~[Check and update getting-started scripts](https://github.com/stackabletech/issues/issues/new?template=pre-release-getting-started-scripts.md)~
- [x] ~[Check and update demo charts](https://github.com/stackabletech/demos/issues/new?template=pre-release-chart-updates.md)~
- [x] ~[Test demos and upgrade from stable to nightly release](https://github.com/stackabletech/demos/issues/new?template=pre-release-upgrade-testing.md)~
- [x] ~Ensure integration tests are successful on OpenShift~
- [x] ~Check stackable-utils scripts in dry-run mode work~
- [ ] https://github.com/stackabletech/airflow-operator/pull/567
- [ ] https://github.com/stackabletech/commons-operator/pull/317
- [ ] https://github.com/stackabletech/druid-operator/pull/675
- [ ] https://github.com/stackabletech/hbase-operator/pull/610
- [ ] https://github.com/stackabletech/hdfs-operator/pull/638
- [ ] https://github.com/stackabletech/hello-world-operator/pull/150
- [ ] https://github.com/stackabletech/hive-operator/pull/558
- [ ] https://github.com/stackabletech/kafka-operator/pull/808
- [ ] https://github.com/stackabletech/listener-operator/pull/266
- [ ] https://github.com/stackabletech/nifi-operator/pull/735
- [ ] https://github.com/stackabletech/opa-operator/pull/674
- [ ] https://github.com/stackabletech/secret-operator/pull/540
- [ ] https://github.com/stackabletech/spark-k8s-operator/pull/513
- [ ] https://github.com/stackabletech/superset-operator/pull/584
- [ ] https://github.com/stackabletech/trino-operator/pull/691
- [ ] https://github.com/stackabletech/zookeeper-operator/pull/903
- [ ] https://github.com/stackabletech/docker-images/pull/973
```

### Other Pre-Requisites (before Feature Freeze)

Search for open issues labeleded with [`scheduled-for/24.11.1`](https://github.com/search?q=org%3Astackabletech+label%3Ascheduled-for%2F24.11.1&type=issues&state=open)

```[tasklist]
### Other release-specific pre-requisites
- [x] Choose a viable release candidate: 24.11.1-rc2
- [x] Check that all PRs (e.g. with labels scheduled-for/xx.yy.z) have been merged
- [x] Discuss where the patch release notes go (probably a new section above the 24.11 release?) See https://github.com/stackabletech/documentation/pull/703
```

### Feature freeze

This will not be so crucial with release branches, but is nonetheless sensible as it will make it easier to cherry-pick any release-related bugfixes from main into the release branch.

### End of the release cycle (Release day)

```[tasklist]
#### Technical tasks
- [x] Run the stackable-utils release scripts for promoting `24.11.1-rc2` to `24.11.1` @adwk67
- [ ] https://github.com/stackabletech/crddocs/pull/46
- [x] Deploy CRD docs [website](https://crds.stackable.tech/) for the new release triggering the [deploy](https://github.com/stackabletech/crddocs/actions/workflows/deploy.yml) action
- [x] Test `stackablectl` with locally updated (to new release number) `releases.yaml` @Techassi
- [ ] https://github.com/stackabletech/release/pull/35
- [ ] https://github.com/stackabletech/issues/issues/688
- [ ] https://github.com/stackabletech/stackable-cockpit/pull/346
- [ ] https://github.com/stackabletech/demos/pull/138
- [ ] https://github.com/stackabletech/demos/issues/137
- [x] Check that an upgrade can be performed on an existing cluster without data loss (cycling demo) @NickLarsenNZ
- [x] Run all integration tests for `x86_64` @NickLarsenNZ
- [ ] ~Run all integration tests for `aarch64`~ Deferring until integrations tests are moved to Github Actions
- [x] OpenShift testing (discuss internally) - will be done as part of the OS certification
```

> [!TIP]
> Name the release-notes branch `docs/release-notes-24.11.1` so that the link below takes you directly to the [Pull Request template][docs-pr-template].

[docs-pr-template]: https://github.com/stackabletech/documentation/tree/main/.github/PULL_REQUEST_TEMPLATE/release-notes.md&title=chore(tracking):%20Release%20Notes%20for%20SDP%2024.11.1

```[tasklist]
#### Documentation tasks
- [x] Create a stackabletech/documentation branch called `docs/release-notes-24.11.1`
- [ ] https://github.com/stackabletech/documentation/pull/703
- [ ] https://github.com/stackabletech/documentation/pull/704
- [x] Add the 24.11.1 section titles to changelogs in the `main` branch @adwk67
- [x] Cherry-pick the updated release notes into the release branch
- [x] Update SDP release version in `main` [stackabletech/documentation/modules/ROOT/pages/getting-started.adoc](https://github.com/stackabletech/documentation/blob/main/modules/ROOT/pages/getting-started.adoc) and test the release install command
- [ ] https://github.com/stackabletech/documentation/pull/705
- [x] ~Update releases in the playbook (see [scripts/publish-new-version.sh](https://github.com/stackabletech/documentation/blob/main/scripts/publish-new-version.sh))~
- [x] ~Update antora.yaml version in stackabletech/demos on the release branch - the stackable-utils release-scripts should do this like they do for products and operators.~
- [x] ~Set the release to "Released" in the Feature Tracker and create a new release (how?)~
```

Marketing tasks can now reference published documentation.

```[tasklist]
#### Marketing tasks
- [x] ~Write marketing / customer oriented release summary to be published in the marketing channels~
- [x] ~Update the homepage banner (as long as we have it) to point to the new release~
- [x] ~Write a blogpost / news article announcing the new release (optional)~
- [x] ~Write a description of new demos for homepage/demos section~
- [x] ~Announce Release on LinkedIn~
- [x] ~Announce Release in Newsletter (optional)~
- [x] ~Produce a release highlight video (optional)~
- [x] ~Announce Release on Hacker News (optional)~
- [x] Post an announcement in the GitHub [Discussions Announcement forum](https://github.com/stackabletech/community/discussions/categories/announcements) and make it a pinned discussion while at the same time removing the old pinned thread @soenkeliebau
- [x] Post an announcement in Discord @soenkeliebau
- [x] ~Post an announcement on DOK Community in the #be-shameless Channel (Ping Lars or Jim)~
- [x] ~Post an announcement via OSBA (Ping Lars, info@osb-alliance.com)~
- [x] ~Send announcement to Kubernetes Podcast (Ping Lars)~
- [x] ~Send announcement to Heiser~
- [x] ~Ping the stackable-ionos-tech channel or anyone responsible once all tags are created~
```

```[tasklist]
#### Post-release tasks
- [x] Update the list of supported SDP releases in Jira (ping Jim)
- [x] Openshift certification.  [Tracking](https://github.com/stackabletech/issues/issues/690)
- [x] ~Mark any releases older than one year as "end-of-life" [in the documentation](https://github.com/stackabletech/documentation/blob/f751e7ff7cddacae7d2c6c2c6c1d1c877c7aa11c/antora.yml#L18)~
- [ ] Post 24.11.1 release retro (use issue created at the start of the process)
- [ ] https://github.com/stackabletech/issues/issues/686
- [ ] https://github.com/stackabletech/stackable-utils/pull/95
```

**Comment by Techassi** [comment]
Closing as completed.
