### ISSUE TITLE
Ship Druid Operator

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/issues#78]
- [x] Implement initial Druid Operator for all Server-/Process Types 
- [x] Load and Query Example Data

**Acceptance Criteria**
- [x] Druid Cluster can be deployed, configured by Stackable Platform
- [x] User documentation exists
- [x] Usage is shown by a simple example
